newrelic/entity-definitions

.github/pull_request_template.md
.github/workflows/validate-definition.yml
.gitignore
README.md
validator/README.md
validator/package-lock.json
validator/package.json
validator/schemas/entity-schema-v1.json
validator/schemas/golden-metrics-schema-v1.json
validator/schemas/summary-metrics-schema-v1.json
validator/tools/utils.js
validator/tools/validate_uniqueness.js

- Add validations with some documentation.
- Add github actions, PR template and .gitignore.
After this PR is merged I'll activate the actions so to verify that they run in the next PR (which will contain the first entity definitions)

Add validations

---

.gitignore
definitions/infra-etcd_cluster/dashboard.json
definitions/infra-etcd_cluster/definition.yml
definitions/infra-etcd_cluster/golden_metrics.yml
definitions/infra-etcd_cluster/summary_metrics.yml
definitions/infra-kubernetes_apiserver/definition.yml
definitions/infra-kubernetes_apiserver/golden_metrics.yml
definitions/infra-kubernetes_apiserver/summary_metrics.yml

Added the `INFRA-ETCD_CLUSTER` AND `INFRA-KUBERNETES_APISERVER` definitions, along with their summary and golden metrics, and a dashboard template for `INFRA-ETCD_CLUSTER`. 

Add new definitions

---

README.md
docs/example-entity-definition.yml
docs/example-entity-golden_metrics.yml
docs/example-entity-summary_metrics.yml
docs/golden_metrics.md
docs/summary_metrics.md

- Added tags and golden tags information on the README. 
- Added comments to the example definition fields as requested. 

Improve documentation for tags and example definition

---

README.md
definitions/infra-etcd_cluster/definition.yml
definitions/infra-kubernetes_apiserver/definition.yml
docs/example-entity-definition.yml
validator/schemas/entity-schema-v1.json

Based on feedback received: convert dashboardTemplate, summaryMetrics and goldenMetrics from a single file reference to an array. 

Convert dashboardTemplate and composite metrics into arrays

---

validator/tools/validate_uniqueness.js

Fixed an issue with the validator and the new schema format.

Fix identifier uniqueness validation

---

definitions/infra-etcd_cluster/dashboard.json
definitions/infra-kubernetes_apiserver/dashboard.json

Add dashboard for kubernetes_apiserver and modify the one of etcd_cluster

---

definitions/ext-tinyproxy/dashboard.json
definitions/ext-tinyproxy/definition.yml
definitions/ext-tinyproxy/golden_metrics.yml
definitions/ext-tinyproxy/summary_metrics.yml

Signed-off-by: JF Joly <joly.pro@gmail.com>

Adding Tinyproxy entity type

---

README.md
docs/example-entity-definition.yml
validator/schemas/entity-schema-v1.json
validator/tools/validate_uniqueness.js

- Support a condition that matches on the presence of a given attribute.
- Mention in the docs that the conditions are not cumulative (only one needs to be fulfilled) and fix the validator to reflect that.

Support attribute condition

---

definitions/infra-azureappserviceplan/definition.yml
definitions/infra-azureappserviceplan/summary_metrics.yml
definitions/infra-gcpkubernetescontainer/definition.yml
definitions/infra-gcpkubernetescontainer/summary_metrics.yml
definitions/infra-gcpkubernetesnode/definition.yml
definitions/infra-gcpkubernetesnode/summary_metrics.yml
definitions/infra-vspherecluster/definition.yml
definitions/infra-vspherecluster/summary_metrics.yml
definitions/infra-vspheredatacenter/definition.yml
definitions/infra-vspheredatacenter/summary_metrics.yml
definitions/infra-vspheredatastore/definition.yml
definitions/infra-vspheredatastore/summary_metrics.yml
definitions/infra-vspherehost/definition.yml
definitions/infra-vspherehost/summary_metrics.yml
definitions/infra-vsphereresourcepool/definition.yml
definitions/infra-vsphereresourcepool/summary_metrics.yml
definitions/infra-vspherevm/definition.yml
definitions/infra-vspherevm/summary_metrics.yml

These types where not pointing to the correct entity type. Now they are fixed and hence exported.
We are also updating to new types added today.
From now on all changes for summaries should happen in the public repo

Update summary metrics for vSphere, Azure & GCP

---

definitions/infra-azurefirewall/definition.yml
definitions/infra-azurefirewall/golden_metrics.yml

For some reason this type was not migrated. So i've manually migrated it.
From now one all GM changes should be done from this repo.

Provide golden metrics for azure firewall

---

definitions/infra-azuresqlserver/definition.yml
definitions/infra-azuresqlserver/summary_metrics.yml

added missing summary metrics for Azure Sql Server

---

README.md
docs/example-entity-definition.yml
validator/schemas/entity-schema-v1.json

Having a condition is mandatory for the synthesis. This PR marks it as such on the schema so that it'll be validated, the documentation has also been updated accordingly.

Make conditions mandatory

---

README.md
docs/example-entity-definition.yml
validator/schemas/entity-schema-v1.json

Add the alertable field to the configuration section.

Add alertable configuration

---

definitions/infra-host/definition.yml
definitions/infra-host/golden_metrics.yml

Added all golden tags as per guidelines for cloud entities.
Added network traffic metric (to complete n=4 recommended golden metrics)

infra-host golden tags and metrics update

---

definitions/infra-awsautoscalinggroup/definition.yml
definitions/infra-awscloudfrontdistribution/definition.yml
definitions/infra-awscloudfrontdistribution/golden_metrics.yml
definitions/infra-awsdynamodbglobalsecondaryindex/definition.yml
definitions/infra-awsdynamodbglobalsecondaryindex/golden_metrics.yml
definitions/infra-awsdynamodbregion/definition.yml
definitions/infra-awsdynamodbregion/golden_metrics.yml
definitions/infra-awsdynamodbtable/definition.yml
definitions/infra-awsdynamodbtable/golden_metrics.yml
definitions/infra-azureapplicationgateway/golden_metrics.yml

Hello Entity Platform, this is Helena :) 
AWSAUTOSCALINGGROUP
definition.yml: Adding region as key tag.
AWSCLOUDFRONTDISTRIBUTION
definition.yml: Adding region as key tag.
golden_metrics.yml: Adding uploaded and downloaded bytes as golden metrics
AWSDYNAMODBREGION
definition.yml: Adding key tags and golden metrics file
golden_metrics.yml: Adding system errors as golden metric
AWSDYNAMODBTABLE
definition.yml: Adding region and table status as key tags.
golden_metrics.yml: Fixing aggregation functions
AWSDYNAMODBGLOBALSECONDARYINDEX
definition.yml: Adding key tags and golden metrics file
golden_metrics: Provisioned and consumed read and write capacity units
AZUREAPPLICATIONGATEWAY
golden_metrics.yml: Fixing metric names and aggregation functions

Fix for Azure Application Gateway. Golden metrics and tags for AWS types

---

definitions/infra-azureapimanagementservice/definition.yml
definitions/infra-azureapimanagementservice/summary_metrics.yml
definitions/infra-azureappservicewebapp/definition.yml
definitions/infra-azureappservicewebapp/golden_metrics.yml
definitions/infra-azureappservicewebapp/summary_metrics.yml
definitions/infra-azurecosmosdbaccount/definition.yml
definitions/infra-azurecosmosdbaccount/golden_metrics.yml
definitions/infra-azurecosmosdbcollection/definition.yml
definitions/infra-azurecosmosdbcollection/golden_metrics.yml
definitions/infra-azurecosmosdbdatabase/definition.yml
definitions/infra-azurecosmosdbdatabase/golden_metrics.yml
definitions/infra-azurefunctionsapp/definition.yml
definitions/infra-azurefunctionsapp/golden_metrics.yml
definitions/infra-azurefunctionsapp/summary_metrics.yml
definitions/infra-azureloadbalancer/definition.yml
definitions/infra-azureloadbalancer/golden_metrics.yml
definitions/infra-azureloadbalancer/summary_metrics.yml
definitions/infra-azuremariadbserver/definition.yml
definitions/infra-azuremariadbserver/golden_metrics.yml
definitions/infra-azuremysqlserver/definition.yml
definitions/infra-azuremysqlserver/golden_metrics.yml
definitions/infra-azurepostgresqlserver/definition.yml
definitions/infra-azurepostgresqlserver/golden_metrics.yml

Update a bunch of Entity Types coming from Azure integrations. I updated golden tags, summary metrics and golden metrics.

Update azure entities

---

definitions/infra-gcpspannerdatabase/definition.yml
definitions/infra-gcpspannerdatabase/golden_metrics.yml

Added configuration for default golden metrics through the golden-metrics.yml file

Golden metrics configuration added for GCPSpannerDatabase

---

validator/schemas/summary-metrics-schema-v1.json

Add the eventObjectId enum so that it gets validated if used, also fix an error with the key metrics.

Update summary metrics schema

---

definitions/apm-application/golden_metrics.yml

apm-application response time x1000

---

definitions/infra-gcpappengineservice/definition.yml
definitions/infra-gcpappengineservice/golden_metrics.yml
definitions/infra-gcpappengineservice/summary_metrics.yml
definitions/infra-gcpbigquerydataset/definition.yml
definitions/infra-gcpbigquerydataset/golden_metrics.yml
definitions/infra-gcpbigquerydataset/summary_metrics.yml
definitions/infra-gcpbigquerytable/definition.yml
definitions/infra-gcpbigquerytable/golden_metrics.yml
definitions/infra-gcpbigquerytable/summary_metrics.yml
definitions/infra-gcpcloudfunction/definition.yml
definitions/infra-gcpcloudfunction/golden_metrics.yml
definitions/infra-gcpcloudfunction/summary_metrics.yml
definitions/infra-gcpcloudsql/definition.yml
definitions/infra-gcphttploadbalancer/definition.yml
definitions/infra-gcphttploadbalancer/golden_metrics.yml
definitions/infra-gcpinternalloadbalancer/definition.yml
definitions/infra-gcpinternalloadbalancer/golden_metrics.yml
definitions/infra-gcpinternalloadbalancer/summary_metrics.yml
definitions/infra-gcpspannerdatabase/definition.yml
definitions/infra-gcpspannerinstance/definition.yml
definitions/infra-gcpspannerinstance/golden_metrics.yml
definitions/infra-gcpstoragebucket/definition.yml
definitions/infra-gcpstoragebucket/golden_metrics.yml
definitions/infra-gcpstoragebucket/summary_metrics.yml

changes to enable goldenmetrics, goldentags and some modifications to summary metrics of the following entities:
GCPSPANNERINSTANCE
GCPSTORAGEBUCKET
GCPAPPENGINESERVICE
GCPBIGQUERYDATASET
GCPBIGQUERYTABLE
GCPCLOUDFUNCTION
GCPCLOUDSQL
GCPHTTPLOADBALANCER
GCPINTERNALLOADBALANCER

Fprats new golden metrics

---

definitions/infra-awskinesisanalyticsapplication/definition.yml
definitions/infra-awskinesisanalyticsapplication/golden_metrics.yml
definitions/infra-awskinesisanalyticsapplication/summary_metrics.yml
definitions/infra-awskinesisanalyticstask/definition.yml
definitions/infra-awskinesisanalyticstask/golden_metrics.yml
definitions/infra-awskinesisanalyticstask/summary_metrics.yml

Added missing golden tags and metrics for AWS Kinesis Analytics

Add golden tags and metrics for kinesis analytics

---

definitions/infra-azurestorageaccount/definition.yml
definitions/infra-azurestorageaccount/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/definition.yml
definitions/infra-azurevirtualmachinescaleset/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/summary_metrics.yml
definitions/infra-rabbitmqnode/definition.yml

Hi, this is Helena!
**infra-azurestorageaccount**
- I've added golden metrics and tags.
- These golden metrics are not broken down by blobs, tables, queues or files, but they give a high level idea of trends and spikes. 
**infra-azurevirtualmachinescaleset**
- I've added golden metrics, golden tags, and summary metrics.

Golden metrics and tags for Azure types

---

definitions/infra-na/definition.yml
validator/schemas/entity-schema-v1.json

Add INFRA-NA entity type and adapt schema validation

Add INFRA-NA entity type

---

definitions/ext-fastly_pop/definition.yml

FASTLY_POP: Remove summary metric def. reference

---

README.md
validator/schemas/entity-schema-v1.json

As part of synthesis work we increased the guid limits. Reflect that into the docs

Update docs to reflect guid length changes

---

definitions/infra-apacheserver/definition.yml
definitions/infra-apacheserver/golden_metrics.yml
definitions/infra-cassandranode/definition.yml
definitions/infra-elasticsearchnode/definition.yml
definitions/infra-kafkabroker/definition.yml
definitions/infra-mssqlinstance/definition.yml
definitions/infra-mysqlnode/definition.yml
definitions/infra-mysqlnode/golden_metrics.yml
definitions/infra-nginxserver/definition.yml
definitions/infra-postgresqlinstance/definition.yml
definitions/infra-redisinstance/definition.yml
definitions/infra-vspherecluster/definition.yml
definitions/infra-vspherecluster/golden_metrics.yml
definitions/infra-vspherehost/definition.yml
definitions/infra-vspherehost/golden_metrics.yml
definitions/infra-vspherevm/definition.yml
definitions/infra-vspherevm/golden_metrics.yml

Vsphere Cluster Entity Golden Metrics/Tags 

---

definitions/infra-awselasticacherediscluster/golden_metrics.yml

Fix some typos in the title of the metrics.

Fix typos in GM for AWSELASTICACHEREDISCLUSTER

---

definitions/ext-rhost/definition.yml

Since this PR was open for a lot of time we didn't spot that the tags needed to be in the new format

Change RHOST tags to the new format

---

definitions/infra-awsnlbtargetgroup/definition.yml
definitions/infra-awsnlbtargetgroup/golden_metrics.yml

Detected and solved an issue with NLB Target Groups:
- Golden Tags where the NLB ones instead of NLB Target Group
- Golden Metrics where NLB ones instead of NLB Target Group

Detected Issue with NLB Target groups Golden Tags and Metrics

---

definitions/infra-rabbitmqnode/definition.yml
validator/tools/validate_rules.js

Confirmed with the owner that they are OK with using these metrics instead of the ones we had defined internally.

Add rabbitmqnode SM and remove from disallow-list

---

definitions/infra-container/summary_metrics.yml
definitions/infra-host/summary_metrics.yml
definitions/mobile-application/summary_metrics.yml
validator/schemas/summary-metrics-schema-v1.json

Add back the title validation.
Add title to some recent SM definitions where it was missing.

Add missing title to SM

---

definitions/infra-azureapimanagementservice/golden_metrics.yml
definitions/infra-azureapimanagementservice/summary_metrics.yml

Fix the title of a metric which value is in milliseconds.

Update SM&GM for INFRA-AZUREAPIMANAGEMENTSERVICE

---

definitions/res-gitrepository/definition.yml

Add a git repo entity definition to allow the Entity Community team to execute on the steel thread.

Add a git repo definition

---

definitions/ext-network_synth/definition.yml
definitions/ext-network_synth/golden_metrics.yml
definitions/ext-network_synth/summary_metrics.yml

Building entities from [Kentik Synthetic Tests](https://kb.kentik.com/v4/Ma00.htm#Ma00-Synthetics_Overview) sent via the [Kentik Firehose](https://kb.kentik.com/v0/Fc19.htm#Fc19-About_Kentik_Firehose) to the Metric API

adding network synthetics entity

---

definitions/infra-kubernetesdeployment/definition.yml
definitions/infra-kubernetespod/definition.yml

Add rules for Kubernetes deployments. Plus update the pods' to include more tags: `k8s.deploymentName`,  `k8s.createdBy` and `k8s.createdKind`.

Add Kubernetes deployments synthesis rules and update the pod's

---

definitions/infra-awskinesisdeliverystream/summary_metrics.yml
definitions/infra-varnishinstance/summary_metrics.yml

Fixing some errors we found during the bot parsing implementation

Fix invalid nrqls

---

definitions/infra-kubernetes_statefulset/definition.yml

Add definition for the Kubernetes statufulset entity.

Add K8s statefulset entity definition

---

definitions/ext-pihole/golden_metrics.yml
definitions/ext-pihole/summary_metrics.yml

Fix a typo on the summary and golden metrics of Pi-Holes

---

definitions/infra-kubernetes_deployment/definition.yml
definitions/infra-kubernetes_deployment/golden_metrics.yml
definitions/infra-kubernetes_deployment/summary_metrics.yml

Add composite metrics and golden tags for k8s deployments

---

definitions/infra-kubernetes_statefulset/definition.yml
definitions/infra-kubernetes_statefulset/golden_metrics.yml
definitions/infra-kubernetes_statefulset/summary_metrics.yml

Add summary metrics, golden metrics and tags for K8s statefulset entity.

Add summary metrics, golden metrics and tags for K8s statefulset

---

definitions/ext-network_synth/dashboard.json
definitions/ext-network_synth/definition.yml

Adding dashboard following new public dashboard API format

adding dashboard

---

definitions/res-team/definition.yml

Models a team.  For now, not providing any golden / summary metric, nor synthesis rules, but this allows anyone to create a "resource" entity that can contain information about a team.

Add RES-TEAM modelling a team

---

README.md

Added a mention about our reserved tags on the `tags` section. I hope I'm not missing any.

Document reserved tags

---

README.md
definitions/ext-network_synth/dashboard.json
definitions/ext-pihole/dashboard.json
definitions/ext-redis/dashboard.json
definitions/ext-router/dashboard.json
definitions/ext-switch/dashboard.json
definitions/ext-tinyproxy/dashboard.json
definitions/ext-unix_host/dashboard.json
definitions/infra-etcd_cluster/dashboard.json
definitions/infra-kubernetes_apiserver/dashboard.json
docker-compose.yml
validator/README.md
validator/package-lock.json
validator/package.json
validator/sanitizeDashboards.Dockerfile
validator/schemas/dashboard-schema-v1.json
validator/tools/props.js
validator/tools/sanitize_dashboards.js
validator/tools/tests/dashboards/rawDashboard.json
validator/tools/tests/dashboards/sanitizedDashboard.json
validator/tools/utils.js
validator/tools/utils.test.js
validator/validateDefinitions.Dockerfile

Convert existing dashboards to the new format

Convert dashboard templates to new format

---

validator/tools/validate_rules.js

As of today we are hard coding the rules in the service.
But we will replace them with #167

Allow summaries for EXT-SERVICE

---

definitions/ext-pihole/dashboard.json

Fix ext-pihole dashboard's widget size

---

definitions/infra-kubernetes_pod/summary_metrics.yml

We're trying to make it less crowded. Both these two tags can be used as filters in the UX.

Remove node and namespace from pod summary metrics

---

definitions/ext-rf_scanner/definition.yml

Add distributionCenter tag to EXT-RF_SCANNER, requested by @batbore

Add distributionCenter tag to EXT-RF_SCANNER

---

definitions/ext-switch/dashboard.json

Fixing widget sizes and clearing unnecessary NRQL `WHERE` conditions

[EXT-SWITCH] fixing widget sizes and clearing unnecessary NRQL

---

definitions/ext-service/definition.yml

This tag seems to be missing from some entities.

Ensure that telemetry.sdk.language is set

---

definitions/ext-service/definition.yml

Add JFR as a source for EXT-SERVICE
we will need to add GM y SM later on

Add JFR source

---

definitions/ext-flow_device/dashboard.json
definitions/ext-flow_device/definition.yml
definitions/ext-flow_device/golden_metrics.yml
definitions/ext-flow_device/summary_metrics.yml

adding definition for flow devices from Kentik

adding flow device definition

---

definitions/ext-vpc_network/dashboard.json
definitions/ext-vpc_network/summary_metrics.yml

fixing some typos and updating the `Endpoints` SM and associated dashboard widget

fixing typos and "endpoints" SM and dashboard widget

---

definitions/infra-container/definition.yml

Don't encode identifier in GUID for INFRA-CONTAINER.

Don't encode identifier in GUID for INFRA-CONTAINER

---

definitions/ext-host/dashboard.json
definitions/ext-host/definition.yml
definitions/ext-mysql/golden_metrics.yml

-Updating some metrics that lost some periods during find and replace
-Adding missed prefixes to dashboard.json for ext-host
-Adding the dashboard to the definition file for ext-host

CBO-188 Gateway

---

definitions/infra-kubernetes_daemonset/dashboard.json
definitions/infra-kubernetes_deployment/dashboard.json
definitions/infra-kubernetes_pod/dashboard.json
definitions/infra-kubernetes_statefulset/dashboard.json

Update k8s dashboards after feedback and review

chore(FSI-2341): update k8s dashboards after review

---

definitions/infra-azureapimanagementservice/golden_metrics.yml
definitions/infra-azureapplicationgateway/golden_metrics.yml
definitions/infra-azureappservicewebapp/golden_metrics.yml
definitions/infra-azurecontainersinstancegroup/golden_metrics.yml
definitions/infra-azurecontainersmanagedcluster/golden_metrics.yml
definitions/infra-azurecontainersregistry/golden_metrics.yml
definitions/infra-azurecosmosdbaccount/golden_metrics.yml
definitions/infra-azurecosmosdbcollection/golden_metrics.yml
definitions/infra-azurecosmosdbdatabase/golden_metrics.yml
definitions/infra-azuredatafactorydatafactory/golden_metrics.yml
definitions/infra-azureeventhubcluster/golden_metrics.yml
definitions/infra-azureeventhubnamespace/golden_metrics.yml
definitions/infra-azurefirewall/golden_metrics.yml
definitions/infra-azurefrontdoorfrontdoor/golden_metrics.yml
definitions/infra-azurefunctionsapp/golden_metrics.yml
definitions/infra-azurekeyvaultvault/golden_metrics.yml
definitions/infra-azureloadbalancer/golden_metrics.yml
definitions/infra-azurelogicappsintegrationserviceenvironment/golden_metrics.yml
definitions/infra-azurelogicappsworkflow/golden_metrics.yml
definitions/infra-azuremariadbserver/golden_metrics.yml
definitions/infra-azuremysqlserver/golden_metrics.yml
definitions/infra-azurepostgresqlserver/golden_metrics.yml
definitions/infra-azurepowerbidedicatedcapacity/golden_metrics.yml
definitions/infra-azureservicebusnamespace/golden_metrics.yml
definitions/infra-azuresqldatabase/golden_metrics.yml
definitions/infra-azuresqlmanagedinstance/golden_metrics.yml
definitions/infra-azurestorageaccount/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/golden_metrics.yml

As pointed out, I made a mistake in the previous PR, using the wrong provider value.

Use correct provider for Azure

---

definitions/ext-pihole/definition.yml

Added instrumentation.provider and instrumentation.name tags to EXT-PIHOLE

---

definitions/infra-azureapimanagementservice/golden_metrics.yml
definitions/infra-azureapplicationgateway/golden_metrics.yml
definitions/infra-azureappservicewebapp/golden_metrics.yml
definitions/infra-azurecontainersinstancegroup/golden_metrics.yml
definitions/infra-azurecontainersmanagedcluster/golden_metrics.yml
definitions/infra-azurecontainersregistry/golden_metrics.yml
definitions/infra-azurecosmosdbaccount/golden_metrics.yml
definitions/infra-azurecosmosdbcollection/golden_metrics.yml
definitions/infra-azurecosmosdbdatabase/golden_metrics.yml
definitions/infra-azuredatafactorydatafactory/golden_metrics.yml
definitions/infra-azureeventhubcluster/golden_metrics.yml
definitions/infra-azureeventhubnamespace/golden_metrics.yml
definitions/infra-azurefirewall/golden_metrics.yml
definitions/infra-azurefrontdoorfrontdoor/golden_metrics.yml
definitions/infra-azurefunctionsapp/golden_metrics.yml
definitions/infra-azurekeyvaultvault/golden_metrics.yml
definitions/infra-azureloadbalancer/golden_metrics.yml
definitions/infra-azurelogicappsintegrationserviceenvironment/golden_metrics.yml
definitions/infra-azurelogicappsworkflow/golden_metrics.yml
definitions/infra-azuremariadbserver/golden_metrics.yml
definitions/infra-azuremysqlserver/golden_metrics.yml
definitions/infra-azurepostgresqlserver/golden_metrics.yml
definitions/infra-azurepowerbidedicatedcapacity/golden_metrics.yml
definitions/infra-azureservicebusnamespace/golden_metrics.yml
definitions/infra-azuresqldatabase/golden_metrics.yml
definitions/infra-azuresqlmanagedinstance/golden_metrics.yml
definitions/infra-azurestorageaccount/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/golden_metrics.yml

Reverts newrelic-experimental/entity-synthesis-definitions#215 - this is incompatible with the GMH

Revert "Use correct provider for Azure"

---

definitions/infra-gcpappengineservice/golden_metrics.yml
definitions/infra-gcpbigquerydataset/golden_metrics.yml
definitions/infra-gcpbigquerydataset/summary_metrics.yml
definitions/infra-gcpbigquerytable/golden_metrics.yml
definitions/infra-gcpbigquerytable/summary_metrics.yml
definitions/infra-gcpbigtablecluster/golden_metrics.yml
definitions/infra-gcpbigtabletable/golden_metrics.yml
definitions/infra-gcpcloudcomposerenvironment/golden_metrics.yml
definitions/infra-gcpcloudcomposerworkflow/golden_metrics.yml
definitions/infra-gcpcloudfunction/golden_metrics.yml
definitions/infra-gcpcloudsql/golden_metrics.yml
definitions/infra-gcphttploadbalancer/golden_metrics.yml
definitions/infra-gcpinternalloadbalancer/golden_metrics.yml
definitions/infra-gcpmemcachememcachenode/golden_metrics.yml
definitions/infra-gcpredisinstance/golden_metrics.yml
definitions/infra-gcpspannerdatabase/golden_metrics.yml
definitions/infra-gcpspannerinstance/golden_metrics.yml
definitions/infra-gcpstoragebucket/golden_metrics.yml

Reverts newrelic-experimental/entity-synthesis-definitions#216 - - this is incompatible with the GMH

Revert "Fix gcp golden metrics"

---

definitions/infra-apacheserver/golden_metrics.yml
definitions/infra-cassandranode/golden_metrics.yml
definitions/infra-elasticsearchnode/golden_metrics.yml
definitions/infra-f5pool/golden_metrics.yml
definitions/infra-f5poolmember/golden_metrics.yml
definitions/infra-f5virtualserver/golden_metrics.yml
definitions/infra-host/golden_metrics.yml
definitions/infra-kafkabroker/golden_metrics.yml
definitions/infra-kubernetes_daemonset/golden_metrics.yml
definitions/infra-kubernetes_deployment/golden_metrics.yml
definitions/infra-kubernetes_pod/golden_metrics.yml
definitions/infra-kubernetes_statefulset/golden_metrics.yml
definitions/infra-mssqlinstance/golden_metrics.yml
definitions/infra-mysqlnode/golden_metrics.yml
definitions/infra-nginxserver/golden_metrics.yml
definitions/infra-oracledbinstance/golden_metrics.yml
definitions/infra-postgresqlinstance/golden_metrics.yml
definitions/infra-rabbitmqexchange/golden_metrics.yml
definitions/infra-rabbitmqnode/golden_metrics.yml
definitions/infra-rabbitmqqueue/golden_metrics.yml
definitions/infra-redisinstance/golden_metrics.yml
definitions/infra-vspherecluster/golden_metrics.yml
definitions/infra-vspheredatacenter/golden_metrics.yml
definitions/infra-vspheredatastore/golden_metrics.yml
definitions/infra-vspherehost/golden_metrics.yml
definitions/infra-vsphereresourcepool/golden_metrics.yml
definitions/infra-vspherevm/golden_metrics.yml

Reverts newrelic-experimental/entity-synthesis-definitions#218 - this is incompatible with the GMH

Revert "Jlegoff/fix onhost golden metrics"

---

definitions/infra-azureapimanagementservice/golden_metrics.yml
definitions/infra-azureapplicationgateway/golden_metrics.yml
definitions/infra-azureappservicewebapp/golden_metrics.yml
definitions/infra-azurecontainersinstancegroup/golden_metrics.yml
definitions/infra-azurecontainersmanagedcluster/golden_metrics.yml
definitions/infra-azurecontainersregistry/golden_metrics.yml
definitions/infra-azurecosmosdbaccount/golden_metrics.yml
definitions/infra-azurecosmosdbcollection/golden_metrics.yml
definitions/infra-azurecosmosdbdatabase/golden_metrics.yml
definitions/infra-azuredatafactorydatafactory/golden_metrics.yml
definitions/infra-azureeventhubcluster/golden_metrics.yml
definitions/infra-azureeventhubnamespace/golden_metrics.yml
definitions/infra-azurefirewall/golden_metrics.yml
definitions/infra-azurefrontdoorfrontdoor/golden_metrics.yml
definitions/infra-azurefunctionsapp/golden_metrics.yml
definitions/infra-azurekeyvaultvault/golden_metrics.yml
definitions/infra-azureloadbalancer/golden_metrics.yml
definitions/infra-azurelogicappsintegrationserviceenvironment/golden_metrics.yml
definitions/infra-azurelogicappsworkflow/golden_metrics.yml
definitions/infra-azuremariadbserver/golden_metrics.yml
definitions/infra-azuremysqlserver/golden_metrics.yml
definitions/infra-azurepostgresqlserver/golden_metrics.yml
definitions/infra-azurepowerbidedicatedcapacity/golden_metrics.yml
definitions/infra-azureservicebusnamespace/golden_metrics.yml
definitions/infra-azuresqldatabase/golden_metrics.yml
definitions/infra-azuresqlmanagedinstance/golden_metrics.yml
definitions/infra-azurestorageaccount/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/golden_metrics.yml

Reverts newrelic-experimental/entity-synthesis-definitions#214 - this is incompatible with GMH

Revert "Jlegoff/fix azure golden metrics"

---

definitions/ext-host/definition.yml

Added OpenTelemetry host metrics for host entity generation.

Add synthesis definition for opentelemetry-collector host metrics.

---

definitions/ext-ibmmqmanager/definition.yml
definitions/ext-ibmmqmanager/golden_metrics.yml
definitions/ext-ibmmqqueue/definition.yml
definitions/ext-ibmmqqueue/golden_metrics.yml
definitions/ext-ibmmqqueue/summary_metrics.yml

Entity synthesis definitions for IBM MQ Queue Managers and Queues. Based upon data emitted from this integration:
https://github.com/newrelic-experimental/newrelic-ibm-mq-monitor

ibm mq entities

---

definitions/infra-apacheserver/golden_metrics.yml
definitions/infra-cassandranode/golden_metrics.yml
definitions/infra-elasticsearchnode/golden_metrics.yml
definitions/infra-f5pool/golden_metrics.yml
definitions/infra-f5poolmember/golden_metrics.yml
definitions/infra-f5virtualserver/golden_metrics.yml
definitions/infra-host/golden_metrics.yml
definitions/infra-kafkabroker/golden_metrics.yml
definitions/infra-kubernetes_daemonset/golden_metrics.yml
definitions/infra-kubernetes_deployment/golden_metrics.yml
definitions/infra-kubernetes_pod/golden_metrics.yml
definitions/infra-kubernetes_statefulset/golden_metrics.yml
definitions/infra-mssqlinstance/golden_metrics.yml
definitions/infra-mysqlnode/golden_metrics.yml
definitions/infra-nginxserver/golden_metrics.yml
definitions/infra-oracledbinstance/golden_metrics.yml
definitions/infra-postgresqlinstance/golden_metrics.yml
definitions/infra-rabbitmqexchange/golden_metrics.yml
definitions/infra-rabbitmqnode/golden_metrics.yml
definitions/infra-rabbitmqqueue/golden_metrics.yml
definitions/infra-redisinstance/golden_metrics.yml
definitions/infra-vspherecluster/golden_metrics.yml
definitions/infra-vspheredatacenter/golden_metrics.yml
definitions/infra-vspheredatastore/golden_metrics.yml
definitions/infra-vspherehost/golden_metrics.yml
definitions/infra-vsphereresourcepool/golden_metrics.yml
definitions/infra-vspherevm/golden_metrics.yml

Add back the changes from [this PR ](https://github.com/newrelic-experimental/entity-synthesis-definitions/pull/238)

Fix onhost golden metrics (#238)

---

definitions/ext-service/definition.yml

Add golden tags for Pixie service entities.

Add golden tags for Pixie service entities.

---

README.md

Add in the readme a changelog part

Add the changelog in the readme

---

README.md

Updated the header and the links in the readme

Change the header and the links to the new repo

---

README.md

Change the header to use community plus instead of community. 

Change the header to community plus

---

definitions/ext-wireless_controller/definition.yml
definitions/ext-wireless_controller/golden_metrics.yml
definitions/ext-wireless_controller/meraki-dashboard.json
definitions/ext-wireless_controller/summary_metrics.yml

adding ext-wireless_controller entity from Kentik SNMP integration

feat: adding ext-wireless_controller entity

---

definitions/ext-wireless_controller/meraki-dashboard.json

repairing some NRQL on dashboard to align with latest release from Kentik 

fix: repairing some nrql queries

---

definitions/infra-powerdns_recursor/dashboard.json
definitions/infra-powerdns_recursor/definition.yml

I followed the README creating a dashboard exporting an existing one and running as well `docker-compose run sanitize-dashboards`
I updated the entity with the dashboard definition.

feat(powerDNSRecursor): dashboards

---

definitions/infra-win_service/summary_metrics.yml

Change the names of the keys for the summary metrics to the current updated ones.

Update the keys for WIN_SERVICE summary metrics

---

definitions/ext-endpoint/definition.yml

These represent a network endpoint (e.g. the IP:port tuple).  These will be extracted from network telemetry.

Add EXT-ENDPOINT

---

definitions/infra-powerdns_authoritative/dashboard.json
definitions/infra-powerdns_authoritative/definition.yml
definitions/infra-powerdns_recursor/dashboard.json

Added new version for powerDNS dashboards recursive and added new dashboard for authoritative server @mangulonr 
Fix https://github.com/newrelic/newrelic-coreint/issues/128

feat(dashboards): updated Dashboards for powerdns

---

definitions/mlops-machine_learning_model/definition.yml

I've created the basic definition of a new entity type for ml models under the new domain MLOps. As a next step we'll add synthesis ruled and metrics to this entity.
* [ V] I've read the guidelines and understand the acceptance criteria.
* [ V] The value of the attribute marked as `identifier` will be unique and valid. 
* [ V] I've confirmed that my entity type wasn't already defined. If it is I'm providing an

add basic definition for machine learning model entity type

---

README.md

README review by Tech Docs

---

definitions/ext-host/golden_metrics.yml

With the new validation process, those queries require adjustments to get validated.

Refactoring invalid queries

---

definitions/infra-win_service/summary_metrics.yml

Change WIN_SERVICE summary metrics to query format

Change WIN_SERVICE summary metrics to query format

---

definitions/ext-aws_region/definition.yml

add aws region poc entity type

---

definitions/ext-aws_region/definition.yml

set aws region to be alertable

---

.github/CODEOWNERS

Add Daniel to codeowners

---

definitions/ext-db2/dashboard.json
definitions/ext-ibmmqmanager/dashboard.json
definitions/ext-ibmmqmanager/definition.yml
definitions/ext-ibmmqqueue/dashboard.json
definitions/ext-ibmmqqueue/definition.yml
definitions/ext-nas/readynas-dashboard.json
definitions/ext-ups/dashboard.json

Added Dashboard templates for entity types:
- ext-ibmmqmanager
- ext-ibmmqqueue

Dashboards for MQ Entities

---

validator/schemas/dashboard-schema-v1.json

Allow to configure a text widget in a dashboard.

Allow text widget in the dashboard

---

definitions/ext-istio_service/dashboard.json
definitions/ext-istio_service/definition.yml
definitions/ext-istio_service/golden_metrics.yml
definitions/ext-istio_service/summary_metrics.yml
definitions/infra-awsvpcnetworkinterface/summary_metrics.yml

Adding definition, golden metrics, summary metrics, and summary dashboard for an **Istio Service** entity
cc: @thezackm

adding Istio Service Entity

---

definitions/ext-fastly_pop/definition.yml
definitions/ext-fastly_pop/golden_metrics.yml
definitions/ext-fastly_pop/summary_metrics.yml

Moved golden metrics from Metric to Logs to remove dependency on Events-to-Metrics rules.

Refreshing Fastly POP definitions

---

definitions/ext-fastly_pop/dashboard.json
definitions/ext-fastly_pop/definition.yml
definitions/ext-fastly_pop/fastly-pop_dashboard.json

Added a dashboard template and updated the definition.yaml file

Updating ext-fastly_pop with default entity dashboard

---

docs/golden_metrics.md
docs/summary_metrics.md

Adds documentation regarding instrumentalized query names for working with both, provider and name values.

Adding documentation regarding instrumentalized query names.

---

definitions/ext-pihole/dashboard.json
definitions/ext-pihole/definition.yml
definitions/ext-pihole/golden_metrics.yml
definitions/ext-pihole/summary_metrics.yml

Reverts newrelic/entity-definitions#324

Revert "Delete EXT-PIHOLE (to re-create it later)"

---

definitions/ext-fastly_pop/fastly-pop_dashboard.json

A few testing charts snuck their way into the template. Dropped them and cleaned up the overall layout.
A few testing charts snuck their way into the template. Dropped them and cleaned up the overall layout.

Cleaned up layout and dropped some charts

---

validator/tools/utils.js

Restrict where these apply to right after } ] or ), so that they
just apply to fix json syntax.

Fix validator to handle trailing commas

---

definitions/ext-gatsby_build/dashboard.json

Just making changes to charts in the current Dashboard

chore: update dashboard

---

definitions/ext-gatsby_build/dashboard.json

Reverts newrelic/entity-definitions#333

Revert "chore: update dashboard"

---

definitions/infra-host/golden_metrics.yml

This is another attempt to fix the network GMs for OTEL hosts. Do not merge it until this is tested.

fix network golden metrics for otel hosts

---

definitions/infra-host/golden_metrics.yml

Reverts newrelic/entity-definitions#373

Revert "fix network golden metrics for otel hosts"

---

validator/schemas/entity-schema-v1.json

Allow digits in file names

---

docs/README.md

Add a quick reference section to show the files that can be used to define the new entity type. 

Add quick reference section

---

definitions/infra-awss3bucket/golden_metrics.yml
definitions/infra-awssnstopic/golden_metrics.yml
definitions/infra-awssqsqueue/golden_metrics.yml
definitions/infra-azureappservicewebapp/golden_metrics.yml
definitions/infra-azurecontainersinstancegroup/golden_metrics.yml
definitions/infra-azurecontainersmanagedcluster/golden_metrics.yml
definitions/infra-azurecontainersregistry/golden_metrics.yml
definitions/infra-azurecosmosdbaccount/golden_metrics.yml
definitions/infra-azurecosmosdbcollection/golden_metrics.yml
definitions/infra-azurecosmosdbdatabase/golden_metrics.yml
definitions/infra-azuredatafactorydatafactory/golden_metrics.yml
definitions/infra-azureeventhubcluster/golden_metrics.yml
definitions/infra-azureeventhubnamespace/golden_metrics.yml
definitions/infra-azurefirewall/golden_metrics.yml
definitions/infra-azurefunctionsapp/golden_metrics.yml
definitions/infra-azureloadbalancer/golden_metrics.yml
definitions/infra-azurelogicappsintegrationserviceenvironment/golden_metrics.yml
definitions/infra-azurelogicappsworkflow/golden_metrics.yml
definitions/infra-azuremariadbserver/golden_metrics.yml
definitions/infra-azuremysqlserver/golden_metrics.yml

I'm updating Golden Metrics entity definitions to add Unit:
Here's the workbook I'm using as reference: https://docs.google.com/spreadsheets/d/1aArct8W9LxVbkhvh1BYRHLDjW_OG2GXW6xJ5xn2mpRQ/edit#gid=0

golden-metrics-units-3

---

definitions/infra-azurepostgresqlserver/golden_metrics.yml
definitions/infra-azureservicebusnamespace/golden_metrics.yml
definitions/infra-azuresqldatabase/golden_metrics.yml
definitions/infra-azuresqlmanagedinstance/golden_metrics.yml
definitions/infra-azurevirtualmachinescaleset/golden_metrics.yml
definitions/infra-cassandranode/golden_metrics.yml
definitions/infra-container/golden_metrics.yml
definitions/infra-elasticsearchnode/golden_metrics.yml
definitions/infra-etcd_cluster/golden_metrics.yml
definitions/infra-f5pool/golden_metrics.yml
definitions/infra-f5poolmember/golden_metrics.yml
definitions/infra-f5virtualserver/golden_metrics.yml
definitions/infra-gcpappengineservice/golden_metrics.yml
definitions/infra-gcpbigquerydataset/golden_metrics.yml
definitions/infra-gcpbigquerytable/golden_metrics.yml
definitions/infra-gcpbigtablecluster/golden_metrics.yml
definitions/infra-gcpcloudfunction/golden_metrics.yml
definitions/infra-gcpcloudsql/golden_metrics.yml
definitions/infra-gcphttploadbalancer/golden_metrics.yml
definitions/infra-gcpinternalloadbalancer/golden_metrics.yml

I'm updating Golden Metrics entity definitions to add Unit:
Here's the workbook I'm using as reference: https://docs.google.com/spreadsheets/d/1aArct8W9LxVbkhvh1BYRHLDjW_OG2GXW6xJ5xn2mpRQ/edit#gid=0

golden-metrics-units-4

---

definitions/infra-awsapigatewayapi/golden_metrics.yml
definitions/infra-awsapigatewayresourcewithmetrics/golden_metrics.yml
definitions/infra-awsapigatewaystage/golden_metrics.yml
definitions/infra-awsdynamodbtable/golden_metrics.yml
definitions/infra-awsebsvolume/golden_metrics.yml
definitions/infra-awselasticsearchcluster/golden_metrics.yml
definitions/infra-awselasticsearchnode/golden_metrics.yml
definitions/infra-awsmediapackagevodpackagingconfiguration/golden_metrics.yml
definitions/infra-awsrdsdbinstance/golden_metrics.yml
definitions/infra-awsstatesstatemachine/golden_metrics.yml
definitions/infra-azureapimanagementservice/golden_metrics.yml
definitions/infra-azureapplicationgateway/golden_metrics.yml
definitions/infra-azurefrontdoorfrontdoor/golden_metrics.yml
definitions/infra-redisinstance/golden_metrics.yml
definitions/infra-vspherecluster/golden_metrics.yml
definitions/infra-vspheredatacenter/golden_metrics.yml
definitions/infra-vspheredatastore/golden_metrics.yml
definitions/infra-vspherehost/golden_metrics.yml
definitions/infra-vsphereresourcepool/golden_metrics.yml
definitions/infra-vspherevm/golden_metrics.yml

I'm updating Golden Metrics entity definitions to add Unit:
Here's the workbook I'm using as reference: https://docs.google.com/spreadsheets/d/1aArct8W9LxVbkhvh1BYRHLDjW_OG2GXW6xJ5xn2mpRQ/edit#gid=0

golden-metrics-units-6

---

definitions/ext-factorio_game/dashboard.json
definitions/ext-factorio_game/definition.yml

[Factorio](https://www.factorio.com/) is a construction and management simulation game developed by the Czech studio Wube Software. It is, at the time of writing, in the top 5 best Steam games of all time according to gamer reviews.
One of the key features of the game is that it provides the player with some really interesting statistics. For example:
* The player can check any electric networks stats by clicking on a power pole.
* Production statistics for items, fluids and buildings will show how many items are being produced and consumed.
* Kill statistics show the player how many enemies, trees, ... have been killed and how many losses they've incurred.
This entity type attempts to bring those statistics into New Relic.

EXT-FACTORIO_GAME Add definition and dashboard for new entity type

---

definitions/ext-host/definition.yml

Add several tags for host synthesis.

feat: host synthesis add tags

---

definitions/ext-flow_device/kentik-netflow-events-dashboard.json
definitions/ext-vpc_network/kentik-aws-vpc-dashboard.json

Update dashboards to display src and dst hostnames when DNS is enabled

Update flow dashboard hostnames

---

definitions/ext-key_transaction/definition.yml

Add the KEY_TRANSACTION entity type.

Add Key Transaction entity type

---

definitions/ext-sap_system/dashboard.json
definitions/ext-sap_system/definition.yml
definitions/ext-sap_system/golden_metrics.yml
definitions/ext-sap_system/summary_metrics.yml
definitions/infra-host/golden_metrics.yml

* [ x] I've read the guidelines and understand the acceptance criteria.

Add new entity type ext-sap_system

---

definitions/ext-sap_transaction/dashboard.json
definitions/ext-sap_transaction/definition.yml
definitions/ext-sap_transaction/golden_metrics.yml
definitions/ext-sap_transaction/summary_metrics.yml

Add definition files for new entity type ext-sap_transaction. This type includes SAP 

Add definition files for new entity type ext-sap_transaction

---

definitions/ext-maxdb/dashboard.json
definitions/ext-maxdb/definition.yml
definitions/ext-maxdb/golden_metrics.yml
definitions/ext-maxdb/summary_metrics.yml

Add definition files for new entity type ext-maxdb. Maxdb is a type of database SAP uses.

Add definitions files for new entity type ext-maxdb.

---

definitions/infra-cassandranode/golden_metrics.yml
definitions/infra-vspheredatastore/golden_metrics.yml
definitions/infra-vspherehost/golden_metrics.yml
definitions/infra-vsphereresourcepool/golden_metrics.yml
definitions/infra-vspherevm/golden_metrics.yml

Following this internal discussion, some of the golden metrics are broken and needed to be fixed.

Modify Cassandra and Vsphere golden metrics for Pegasus launch

---

definitions/ext-sap_idoc/dashboard.json
definitions/ext-sap_idoc/definition.yml
definitions/ext-sap_idoc/golden_metrics.yml
definitions/ext-sap_idoc/summary_metrics.yml

1. add a sap.system tag
2. Change dashboard design
3. Change golden metrics and summary metrics to get error from NR_SAP_IDOC event table
The ext-sap_idoc entity type was created as the first SAP entity defined last week. It requires some modification now we understand the entity platform a little better. Our team owns the ext-sap_idoc entity type.
Update the definition files for entity type ext-sap_idoc. Add the sap.system tag to be consistent with other sap entities. The dash board have been rewritten to fit display data for one entity(one type of idoc processor).
* [x ] I've confirmed that my entity type wasn't already defined. If …

Update ext-sap_idoc definition:

---

definitions/ext-service_level/definition.yml
definitions/nr1-service_level/definition.yml

Added SERVICE_LEVEL entity to manage service levels in NR as entities.
* [ x] I've read the guidelines and understand the acceptance criteria.

Add SERVICE_LEVEL entity

---

definitions/ext-firewall/cisco-firepower-dashboard.json
definitions/ext-firewall/definition.yml
definitions/ext-firewall/golden_metrics.yml
definitions/ext-firewall/summary_metrics.yml

Adding Cisco FirePower devices to the existing `EXT-FIREWALL` entity type.

feat: add cisco firepower to ext-firewall

---

definitions/ext-firewall/cisco-firepower-dashboard.json
definitions/ext-web_gateway/fireeye-dashboard.json

removing unnecessary filter from NRQL

fix: removing unnecessary filters from nrql

---

README.md
definitions/ext-pihole/tests/CustomSample.json
definitions/ext-pihole/tests/Log.json

* Add synthesis testing data for pihole entity
* Document how to add testing data to definitions

Add testing data for pihole + document how to add testing data

---

definitions/infra-host/definition.yml

These conditions prevent the entities from being created. We'll remove
them while this is being investigated.

Remove conditions the otel host

---

definitions/ext-vpc_network/aws-kinesis-firehose-vpc-flow-logs-dashboard.json

Just a quick fix to adjust the title of a dashboard widget

chore: adjust widget title

---

definitions/infra-azureapimanagementservice/definition.yml
definitions/infra-azureapplicationgateway/definition.yml
definitions/infra-azurecontainersinstancegroup/definition.yml
definitions/infra-azurecontainersmanagedcluster/definition.yml
definitions/infra-azurecontainersregistry/definition.yml

Adding some synthesis rules for 3 Azure resourceTypes

Add some Azure entity synthesis rules

---

definitions/ext-environment_sensor/definition.yml
definitions/ext-environment_sensor/summary_metrics.yml
definitions/ext-environment_sensor/sunbird-poweriq-dashboard.json

Adding new vendor telemetry to the existing `EXT-Environment_Sensor` definition.

feat: adding sunbird poweriq device to env sensor

---

definitions/synth-private_location/definition.yml
definitions/synth-secure_cred/definition.yml

Make synthetics private locations and secure credentials entity types alertable.

Turn synthetics private locations and secure credentials alertable

---

definitions/infra-host/golden_metrics.yml

This is another test for OTEL host entities, this time to compute CPU and Filesystem utilization. As usual, let's deploy this in staging before merging.

Add missing GMs for otel hosts

---

definitions/infra-host/golden_metrics.yml

The previous PR had a mistake - fixing it in this one

Fix CPU metric for OTEL hosts

---

definitions/aiops-condition/definition.yml

Added the aiops-condition definition to support Conditions as Entities project

feat: add aiops-condition definition

---

definitions/ext-firewall/palo-alto-dashboard.json

updating a widget design and some NRQL for interface metrics 

chore: minor updates to existing palo alto firewall dashboard

---

definitions/ext-network_synth/network-synth-dashboard.json

New dashboard, Demotron mock available here https://onenr.io/08woXa76qRx

chore: network-synth dashboard

---

definitions/ext-network_synth/network-synth-dashboard.json

fix:typo in dashboard

---

definitions/ext-media_gateway/avaya-dashboard.json
definitions/ext-media_gateway/definition.yml
definitions/ext-media_gateway/golden_metrics.yml
definitions/ext-media_gateway/summary_metrics.yml

adding new entity type for `EXT-MEDIA_GATEWAY`; initial telemetry is from various Avaya G-series media gateways

feat: adding media gateway entity for avaya

---

definitions/ext-service/tests/Log.json
definitions/infra-host/definition.yml
definitions/infra-host/tests/MetricRaw.json

Revert las release becase need to be tested before release

hotfix revert release 2.69.0

---

definitions/ext-email_gateway/barracuda-email-gateway-dashboard.json
definitions/ext-email_gateway/definition.yml
definitions/ext-email_gateway/golden_metrics.yml
definitions/ext-email_gateway/summary_metrics.yml

adding new entity type for Email Gateways

feat: adding email gateway definition

---

docs/synthesis.md

Improves the synthesis documentation, documenting different ways of copying tags on an entity.

Improves synthesis doc.

---

definitions/ext-packet_broker/anue-packet-broker-dashboard.json
definitions/ext-packet_broker/definition.yml
definitions/ext-packet_broker/summary_metrics.yml

Adding new entity type for Anue Packet Broker devices

feat: adding packet broker entity type

---

definitions/ext-pihole/definition.yml

Testing some stuff - Ignore

---

definitions/ext-pihole/definition.yml

Rollback prefix changes

---

definitions/ext-ilo/definition.yml
definitions/ext-ilo/golden_metrics.yml
definitions/ext-ilo/hp-ilo-dashboard.json
definitions/ext-ilo/summary_metrics.yml

Adding entity definition for [HP Integrated Lights Out](https://www.hpe.com/us/en/servers/integrated-lights-out-ilo.html) (ILO) devices

feat: adding ext-ilo entity definition

---

definitions/test-andre/definition.yml

Just adding a practice entity for onboarding purposes.

feat: Adding a practice entity

---

definitions/ext-access_point/definition.yml
definitions/ext-access_point/tests/MetricRaw.json

Add a new definition for access_point entity

Add a access point definition

---

definitions/ext-pihole/definition.yml

Change ext pihole to debug

---

definitions/ext-pihole/definition.yml

Reverts newrelic/entity-definitions#543

Revert "Change ext pihole to debug"

---

definitions/infra-ibmmq_manager/dashboard.json
definitions/infra-ibmmq_queue/definition.yml
definitions/infra-ibmmq_queue/golden_metrics.yml

Fix queue golden tags and queue manager dashboard

fix queue tags and manager dashboard

---

definitions/ext-access_point/cisco-access-point-dashboard.json
definitions/ext-access_point/definition.yml
definitions/ext-access_point/golden_metrics.yml
definitions/ext-access_point/summary_metrics.yml

adding Cisco access points to existing `EXT-ACCESS_POINT` definition

chore: add cisco to existing access point def

---

definitions/ext-factorio_game/golden_metrics.yml
definitions/ext-factorio_game/summary_metrics.yml

Add golden and summary metrics to FACTORIO_GAME entity type

---

definitions/test-andre/definition.yml

Reverts newrelic/entity-definitions#527 - the entity for practicing

Revert "feat: Adding a practice entity"

---

definitions/ext-firewall/checkpoint-dashboard.json
definitions/ext-firewall/definition.yml
definitions/ext-firewall/golden_metrics.yml
definitions/ext-firewall/summary_metrics.yml

Added a new checkpoint dashboard to the ext-firewall entity.  Updated definition, summary, golden-metrics for the new vendor.

Checkpoint firewall updates

---

definitions/ext-firewall/definition.yml
definitions/ext-firewall/golden_metrics.yml
definitions/ext-firewall/sonicwall-sma-dashboard.json
definitions/ext-firewall/summary_metrics.yml

adding new vendor telemetry to existing `EXT-FIREWALL` definition

chore: add dell sonicwall to ext-firewall definition

---

definitions/ext-argocd/dashboard.json
definitions/ext-argocd/definition.yml
definitions/ext-argocd/golden_metrics.yml
definitions/ext-argocd/summary_metrics.yml

Added a new Entity Definition for ArgoCD.  Previously created ArgoCD Quickstart, created Entity Definition to match.

Add ArgoCD Entity Definition

---

definitions/infra-apacheserver/summary_metrics.yml
definitions/infra-awsapigatewayapi/summary_metrics.yml
definitions/infra-awsapigatewayresourcewithmetrics/summary_metrics.yml
definitions/infra-awsapigatewaystage/summary_metrics.yml
definitions/infra-awscloudfrontdistribution/summary_metrics.yml
definitions/infra-awsecsservice/summary_metrics.yml
definitions/infra-awskinesisstream/summary_metrics.yml
definitions/infra-awskinesisstreamshard/summary_metrics.yml
definitions/infra-awsnlbtargetgroup/summary_metrics.yml
definitions/infra-awsredshiftnode/summary_metrics.yml
definitions/infra-awssnstopic/summary_metrics.yml
definitions/infra-awssqsqueue/summary_metrics.yml
definitions/infra-azureappservicewebapp/summary_metrics.yml
definitions/infra-azurecosmosdbaccount/summary_metrics.yml
definitions/infra-azurefunctionsapp/summary_metrics.yml
definitions/infra-azuresqldatabase/summary_metrics.yml
definitions/infra-azurestorageaccount/summary_metrics.yml
definitions/infra-gcpappengineservice/summary_metrics.yml
definitions/infra-gcpcloudfunction/summary_metrics.yml
definitions/infra-gcpcloudsql/summary_metrics.yml
definitions/infra-gcpinternalloadbalancer/summary_metrics.yml
definitions/infra-gcpspannerinstance/summary_metrics.yml
definitions/infra-gcpstoragebucket/summary_metrics.yml
definitions/infra-rabbitmqnode/summary_metrics.yml
definitions/infra-redisinstance/summary_metrics.yml
definitions/infra-vspheredatacenter/summary_metrics.yml

This is part of the epic to make all the summary metrics to be a subset of golden metrics.

ESA-1239 make SM names a subset of GM names

---

definitions/infra-awss3bucket/dashboard.json

Fix some indexes to display the dashboard correctly.
We need to +1 all the rows&cols

INFRA-S3Buckets: fix indexes of the dashboard

---

definitions/ext-firewall/definition.yml
definitions/ext-firewall/golden_metrics.yml
definitions/ext-firewall/sophos-xgs-dashboard.json
definitions/ext-firewall/summary_metrics.yml

Adding new vendor for existing `EXT-FIREWALL` entity definition

chore: add sophos vendor to ext-firewall

---

definitions/ext-environment_sensor/golden_metrics.yml
definitions/ext-packet_broker/golden_metrics.yml
definitions/ext-printer/golden_metrics.yml
definitions/infra-awsiotbroker/golden_metrics.yml
definitions/infra-awsiotrule/golden_metrics.yml
definitions/infra-awsiotruleaction/golden_metrics.yml
definitions/infra-awsroute53healthcheck/golden_metrics.yml
definitions/infra-awssesregion/golden_metrics.yml
definitions/infra-awsvpcnetworkinterface/golden_metrics.yml
definitions/infra-azureappserviceplan/golden_metrics.yml
definitions/infra-azurerediscache/golden_metrics.yml
definitions/infra-azurerediscacheshard/golden_metrics.yml
definitions/infra-azuresqlelasticpool/golden_metrics.yml
definitions/infra-azuresqlserver/golden_metrics.yml
definitions/infra-consulagent/golden_metrics.yml
definitions/infra-couchbasebucket/golden_metrics.yml
definitions/infra-couchbasecluster/golden_metrics.yml
definitions/infra-f5system/golden_metrics.yml
definitions/infra-gcpbigqueryproject/golden_metrics.yml
definitions/infra-gcpkubernetescontainer/golden_metrics.yml
definitions/infra-gcpkubernetesnode/golden_metrics.yml
definitions/infra-gcppubsubsubscription/golden_metrics.yml
definitions/infra-gcppubsubtopic/golden_metrics.yml
definitions/infra-varnishinstance/golden_metrics.yml

This PR is part of the effort to make all the Summary Metrics a subset of the Golden Metrics. In this case, I'm tackling all the types that have Summary Metrics but do not have Golden Metrics. What I did is just copy the Summary Metrics and remove the ones that are TAGS.

ESA-1300 copy SM to GM when GM is not present

---

definitions/ext-factorio_game/golden_metrics.yml

The goal of this PR is to make SM a subset of GM.

NR-17236 make SM subset of GM for ext-factorio_game

---

definitions/ext-cisco_ucs/golden_metrics.yml
definitions/ext-idrac/golden_metrics.yml
definitions/ext-ilo/golden_metrics.yml
definitions/ext-istio_service/golden_metrics.yml
definitions/ext-mobility_controller/golden_metrics.yml
definitions/ext-redis/golden_metrics.yml
definitions/ext-unix_host/golden_metrics.yml
definitions/infra-awsalb/golden_metrics.yml
definitions/infra-awsecscluster/golden_metrics.yml
definitions/infra-awsecscluster/summary_metrics.yml
definitions/infra-awselb/golden_metrics.yml
definitions/infra-awselb/summary_metrics.yml
definitions/infra-awsnlb/golden_metrics.yml
definitions/infra-azureservicebusnamespace/summary_metrics.yml
definitions/infra-etcd_cluster/golden_metrics.yml
definitions/infra-nginxserver/golden_metrics.yml
definitions/infra-vspherecluster/golden_metrics.yml
definitions/infra-vspherevm/golden_metrics.yml
definitions/infra-vspherevm/summary_metrics.yml

Relevant information
This is a first iteration to reduce the number of definitions were the SM are not a subset of GM.

NR-17236 convert SM to subset of GM

---

definitions/infra-awsautoscalinggroup/golden_metrics.yml
definitions/infra-awsautoscalinggroup/summary_metrics.yml

Make the SM of awsautoscaling type a subset of its GM.

NR-17236 make awsautoscaling SM a subset of GM

---

definitions/infra-awselasticsearchnode/golden_metrics.yml
definitions/infra-awselasticsearchnode/summary_metrics.yml

This PR tries to make SM a subset of the GM for awselasticsearchnode. IT change the golden metric to be consistent with the entity-type

NR-17236 Make SM a subset of GM for awselasticsearchnode

---

definitions/infra-awsalb/golden_metrics.yml

the requests metrics should not be a rate.

Nojira fix awsalb metrics

---

definitions/infra-awsalb/summary_metrics.yml

This PR adds a pointer to a GM for the SM of awsalb

NR-17236 Add GM pointer to awsalb

---

definitions/infra-awsecsservice/golden_metrics.yml

Fix golden metric for ecs service

---

definitions/mlops-machine_learning_endpoint/golden_metrics.yml

NR-17236_fix SM GM mlops-machine-learning-endpoint

NR-17236_fix_SM_GM_mlops-endpoint

---

definitions/infra-azurerediscacheshard/golden_metrics.yml

This PR is tries to fix the GM for azure redis shard

add entity name to the GM for azure redis shard

---

definitions/infra-cassandranode/golden_metrics.yml
definitions/infra-oracledbinstance/golden_metrics.yml
definitions/infra-oracledbinstance/summary_metrics.yml

Same as other PR of SummaryMetric be a subset of GoldenMetric: infra oracle and cassandra

NR-17236 fix SM GM infra oracle cassandra

---

definitions/infra-awselasticacherediscluster/golden_metrics.yml
definitions/infra-awselasticacherediscluster/summary_metrics.yml
definitions/infra-awselasticsearchcluster/golden_metrics.yml
definitions/infra-awselasticsearchcluster/summary_metrics.yml
definitions/infra-awsredshiftcluster/golden_metrics.yml
definitions/infra-awsredshiftcluster/summary_metrics.yml

Make Summary metrics a subset of Golden metrics for AWS Elasticache Redis, Elastic Search and Redshift.

Fix summary metrics cloud

---

definitions/infra-elasticsearchnode/golden_metrics.yml
definitions/infra-elasticsearchnode/summary_metrics.yml

The goal of this PR is to make SM a subset of the GM for elasticsearchnode.

NR-17236 make SM subset of GM for elasticsearchnode

---

definitions/infra-awsebsvolume/golden_metrics.yml
definitions/infra-awsebsvolume/summary_metrics.yml

NR-17236 make SM subset of GM for awsebsvolumne

---

definitions/ext-aix_oracle/summary_metrics.yml
definitions/ext-cloudflare_host/summary_metrics.yml
definitions/ext-istio_service/summary_metrics.yml
definitions/infra-awsapigatewayapi/summary_metrics.yml
definitions/infra-awsapigatewayresourcewithmetrics/summary_metrics.yml
definitions/infra-awsapigatewaystage/summary_metrics.yml
definitions/infra-awselasticacherediscluster/summary_metrics.yml
definitions/infra-awselasticsearchcluster/summary_metrics.yml
definitions/infra-awsredshiftcluster/summary_metrics.yml
definitions/infra-awsvpcnetworkinterface/summary_metrics.yml
definitions/infra-cassandranode/summary_metrics.yml
definitions/infra-gcpbigquerytable/summary_metrics.yml
definitions/infra-gcpkubernetescontainer/summary_metrics.yml
definitions/infra-kubernetes_pod/summary_metrics.yml
definitions/infra-mssqlinstance/summary_metrics.yml
definitions/infra-oracledbinstance/summary_metrics.yml
definitions/infra-vsphereresourcepool/summary_metrics.yml
definitions/mlops-machine_learning_endpoint/summary_metrics.yml

all those definitions needs to have a golden metric pointer so they can be fetched from the GM backend.

Create Golden Metric Pointers

---

definitions/infra-host/golden_metrics.yml
definitions/infra-host/summary_metrics.yml

Reverts newrelic/entity-definitions#664

Revert "Use GM in infra-host SM"

---

definitions/infra-container/summary_metrics.yml

Use Golden Metric pointer for some summary metrics.

NR-17234 user gm in infra container SM

---

definitions/infra-azurevirtualnetworkspublicipaddress/golden_metrics.yml
definitions/infra-azurevirtualnetworkspublicipaddress/summary_metrics.yml

fix GM SM of infra-azurevirtualnetwork enum from private repo to public one

fix-gm-sm-enum-azurevirtualnetwork

---

definitions/infra-azurevirtualnetworkspublicipaddress/summary_metrics.yml
definitions/infra-couchbasenode/summary_metrics.yml
definitions/infra-f5node/summary_metrics.yml
definitions/infra-f5pool/summary_metrics.yml
definitions/infra-f5poolmember/summary_metrics.yml
definitions/infra-f5virtualserver/summary_metrics.yml
definitions/infra-kafkabroker/summary_metrics.yml

Add goldenMetric in SummaryMetric to enums and other entity definitions

fix-gm-sm-goldenmetric

---

definitions/infra-container/golden_metrics.yml
definitions/infra-container/summary_metrics.yml

New golden metric (networkTrafficTotal)

---

definitions/infra-awsroute53healthcheck/golden_metrics.yml
definitions/infra-azurerediscacheshard/summary_metrics.yml

fix sm gm awsroute53
Added Sample query because in some cases GoldenSignals need it.

fix sm gm awsroute53

---

definitions/infra-awsdocdbclusterbyrole/golden_metrics.yml

fixed AWS DocDB golden metrics

fix AWS DocDB GMs

---

definitions/ext-fibre_channel_switch/golden_metrics.yml
definitions/infra-awskinesisdeliverystream/golden_metrics.yml
definitions/infra-awsnlbtargetgroup/golden_metrics.yml
definitions/infra-awsredshiftnode/golden_metrics.yml
definitions/infra-nginxserver/golden_metrics.yml
definitions/infra-vspherecluster/golden_metrics.yml

Checking discrepancies between Summary metrics results in some entities with GoldenMetrics. Found some query discrepancies and minor errors.

fix some queries of sm gm

---

definitions/infra-azureapimanagementservice/golden_metrics.yml

update Azure API management GM units

update Azure API management GM units

---

definitions/infra-azureapimanagementservice/summary_metrics.yml

update Azure API management SM

update Azure API management SM

---

definitions/infra-awsecscluster/golden_metrics.yml

fix AWS ECS cpu utilization GM

fix AWS ECS cpu utilization GM

---

definitions/infra-awsapigatewayresourcewithmetrics/golden_metrics.yml

fix API Gateway GM

---

definitions/infra-awsapigatewayresourcewithmetrics/summary_metrics.yml

fix API Gateway SM

---

README.md
docs/lifecycle.md

Add a bit more info about the `alertable` attribute and it's implications when set to `false`.

Update lifecycle section with alertable attribute info

---

definitions/mlops-machine_learning_model/golden_metrics.yml
definitions/mlops-machine_learning_model/summary_metrics.yml

- Added a golden and summary metric, hopefully it will be shown in the entity explorer

Add Total inference to mlops-machine-learning-model

---

definitions/ext-coredns/dashboard.json

Fixed layout (removed blank space) and a couple of minor typos.
* [N/A] The value of the attribute marked as `identifier` will be unique and valid. 
* [N/A] I've confirmed that my entity type wasn't already defined. If it is I'm providing an

Minor fixes to coredns dashboard layout

---

definitions/infra-awselasticachememcachednode/summary_metrics.yml

update awselasticachememcachednode SM

NR-30538: update awselasticachememcachednode SM

---

definitions/infra-awsdynamodbglobalsecondaryindex/summary_metrics.yml

update awsdynamodbglobalsecondaryindex SM

NR-30541: update awsdynamodbglobalsecondaryindex SM

---

definitions/infra-vspheredatacenter/golden_metrics.yml
definitions/infra-vspheredatacenter/summary_metrics.yml

fix SummaryMetric and GoldenMetric on  VSPHEREDATACENTER

fix sm gm vsphere

---

definitions/infra-host/summary_metrics.yml

Add networkTrafficTx and networkTrafficRx SMs for INFRA-HOST to replace networkTraffic

Align SM and GM definitions for INFRA-HOST

---

definitions/infra-host/summary_metrics.yml

s/memoryUsage/memoryUsedPercent

Fix infra-host memory usage metric

---

definitions/infra-awss3bucket/summary_metrics.yml

NR-30540 fix GoldenMetric SummaryMetric infra-awss3bucket

NR-30540 gm sm infra-awss3bucket

---

definitions/mlops-machine_learning_model/summary_metrics.yml

NR-30507 add goldenMetric param to mlops

NR-30507 gm mlops

---

definitions/infra-awsrdsdbinstance/golden_metrics.yml
definitions/infra-awsrdsdbinstance/summary_metrics.yml

NR-30539 fix gm-sm awsrdsdbinstance

NR-30539-gm-sm-awsrdsdbinstance

---

definitions/browser-application/golden_metrics.yml
definitions/ext-istio_service/definition.yml

I am on the Application Experience team at New Relic. We maintain the UIs for Browser and Mobile experiences. We are trying to get our summary metrics and golden metrics in order. To do that, we are adding a couple of key metrics to this definition. 

Update Application Experience golden metrics

---

definitions/mobile-application/golden_metrics.yml
definitions/mobile-application/summary_metrics.yml

Hi! I am from the Application Experience team and we are trying to get our summary and golden metrics in sync. This PR is to update summary and golden metrics for Mobile apps. 

feat: Update mobile golden metrics and summary metrics

---

definitions/mobile-application/summary_metrics.yml

NR-19426 add `goldenMetric` field into summaryMetrics to align them with Golden Metrics

NR-19426 gm sm mobile app

---

definitions/apm-application/summary_metrics.yml
definitions/mobile-application/summary_metrics.yml

Add summary metric definitions for APM-APPLICATION

---

definitions/infra-container/golden_metrics.yml
definitions/infra-container/summary_metrics.yml

Add missing GM to INFRA-CONTAINER and align queries used in GMs and SMs. 

Align SM and GM definitions for INFRA-CONTAINER

---

definitions/infra-awselasticacheredisnode/golden_metrics.yml

fix elasticache redis GM definition

fix elasticache redis GM definition

---

definitions/infra-awselasticachememcachednode/golden_metrics.yml
definitions/infra-awselasticachememcachednode/summary_metrics.yml

Use correct units in the SM and GM definitions.

Fix definitions for INFRA-ELASTICACHEMEMCACHEDNODE

---

definitions/infra-gcppubsubtopic/golden_metrics.yml
definitions/infra-gcppubsubtopic/summary_metrics.yml

Add golden metric definitions using both Samples and DMs. As well, rename one GM using the correct name. 

Fix definitions for INFRA-GCPPUBSUBTOPIC

---

definitions/infra-gcpkubernetescontainer/golden_metrics.yml
definitions/infra-gcpkubernetesnode/golden_metrics.yml

Update GM definitions for INFRA-GPCKUBERNETES{CONTAINER,NODE} 

---

definitions/ext-sap_idoc/definition.yml
definitions/ext-sap_job/definition.yml
definitions/ext-sap_transaction/definition.yml

* [ x] I've read the guidelines and understand the acceptance criteria.

Sap biz tags

---

definitions/ext-email_gateway/golden_metrics.yml
definitions/ext-email_gateway/summary_metrics.yml
definitions/ext-ups/definition.yml
definitions/ext-ups/golden_metrics.yml
definitions/ext-ups/kentik-apc_ups-dashboard.json
definitions/ext-ups/kentik-tripplite-ups-dashboard.json
definitions/ext-ups/kentik-ups-dashboard.json
definitions/ext-ups/summary_metrics.yml

adding 2 new data sources to the existing `EXT-UPS` entity definition

chore: add 2 new telemetry sources to ext-ups

---

definitions/mobile-application/golden_metrics.yml
definitions/mobile-application/summary_metrics.yml

As per our meeting earlier, here are the golden metrics names and queries that we want to use. I am setting this as a draft PR so that it isn't merged until the golden metrics are created. 

Update mobile golden metric names

---

definitions/infra-vspheredatastore/golden_metrics.yml

Add GM queries to work properly with GoldenSignals in infra-vspheredatastore

NR-30537_sm_gm_infra-vspheredatastore

---

definitions/aiops-issue/definition.yml

fix aiops/issue to alertable=true

---

definitions/ext-aws_elemental/definition.yml
definitions/ext-aws_elemental/golden_metrics.yml
definitions/ext-aws_elemental/kentik-elemental-dashboard.json
definitions/ext-aws_elemental/summary_metrics.yml

Create a new entity for AWS Elemental appliances

Add AWS Elemental entity

---

definitions/infra-gcpkubernetescontainer/golden_metrics.yml
definitions/infra-gcpkubernetesnode/golden_metrics.yml
definitions/infra-gcppubsubtopic/golden_metrics.yml

Fix typo in gcppubsubtopic GM definitions

---

definitions/infra-gcpkubernetescontainer/golden_metrics.yml
definitions/infra-gcpkubernetesnode/golden_metrics.yml

Add missing eventName attrs to GPC K8s golden metric definitions

---

definitions/infra-awselasticacheredisreplicationgroup/definition.yml
definitions/infra-awselasticacheredisreplicationgroup/golden_metrics.yml
definitions/infra-awselasticacheredisreplicationgroup/summary_metrics.yml
definitions/infra-awselasticacheredisshard/definition.yml
definitions/infra-awselasticacheredisshard/golden_metrics.yml
definitions/infra-awselasticacheredisshard/summary_metrics.yml

add redis replication group and shard entities

add redis replication group and shard entities

---

definitions/ext-factorio_game/dashboard.json

Modified the overview for FACTORIO_GAME to include item production

---

definitions/ext-service_level/definition.yml
definitions/ext-service_level/summary_metrics.yml

Add summary metrics for Service Levels and add those tags also as goldenTags.
* [ X] I've read the guidelines and understand the acceptance criteria.
* [ X] The value of the attribute marked as `identifier` will be unique and valid. 
* [ X] I've confirmed that my entity type wasn't already defined. If it is I'm providing an

feat: add summary metrics for ext-service_level

---

definitions/ext-service_level/definition.yml

Make Service Level entities alertable.

feat: make service levels alertable

---

.github/CODEOWNERS

Modify codeowners.

---

validator/package-lock.json

We just get a report about the minimatch vulnerability. This PR is just upgrading such library, so we don't have any vulnerability in our project.

Fix vulnerability

---

definitions/ext-pixie_dns/dashboard.json

Simple update to the layout. Just moved one item to its own row and expanded the other items.

Update Pixie DNS layout

---

definitions/ext-not_instrumented/definition.yml

Reverts newrelic/entity-definitions#842

Revert "Remove not_instrumented type"

---

definitions/ext-not_instrumented/definition.yml

This PR is for re-applying PR https://github.com/newrelic/entity-definitions/pull/842 after the UI definitions have been removed.

Revert of "Revert "Remove not_instrumented type""

---

definitions/ext-key_transaction/golden_metrics.yml
definitions/ext-key_transaction/summary_metrics.yml

I have created summary metrics for Key Transaction with using golden metrics attributes

feat: NR-10056 adding sumary metrics to Key transaction entity

---

definitions/ext-firewall/fortinet-fortigate-dashboard.json

Adjusted widget based on customer feedback from max() to latest()

fix: Fortigate dashboard max to latest for CPU widget

---

definitions/infra-azurecosmosdbaccount/definition.yml

add synthesis rule for Azure CosmosDB account

add synthesis rule for Azure CosmosDB account

---

definitions/infra-host/golden_metrics.yml

Reverts newrelic/entity-definitions#862

Revert "NEWRELIC-4198 : Update OTEL Host golden metrics (network.io)"

---

validator/package-lock.json
validator/package.json

More info:
- https://security.snyk.io/vuln/SNYK-JS-FASTJSONPATCH-3182961
- https://security.snyk.io/vuln/SNYK-JS-JSON5-3182856

Update JSON libs to fix vulnerabilities

---

definitions/ref-build_artifact/definition.yml

Adding `Build Artifact` to support container scan results in Vulnerability Management

adding build artifact type

---

validator/sanitizeDashboards.Dockerfile
validator/validateDefinitions.Dockerfile

[NR-78597] chore: update node library to avoid security issue

---

definitions/infra-azureappserviceplan/definition.yml
definitions/infra-azurecosmosdbaccount/definition.yml
definitions/infra-azurepostgresqlserver/definition.yml

Updated missed definitions for Azure to all be lower-case

update Azure definitions to lower-case

---

definitions/uninstrumented-container/definition.yml
definitions/uninstrumented-host/definition.yml

Follow-up from #816 introducing more uninstrumented types.
* [X ] I've read the guidelines and understand the acceptance criteria.

Introduce uninstrumented hosts and containers

---

definitions/infra-azureappserviceplan/golden_metrics.yml

Fix azure app service plan GMs 

Fix azure app service plan GMs

---

definitions/aiops-workflow/definition.yml

Added the aiops-workflow definition to support Workflows as Entities project

feat: add workflow entity definition

---

definitions/infra-azuremysqlflexibleserver/definition.yml

fix Azure MySQL condition casing

---

definitions/ext-aws_region/definition.yml
definitions/test-jpujol/definition.yml
definitions/test-manuelrodriguez/definition.yml

Remove types that where used for tests or early poc's

Cleanup test types

---

definitions/ext-solarwinds_server/definition.yml

Change the entityExpiration from 8 days to 1 day due to the SW hosts ephemeral nature

Update definition.yml for entity expiration

---

definitions/infra-mongodb_collection/dashboard.json
definitions/infra-mongodb_collection/definition.yml
definitions/infra-mongodb_database/dashboard.json
definitions/infra-mongodb_database/definition.yml
definitions/infra-mongodb_instance/dashboard.json
definitions/infra-mongodb_instance/definition.yml

This PR adds dashboards for the new MongoDB entities

Mongodb dashboards

---

definitions/infra-azureappserviceplan/golden_metrics.yml

Describe what you have done and any details that you think are relevant or that you might want to discuss with us.

NR-81315 Added event name to azureappserviceplan

---

definitions/ext-gigamon_dns/definition.yml
definitions/ext-gigamon_dns/giga-dns-dashboard.json
definitions/ext-gigamon_dns/summary_metrics.yml

First go at an entity definition built from our Gigamon partnership

Gigamon dns

---

definitions/ext-snmp_appliance/aruba-clearpass-dashboard.json
definitions/ext-snmp_appliance/default-dashboard.json
definitions/ext-snmp_appliance/definition.yml
definitions/ext-snmp_appliance/golden_metrics.yml
definitions/ext-snmp_appliance/summary_metrics.yml

New network entity ext-snmp_appliance

Add snmp appliance

---

definitions/ext-coredns/golden_metrics.yml

Adding request duration metric using histogrampercentile().

Adding request duration metric using histogrampercentile()

---

.github/CODEOWNERS

Add @lujop, aka jpujol,  as a reviewer

Add lujop to CODEOWNERS

---

definitions/ext-snmp_appliance/default-dashboard.json

Fixed several copy-pasted dashboard references to a different entity type

fix: correct where conditions

---

definitions/aiops-policy/definition.yml

I've added alerting policies as an entity, as per this ticket: https://issues.newrelic.com/browse/NR-94719
* [ x ] I've read the guidelines and understand the acceptance criteria.
* [ x ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ x ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an

[NR-94719] feat: Policies as entities

---

definitions/infra-squid_cachemgr/dashboard.json
definitions/infra-squid_cachemgr/definition.yml
definitions/infra-squid_cachemgr/golden_metrics.yml
definitions/infra-squid_cachemgr/summary_metrics.yml
definitions/infra-squid_cachemgr/tests/MetricRaw.json

Modifying the attribute used for entity synthesis to the new one decided by CoreInt's product.
Adding the Golden Metrics and Entity Dashboards for the Squid Cache Manager.

INFRA Squid Cache Manager improve experience (GM, SM & dashboards)

---

definitions/ext-network_dns_service/golden_metrics.yml

ext-network_dns_service: Updated the instrumentation.name

---

definitions/ext-firewall/cisco-asa-dashboard.json

Added many widgets to the ext-firewall cisco asa dashboard

EXT-FIREWALL: Update cisco-asa-dashboard.json

---

definitions/ext-team/definition.yml

feat: add new entity team

---

validator/sanitizeDashboards.Dockerfile
validator/validateDefinitions.Dockerfile

Node docker image upgrade to node:19.8.1-alpine3.17. 

Node docker image upgrade to node:19.8.1-alpine3.17

---

definitions/infra-kubernetes_cronjob/dashboard.json
definitions/infra-kubernetes_job/dashboard.json

Improve presentation of pod failure reason

Improvements to CronJob and Job dashboards

---

definitions/infra-azurednszones/definition.yml
definitions/infra-azurednszones/golden_metrics.yml
definitions/infra-azurednszones/summary_metrics.yml

Adding Azure DNS Zones as an entity as part of Project NorthStar from the Product Partnerships team.

Azure DNS Zones - Project NorthStar

---

definitions/infra-azureeventgriddomains/definition.yml
definitions/infra-azureeventgriddomains/golden_metrics.yml
definitions/infra-azureeventgriddomains/summary_metrics.yml

Adding Azure Event Grid Domains as an entity as part of Project NorthStar from the Product Partnerships team.

Azure Event Grid Domains - Project NorthStar

---

definitions/infra-azureeventgridpartnernamespaces/definition.yml
definitions/infra-azureeventgridpartnernamespaces/golden_metrics.yml
definitions/infra-azureeventgridpartnernamespaces/summary_metrics.yml

Adding Azure Event Grid Partner Namespaces as an entity as part of Project NorthStar from the Product Partnerships team.

Infra azureeventgridpartnernamespaces

---

definitions/infra-azureeventgridpartnertopics/definition.yml
definitions/infra-azureeventgridpartnertopics/golden_metrics.yml
definitions/infra-azureeventgridpartnertopics/summary_metrics.yml

Adding Azure Event Grid Partner Topics as an entity as part of Project NorthStar from the Product Partnerships team.

Azure Event Grid Partner Topics - Project NorthStar

---

definitions/infra-azureeventgridsystemtopics/definition.yml
definitions/infra-azureeventgridsystemtopics/golden_metrics.yml
definitions/infra-azureeventgridsystemtopics/summary_metrics.yml

This adds Azure Event Grid System Topics service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Event Grid System Topics - Project NorthStar

---

definitions/infra-azureeventgridtopics/definition.yml
definitions/infra-azureeventgridtopics/golden_metrics.yml
definitions/infra-azureeventgridtopics/summary_metrics.yml

This adds Azure Event Grid Topics service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Event Grid Topics - Project NorthStar

---

definitions/infra-azuremediaservices/definition.yml
definitions/infra-azuremediaservices/golden_metrics.yml
definitions/infra-azuremediaservices/summary_metrics.yml

This adds Azure Media Services service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Media Services - Project NorthStar

---

definitions/infra-azuremediaservicesliveevents/definition.yml
definitions/infra-azuremediaservicesliveevents/golden_metrics.yml
definitions/infra-azuremediaservicesliveevents/summary_metrics.yml

This adds Azure Media Services Live Events service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Media Services Live Events - Project NorthStar

---

definitions/infra-azuremediaservicesstreamingendpoints/definition.yml
definitions/infra-azuremediaservicesstreamingendpoints/golden_metrics.yml
definitions/infra-azuremediaservicesstreamingendpoints/summary_metrics.yml

This adds Azure Media Services Streaming Endpoints service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Media Services Streaming Endpoints - Project NorthStar

---

definitions/infra-azuremediaservicesvideoanalyzer/definition.yml
definitions/infra-azuremediaservicesvideoanalyzer/golden_metrics.yml
definitions/infra-azuremediaservicesvideoanalyzer/summary_metrics.yml

This adds Azure Media Services Video Analyzer service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure Media Services Video Analyzer - Project NorthStar

---

definitions/infra-azureiotcentralapplications/definition.yml
definitions/infra-azureiotcentralapplications/golden_metrics.yml
definitions/infra-azureiotcentralapplications/summary_metrics.yml

This adds Azure IOT Central Applications service as an entity in New Relic, using Azure Monitor. This is part of Project NorthStar by the Product Partnerships team.

Azure IOT Central Applications - Project NorthStar

---

definitions/infra-kubernetes_persistentvolume/summary_metrics.yml

I misspelled these two attributes in #1013.

Fix K8s PersistentVolume Summary Metrics

---

definitions/infra-azuresignalr/definition.yml
definitions/infra-azuresignalr/golden_metrics.yml
definitions/infra-azuresignalr/summary_metrics.yml

Adding Azure SignalR entity as part of Project NorthStar Azure - cohort 2, from the Product Partnership team.

Project NorthStar Azure - infra-azuresignalr

---

definitions/infra-azurerelay/definition.yml
definitions/infra-azurerelay/golden_metrics.yml
definitions/infra-azurerelay/summary_metrics.yml

Adding Azure Relay entity as part of Project NorthStar Azure - cohort 2, from the Product Partnership team.

Project NorthStar Azure - infra-azurerelay

---

definitions/infra-azurenetworkwatcher/definition.yml
definitions/infra-azurenetworkwatcher/golden_metrics.yml
definitions/infra-azurenetworkwatcher/summary_metrics.yml

Adding Azure Network Watcher entity as part of Project NorthStar Azure - cohort 2, from the Product Partnership team.

Project NorthStar Azure - infra-azurenetworkwatcher

---

definitions/infra-azurenetappcapacitypool/definition.yml
definitions/infra-azurenetappcapacitypool/golden_metrics.yml
definitions/infra-azurenetappcapacitypool/summary_metrics.yml

Adding Azure Net App Capacity Pools as part of Project NorthStar Azure - cohort 2, from the Product Partnerships team.

Project NorthStar Azure - infra-azurenetappcapacitypool

---

definitions/infra-azurestoragesync/definition.yml
definitions/infra-azurestoragesync/golden_metrics.yml
definitions/infra-azurestoragesync/summary_metrics.yml

New Azure entity for NorthStar Azure project, cohort 2, from the Product Partnerships team.

Project NorthStar Azure - infra-azurestoragesync

---

.github/CODEOWNERS
.github/pull_request_template.md

As we agreed internally.
Removing codeowners to avoid noise.
Our 2 heroe's will monitor the repo

Remove codeowners

---

definitions/infra-azurestoragesync/golden_metrics.yml
definitions/infra-azurestoragesync/summary_metrics.yml

For Azure StorageSync, standardizing the names in the golden metrics and summary metrics files

Project NorthStarAzure Cohort 2 Fixes

---

validator/package-lock.json
validator/package.json
validator/tools/sanitize_dashboards.js
validator/tools/utils.js
validator/tools/validate_folders.js

Upgrade validator dependencies.

Upgrade validator dependencies. 

---

definitions/uninstrumented-host/definition.yml

Temporarily reduce TTL of unistrumented hosts to 4 hours
~~* [ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.~~

Temporarily change uninstrumented host TTL to 4 hours

---

definitions/infra-awschatbot/dashboard.json
definitions/infra-awschatbot/definition.yml
definitions/infra-awschatbot/golden_metrics.yml
definitions/infra-awschatbot/summary_metrics.yml

This PR is to increase AWS Integrations under Project Northstar

[Product-Partnerships] Added AWS Entity chatbot

---

definitions/ext-rservice/dashboard.json
definitions/ext-rservice/golden_metrics.yml

errorRate golden signal was not capturing the metric correctly; and the responseTimeMS golden signal was too restrictive as well as within the dashboard as well.

Fix errorRate and response time for ext-rservice

---

definitions/infra-awstranscribe/dashboard.json
definitions/infra-awstranscribe/definition.yml
definitions/infra-awstranscribe/golden_metrics.yml
definitions/infra-awstranscribe/summary_metrics.yml

Asana Task - https://app.asana.com/0/1202974982230192/1202975137301837
Partnership Engineering Team - 
- Added AWS-Transcribe Entity
- Amazon Transcribe is an automatic speech recognition service that uses machine learning models to convert audio to text. You can use Amazon Transcribe as a standalone transcription service or to add speech-to-text capabilities to any application.

[Product Partnerships] Added AWS Transcribe

---

definitions/mlops-llm_application/definition.yml

chore(mlops-llm-application): Fix conditions

---

definitions/ext-firewall/default-dashboard.json
definitions/ext-router/default-dashboard.json
definitions/ext-switch/default-dashboard.json

This PR adds a couple more styling tweaks to network monitoring default dashboards. Also fixes a typo in the layout for firewalls

refactor: Styling network monitoring dashboards

---

definitions/infra-azurecognitiveservice/definition.yml
definitions/infra-azurecognitiveservice/golden_metrics.yml
definitions/infra-azurecognitiveservice/summary_metrics.yml

Added azure cognitive service entity to increase number of integrations with Azure.

[Product Partnerships]Added Azure cognitive services entity

---

definitions/infra-azurebingsearch/definition.yml
definitions/infra-azurebingsearch/golden_metrics.yml
definitions/infra-azurebingsearch/summary_metrics.yml

Added Azure bing search entity

[Product Partnerships] Azure bing search entity added

---

definitions/ext-network_dns_service/golden_metrics.yml
definitions/ext-network_dns_service/summary_metrics.yml

Simplify queries to handle inconsistent header details

ext-network_dns_service: Simplify Gigamon AppInsights metrics

---

definitions/ext-site/golden_metrics.yml

Include units to golden metrics for consistency with other golden-metrics.yml files

EXT-SITE: Add units to golden metrics

---

definitions/ext-meraki_device/meraki-device-dashboard.json

Update table queries to properly use rate function

ext-meraki_device: Update meraki-device-dashboard.json

---

definitions/browser-micro_frontend/definition.yml

[browser-micro_frontend] Add micro frontend entity type

---

definitions/mlops-machine_learning_model/definition.yml

ADD attribute based condition for Python agent

---

definitions/infra-azurefunctionsworkflow/definition.yml
definitions/infra-azurefunctionsworkflow/golden_metrics.yml
definitions/infra-azurefunctionsworkflow/summary_metrics.yml

Added new entity for azure functions workflow

[Product Partnerships]Azure Functions Workflow entity added

---

validator/validateDefinitions.Dockerfile

Use the most recent version from node for local execution of validations

Use node:latest for local validations execution

---

validator/sanitizeDashboards.Dockerfile

* Use node:latest for local sanitization execution

Use node:latest for local sanitization execution

---

definitions/infra-awsworkmail/dashboard.json
definitions/infra-awsworkmail/definition.yml
definitions/infra-awsworkmail/golden_metrics.yml
definitions/infra-awsworkmail/summary_metrics.yml

Partnership Engineering Team - 
- Added AWS-WorkMail Entity
- Amazon WorkMail is a secure, managed business email and calendar service with support for existing desktop and mobile email client applications. Amazon WorkMail gives users the ability to seamlessly access their email, contacts, and calendars using the client application of their choice, including Microsoft Outlook, native iOS and Android email applications, any client application supporting the IMAP protocol, or directly through a web browser. 
Asana Task - https://app.asana.com/0/1202553104203429/1202975070529557/f

[Product Partnerships] Added Aws workmail Entity

---

definitions/ext-service/golden_metrics.yml

We're building a new APM agent based on Open Telemetry.  The `instrumentation-provider` is set as `newrelic-opentelemtry`.  The agent reports metrics similar to those reported by a normal APM agent, but as dimensional metric data instead of timeslice metrics.  This PR should fix the summary metrics for these agents.
https://github.com/newrelic/newrelic-opentelemetry-java

Add golden metrics for New Relic Otel distro agent

---

definitions/ext-service/golden_metrics.yml

Sigh.  So close, but this is showing error rate from 0-1 instead of 0-100.

Show error rate as percentage

---

definitions/infra-awsdatasync/dashboard.json
definitions/infra-awsdatasync/definition.yml
definitions/infra-awsdatasync/golden_metrics.yml
definitions/infra-awsdatasync/summary_metrics.yml

[Product Partnerships] Added AWS DataSync

---

definitions/infra-awssimpleworkflow/golden_metrics.yml
definitions/infra-awssimpleworkflow/summary_metrics.yml

[Product Partnerships ] Updated Golden Metrics

---

validator/package.json
validator/schemas/relationship-synthesis-schema-v1.json

Create a new schema validation for Relationship Synthesis.  It will make sure that the YMLs defining relationship synthesis are correct

[NR-120588] feat: relationship synthesis schema

---

docker-compose.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-REDISINSTANCE.yml
relationships/synthesis/INFRA-HOST-to-EXT-SERVICE.yml
validator/README.md
validator/package.json
validator/schemas/relationship-synthesis-schema-v1.json
validator/tools/props.js
validator/tools/utils.js
validator/tools/validate_relationship_synthesis_rules.js

Add first set of rules for relationship synthesis validation rules

[Nr 120588] relationship synthesis validation rules

---

relationships/README.md

Add extra README.md inside of the relationships folder.

Add extra README.md inside of the relationships folder

---

relationships/README.md

Fix links to other relationship docs sections on the markdown file.

Adjust docs candidates links

---

docs/relationships/README.md
relationships/README.md

Adjust working on relationship synthesis.

Adjust working on relationship synthesis

---

definitions/ext-firewall/fortinet-fortigate-dashboard.json

Updated ext-firewall entity dashboard based on customer feedback

Chore: Update fortinet-fortigate-dashboard.json

---

docs/entities/lifecycle.md

Improve lifecycle docs based on the recommendations from the technical writer.
Reflects also the recent changes on the public docs: https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic/#expiration

[NR-147041] Improve lifecycle docs

---

entity-types/infra-awssagemaker/golden_metrics.yml
entity-types/infra-awssagemaker/summary_metrics.yml

[Product Partnerships] Updating AWS Sagemaker Entity

---

entity-types/infra-azurevirtualhub/definition.yml
entity-types/infra-azurevirtualhub/golden_metrics.yml
entity-types/infra-azurevirtualhub/summary_metrics.yml

- Added new entity for Azure Virtual Hubs, i.e. `Microsot.Network/virtualhubs`

[NR-149170] Add infra-azurevirtualhub

---

entity-types/infra-azurefunctionsapp/golden_metrics.yml
entity-types/infra-azurewebapp/golden_metrics.yml

Fixed typo in golden signals metric.
Added golden metric support for Azure Monitor metric

update Azure entities golden metrics

---

relationships/candidates/AWSMSKTOPIC.yml

Add candidate definition for Infra's MSK Topic entity.
In further PR, we will add a synthesis rule for relationships between APM applications and this kind of entity.

Add candidate definition for Infra's MSK Topic entity

---

entity-types/infra-awssagemaker/dashboard.json

[Product Partnerships] Updating Amazon Sagemaker Entity

---

entity-types/ext-pdu/servertech-pdu4-dashboard.json

small PR to expand width of this dashboard a bit

chore: widen servertech dashboard

---

entity-types/mlops-llm_application/definition.yml

ADD  instrumentation.provider condition

---

relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_AMQP.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_CASSANDRA.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_DNS.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_KAFKA.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_MYSQL.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_POSTGRES.yml
relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_REDIS.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_AMQP.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_CASSANDRA.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_DNS.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_KAFKA.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_MYSQL.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_POSTGRES.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_REDIS.yml

Add the relationships of Kubernetes based on Synthesis.

Add the Kubernetes relationships

---

relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-SERVICE.yml
relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-SERVICE.yml

Add the k8s contains ext service

Add the k8s contains ext service

---

relationships/synthesis/EXT-SERVICE-to-EXT-SERVICE.yml

Add EXT SERVICE to EXT SERVICE

Add the ext service to ext service

---

relationships/synthesis/INFRA-HOST-to-MLOPS-MACHINE_LEARNING_MODEL.yml

Add the MLOPS Machine Learning Model Relationships

Add the relationships from mlops

---

relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_AMQP.yml

Found a typo in the rule definition while migrating

Fix k8sPodContainsExtPixieAmqp relationhip

---

entity-types/infra-awselementalmediaconvert/definition.yml

[Product Partnerships] Added AWS Elemental Media Convert

---

entity-types/ext-package/summary_metrics.yml

This PR adds a few summary tags for the new Package entity

Add summary tags

---

relationships/synthesis/INFRA-HOST-to-MLOPS-MACHINE_LEARNING_MODEL.yml

Updated relationship name to reflect the verb of the relationship.

Update verb for ml relationship

---

entity-types/ext-testreplacement/definition.yml

test: see if replacement works as expected in Staging

test: see if replacement works as expected in Staging

---

entity-types/infra-redisinstance/definition.yml
entity-types/infra-redisinstance/golden_metrics.yml

[infra-redisinstance] Update the whole entity for the new experience [NR-147979]

---

relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_KAFKA.yml

fix k8sPodContainsExtPixieKafka rule

---

docs/entities/synthesis.md

Change the tags options by title to add an anchor.

Change the tags options by title to add an anchor.

---

entity-types/infra-azuremachinelearningdeployment/definition.yml
entity-types/infra-azuremachinelearningdeployment/golden_metrics.yml
entity-types/infra-azuremachinelearningdeployment/summary_metrics.yml

[Product Partnerships] Added Azure Machine Learning Deployment Entity

---

entity-types/infra-awsappstream/dashboard.json
entity-types/infra-awsappstream/definition.yml
entity-types/infra-awsappstream/golden_metrics.yml
entity-types/infra-awsappstream/summary_metrics.yml

[Product Partnerships] Added Amazon AppStream Entity

---

entity-types/infra-redisinstance/tests/Metric.json

Added unit tests for Redis instance

Unit test for otel redis instance

---

entity-types/infra-awscloudsearch/dashboard.json
entity-types/infra-awscloudsearch/definition.yml
entity-types/infra-awscloudsearch/golden_metrics.yml
entity-types/infra-awscloudsearch/summary_metrics.yml

[Product Partnerships] Added Amazon CloudSearch Entity

---

.github/workflows/validate-definition.yml

Add permissions in the workflow to grant the write in prs

Add permisions in the workflow to grant the permissions to write in pr

---

entity-types/infra-host/golden_metrics.yml

update HOST GMs with cloud Events data

update HOST GMs with cloud Events data

---

entity-types/infra-awstransferfamily/dashboard.json
entity-types/infra-awstransferfamily/definition.yml
entity-types/infra-awstransferfamily/golden_metrics.yml
entity-types/infra-awstransferfamily/summary_metrics.yml

[Product Partnerships] Added Amazon Transfer Family Entity

---

entity-types/ext-rservice/definition.yml

Expanding definition rules to include additional services to be included as part of the ext-rservice entity. I also removed a product services beginning with "gaps.".
* [ x] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

New set of products services

---

entity-types/ext-pinecone_index/dashboard.json
entity-types/ext-pinecone_index/definition.yml
entity-types/ext-pinecone_index/golden_metrics.yml

Adding an entity for the [Pinecone vector DB](https://www.pinecone.io/). This is a SaaS product and can be monitored with Prometheus according to [this documentation](https://docs.pinecone.io/docs/monitoring)

Pinecone index entity

---

entity-types/infra-awskeyspaces/dashboard.json
entity-types/infra-awskeyspaces/definition.yml
entity-types/infra-awskeyspaces/golden_metrics.yml
entity-types/infra-awskeyspaces/summary_metrics.yml

[Product Partnerships] Added Amazon Keyspaces Entity

---

entity-types/nr1-fleet/definition.yml

Add a new entity type for Fleets.

Add NR1-FLEET type

---

docs/README.md

Dummy Update of README

---

validator/sanitizeDashboards.Dockerfile
validator/validateDefinitions.Dockerfile

Fix https://www.cve.org/CVERecord?id=CVE-2023-45853
Changing node image to alpine based one as Debian ones we were using still have the security issue
https://hub.docker.com/_/node/tags

Fix  CVE-2023-45853

---

entity-types/infra-gcpaiplatformendpoint/definition.yml
entity-types/infra-gcpaiplatformfeatureonlinestore/definition.yml
entity-types/infra-gcpaiplatformfeaturestore/definition.yml
entity-types/infra-gcpaiplatformindex/definition.yml
entity-types/infra-gcpaiplatformlocation/definition.yml

Adding support for new Cloud Integration GCP Vertex AI

NR-168688: Add support for GCP Vertex AI

---

entity-types/infra-awsfsxforlustre/dashboard.json
entity-types/infra-awsfsxforlustre/definition.yml
entity-types/infra-awsfsxforlustre/golden_metrics.yml
entity-types/infra-awsfsxforlustre/summary_metrics.yml

[Product Partnerships] Added Fsx Lustre Entity

---

docs/relationships/candidate_relationships.md

Fixes candidate_relationships.md onMiss/onMatch fields with the correct data.

Fixes candidate_relationships.md onMiss/onMatch fields

---

entity-types/infra-awsusage/definition.yml
entity-types/infra-awsusage/golden_metrics.yml
entity-types/infra-awsusage/summary_metrics.yml

AWS Usage entity

---

entity-types/infra-host/golden_metrics.yml

Resolves [NR-181941](https://new-relic.atlassian.net/browse/NR-181941) to update golden metrics for prometheus hosts.

fix: Update prometheus golden metrics

---

entity-types/infra-host/golden_metrics.yml

This reverts commit 6b95105c824825c9ad7f272a66ddcb075764d393.

Revert "fix: Update prometheus golden metrics (#1302)"

---

entity-types/infra-host/golden_metrics.yml

Updated `select` to remove `filter`. I believe the previous query was improperly defined and this should meet our needs and not require extra fixes in https://new-relic.atlassian.net/browse/NR-190474.

Feat: Prometheus golden metric

---

entity-types/infra-awseventsrule/definition.yml
entity-types/infra-awseventsrule/golden_metrics.yml
entity-types/infra-awseventsrule/summary_metrics.yml

AWSEVENTSRULE

---

entity-types/infra-awsvpcvpntunnel/golden_metrics.yml
entity-types/infra-awsvpcvpntunnel/summary_metrics.yml
entity-types/infra-awsvpnconnection/definition.yml
entity-types/infra-awsvpnconnection/golden_metrics.yml
entity-types/infra-awsvpnconnection/summary_metrics.yml

AWSVPCVPNTUNNEL & AWSVPNCONNECTION

---

entity-types/infra-elasticsearchnode/newrelic_dashboard.json

Convert Elastic Search dashboard back to samples

Convert Elastic Search dashboard back to samples

---

entity-types/infra-kafkabroker/newrelic_dashboard.json

Convert Kafka Broker dashboard back to sample

Convert Kafka Broker dashboard back to sample

---

README.md

Updated the link to ext-pihole example.

Update README.md with a valid link to ext-pihole

---

entity-types/ext-air_conditioner/liebert-dashboard.json
entity-types/ext-pdu/servertech-pdu4-dashboard.json
entity-types/ext-sd_wan/cloudgenix-dashboard.json
entity-types/ext-waf/kentik-waf-dashboard.json

Remove a duplicated `AS` clause from some queries. This should fix some dashboards that were broken because of it.

fix(queries): Fix typos in queries

---

entity-types/infra-nginxserver/newrelic_dashboard.json

Convert Nginx server dashboard back to sample

Convert Nginx server dashboard back to sample

---

entity-types/infra-postgresqlinstance/newrelic_dashboard.json

Convert PostgreSQL Instance dashboard back to sample

Convert PostgreSQL Instance dashboard back to sample

---

entity-types/infra-mysqlnode/newrelic_dashboard.json

Convert MySQL Node dashboard back to sample

Convert MySQL Node dashboard back to sample

---

entity-types/infra-rabbitmqqueue/newrelic_dashboard.json

Convert RabbitMQ queue dashboard back to sample

Convert RabbitMQ queue dashboard back to sample

---

entity-types/infra-rabbitmqcluster/newrelic_dashboard.json

Convert RabbitMQ Cluster dashboard back to sample

Convert RabbitMQ Cluster dashboard back to sample

---

entity-types/infra-rabbitmqexchange/newrelic_dashboard.json

Convert RabbitMQ Exchange dashboard back to sample

Convert RabbitMQ Exchange dashboard back to sample

---

entity-types/infra-rabbitmqnode/newrelic_dashboard.json

Convert RabbitMQ Node dashboard back to sample

Convert RabbitMQ Node dashboard back to sample

---

entity-types/infra-redisinstance/newrelic_dashboard.json

Convert Redis Instance dashboard back to sample

Convert Redis Instance dashboard back to sample

---

entity-types/infra-vspherevm/newrelic_dashboard.json

Convert Vsphere VM dashboard back to sample

Convert Vsphere VM dashboard back to sample

---

entity-types/infra-vspherehost/newrelic_dashboard.json

Convert VSphere Host dashboard back to sample

Convert VSphere Host dashboard back to sample

---

entity-types/infra-vspheredatastore/newrelic_dashboard.json

Convert VSphere Datatore dashboard back to sample

Convert VSphere Datatore dashboard back to sample

---

entity-types/infra-vspheredatacenter/newrelic_dashboard.json

Convert VSphere Datacenter dashboard back to sample

Convert VSphere Datacenter dashboard back to sample

---

entity-types/infra-couchbasebucket/newrelic_dashboard.json

Update the couchbase bucke entity to use samples instead of metrics

Convert couchbase bucket back to sample

---

entity-types/infra-couchbasecluster/newrelic_dashboard.json

Convert couchbase cluster dashboard back to sample

Convert couchbase cluster dashboard back to sample

---

entity-types/infra-couchbasenode/newrelic_dashboard.json

Convert couchbase node dashboard back to sample

Convert couchbase node dashboard back to sample

---

entity-types/infra-memcachedinstance/newrelic_dashboard.json

Convert Memcached instance dashboard back to sample

Convert Memcached instance dashboard back to sample

---

entity-types/infra-f5node/newrelic_dashboard.json

Convert F5 Node dashboard back to sample

Convert F5 Node dashboard back to sample

---

entity-types/infra-f5system/newrelic_dashboard.json

Convert F5 System dashboard back to sample

Convert F5 System dashboard back to sample

---

entity-types/infra-f5poolmember/newrelic_dashboard.json

Convert F5 Pool Member dashboard back to sample

Convert F5 Pool Member dashboard back to sample

---

entity-types/infra-f5virtualserver/newrelic_dashboard.json

Convert F5 Virtual Server dashboard back to sample

Convert F5 Virtual Server dashboard back to sample

---

entity-types/infra-mssqlinstance/newrelic_dashboard.json

Convert MS SQL Instance dashboard back to sample

Convert MS SQL Instance dashboard back to sample

---

entity-types/infra-oracledbinstance/newrelic_dashboard.json

Convert OracleDB dashboard back to sample

Convert OracleDB dashboard back to sample

---

entity-types/infra-varnishinstance/newrelic_dashboard.json

Convert Varnish Instance dashboard back to sample

Convert Varnish Instance dashboard back to sample

---

entity-types/infra-vspherecluster/newrelic_dashboard.json

Convert VSphere Cluster dashboard back to sample

Convert VSphere Cluster dashboard back to sample

---

entity-types/infra-kubernetes_persistentvolume/dashboard.json

Convert K8s Persistent Volumes from Metric to Sample

Convert K8s Persistent Volumes from Metric to Sample

---

entity-types/infra-kubernetes_persistentvolumeclaim/dashboard.json

Convert K8s Persistent Volume Claim dashboard from metric to samples

Convert K8s Persistent Volume Claim dashboard from metric to samples

---

entity-types/infra-vsphereresourcepool/newrelic_dashboard.json

Convert Vsphere Resource Pool dashboard back to samples

Convert Vsphere Resource Pool dashboard back to samples

---

entity-types/infra-f5pool/newrelic_dashboard.json

Convert F5 Pool dashboard back to sample

Convert F5 Pool dashboard back to sample

---

entity-types/infra-kubernetes_cronjob/dashboard.json

The previous [PR](https://github.com/newrelic/entity-definitions/pull/1353) contained a mistake which I am fixing in this PR

Fix bad NRQL query in K8s cron jobs dashboard

---

entity-types/aiops-issue/definition.yml

Reverts newrelic/entity-definitions#1357
Reverting these changes to make Issues re-appear in Explorer.

Revert "Change Issues visibility in Explorer & Navigator"

---

entity-types/uninstrumented-awsdynamodbtable/definition.yml
relationships/candidates/AWSDYNAMODBTABLE.yml
relationships/synthesis/EXT-APPLICATION-to-INFRA-DYNAMODBTABLE.yml

- Currently we are working with mapping relationships for Lambda functions for Otel entity. As part of it, I'm trying to adding new rules for DynamoDB calls.
- Please review this PR & provide the feedback on it, And also guid me for further assistance.
- Please find the ticket link [here](https://new-relic.atlassian.net/browse/NR-216368)

NR-216368 : Added relation creation for Service maps in Otel Span data

---

relationships/candidates/AWSDYNAMODBTABLE.yml
relationships/synthesis/EXT-SERVICE-to-INFRA-DYNAMODBTABLE.yml

1. Currently we are working with mapping relationships for Lambda functions for Otel entity. We've already added new rules for DynamoDB calls. Also adding one more field i.e aws.arn for the same.
2. Please review this PR & provide the feedback on it, And also guid me for further assistance.
3. Please find the ticket link [here](https://new-relic.atlassian.net/browse/NR-216368)

Adding Aws Arn tag for dynamoDB relationships

---

entity-types/ext-switch/golden_metrics.yml

fixing the GM query for CPU on dell switches

fix: update dell snmp metric

---

entity-types/infra-awsworkspacesweb/dashboard.json
entity-types/infra-awsworkspacesweb/definition.yml
entity-types/infra-awsworkspacesweb/golden_metrics.yml
entity-types/infra-awsworkspacesweb/summary_metrics.yml

[Product Partnerships] Added AWS Workspace Entity

---

entity-types/infra-container/definition.yml

Adds synthesis of K8s Containers from kube-state-metrics received via OTel endpoint.

feat: K8s container synthesis from ksm->otel

---

entity-types/infra-awsipam/definition.yml
entity-types/infra-awsipam/golden_metrics.yml
entity-types/infra-awsipam/summary_metrics.yml
entity-types/infra-awsipampool/definition.yml
entity-types/infra-awsipampool/golden_metrics.yml
entity-types/infra-awsipampool/summary_metrics.yml
entity-types/infra-awsipamscope/definition.yml
entity-types/infra-awsipamscope/golden_metrics.yml
entity-types/infra-awsipamscope/summary_metrics.yml

AWS IPAM Entities

---

entity-types/infra-awstrustedadvisorcategory/definition.yml
entity-types/infra-awstrustedadvisorcategory/golden_metrics.yml
entity-types/infra-awstrustedadvisorcategory/summary_metrics.yml
entity-types/infra-awstrustedadvisorcheck/definition.yml
entity-types/infra-awstrustedadvisorcheck/golden_metrics.yml
entity-types/infra-awstrustedadvisorcheck/summary_metrics.yml
entity-types/infra-awstrustedadvisorservicelimit/definition.yml
entity-types/infra-awstrustedadvisorservicelimit/golden_metrics.yml
entity-types/infra-awstrustedadvisorservicelimit/summary_metrics.yml

AWS TrustedAdvisor entities

---

entity-types/infra-awssecretsmanager/definition.yml
entity-types/infra-awssecretsmanager/golden_metrics.yml
entity-types/infra-awssecretsmanager/summary_metrics.yml

AWS SecrecsManager entity

---

entity-types/infra-awsnetworkfirewall/definition.yml
entity-types/infra-awsnetworkfirewall/golden_metrics.yml
entity-types/infra-awsnetworkfirewall/summary_metrics.yml

AWS Network Firewall

---

entity-types/infra-awsmemorydbcluster/definition.yml
entity-types/infra-awsmemorydbcluster/golden_metrics.yml
entity-types/infra-awsmemorydbcluster/summary_metrics.yml

AWS MemoryDB Cluster

---

entity-types/infra-awsprometheusrulegroup/definition.yml
entity-types/infra-awsprometheusrulegroup/golden_metrics.yml
entity-types/infra-awsprometheusrulegroup/summary_metrics.yml
entity-types/infra-awsprometheusworkspace/definition.yml
entity-types/infra-awsprometheusworkspace/golden_metrics.yml
entity-types/infra-awsprometheusworkspace/summary_metrics.yml

AWS Prometheus entities

---

entity-types/infra-awskmskey/definition.yml
entity-types/infra-awskmskey/golden_metrics.yml
entity-types/infra-awskmskey/summary_metrics.yml

AWS KMS Key

---

infra-awsecrrepository/definition.yml
infra-awsecrrepository/golden_metrics.yml
infra-awsecrrepository/summary_metrics.yml

AWS ECR entities

---

entity-types/infra-awsgwlb/definition.yml
entity-types/infra-awsgwlb/golden_metrics.yml
entity-types/infra-awsgwlb/summary_metrics.yml
entity-types/infra-awsgwlbtargetgroup/definition.yml
entity-types/infra-awsgwlbtargetgroup/golden_metrics.yml
entity-types/infra-awsgwlbtargetgroup/summary_metrics.yml

AWS Gateway ELB entities

---

entity-types/infra-awscertificatemanager/definition.yml
entity-types/infra-awscertificatemanager/golden_metrics.yml
entity-types/infra-awscertificatemanager/summary_metrics.yml

AWS Certificate Manager Entity

---

entity-types/infra-awsoutpost/definition.yml
entity-types/infra-awsoutpost/golden_metrics.yml
entity-types/infra-awsoutpost/summary_metrics.yml

AWS Outpost entity

---

relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_JOB.yml

Adds synthesis of K8s Cluster-Job relationship from kube-state-metrics received via OTel endpoint.

Os k8s cluster to job

---

entity-types/infra-kubernetes_pod/definition.yml

Remap golden tags for K8s Pods synthesized from ksm->OTel

feat: Remap tags for k8s pods via otel

---

entity-types/infra-kubernetescluster/definition.yml

Adds synthesis of K8s Cluster from metrics received via OTel endpoint.

feat: K8s cluster synthesis from otel

---

entity-types/ebpf-client/definition.yml
entity-types/ebpf-client/tests/Span.json
entity-types/ebpf-redis_server/definition.yml
entity-types/ebpf-redis_server/tests/Span.json
relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml

Updates the `kind` column identifier to match data collected by the ebpf agent.

Update column name for kind (trace_role) in ebpf entities

---

entity-types/infra-kubernetes_persistentvolumeclaim/golden_metrics.yml

Add Kubernetes persistent volume claim golden metric queries for kube-state-metrics -> OpenTelemetry

feat: Golden metrics for OS k8s pvc

---

entity-types/infra-kubernetes_job/golden_metrics.yml

Add Kubernetes job golden metric queries for kube-state-metrics -> OpenTelemetry

feat: Golden metrics for OS k8s job

---

entity-types/infra-awsnetworkfirewall/golden_metrics.yml
entity-types/infra-awsnetworkfirewall/summary_metrics.yml

Found a couple of typos. Fixed them.

Fix Capitalization of TLS

---

entity-types/ebpf-client/definition.yml

Fix indentation for ebpf client entity def

---

.github/workflows/validate-definition.yml
validator/package.json
validator/tools/props.js

Reverts newrelic/entity-definitions#1503 (automatically generated revert)
It's not working as expected and needs to be fixed

Revert "Fix Github validation action"

---

.github/workflows/validate-definition.yml
validator/package.json
validator/tools/props.js

Reverts newrelic/entity-definitions#1505 (automatically generated revert)

Revert "Attemp to fix validator"

---

entity-types/agent-infraagent/definition.yml
entity-types/agent-otelcol/definition.yml
entity-types/agent-superagent/definition.yml

Add the following agent definitions to synthesize agent entities
- Infra
- NRDOT
- SUPERVISOR

Add agent entity definitions

---

.github/workflows/validate-definition.yml
validator/package.json
validator/tools/props.js

Try to fix the validation action
* [X ] I've read the guidelines and understand the acceptance criteria.

Fix validations

---

docs/entities/lifecycle.md

Update documentation to clarify the behaviour of entity's TTL.

Clarify the behaviour of entity's TTL

---

.github/workflows/validate-definition.yml

Cleanup code after testing #1512 works correctly.

Clean some debug code for Fix validation PR

---

relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml

use anyOf not value

---

entity-types/infra-kubernetes_deployment/golden_metrics.yml

Add Kubernetes deployment golden metric queries for kube-state-metrics -> OpenTelemetry

feat: Golden metrics for OS k8s deployment

---

entity-types/infra-gcpvertexaiendpoint/definition.yml
entity-types/infra-gcpvertexaiendpoint/golden_metrics.yml
entity-types/infra-gcpvertexaiendpoint/summary_metrics.yml

This is an entity for VertexAI endpoints. I followed the other GCP infra entites as an example.

feat: added vertex entity def

---

entity-types/ebpf-amqp_server/definition.yml
entity-types/ebpf-amqp_server/tests/Span.json
entity-types/ebpf-cassandra_server/definition.yml
entity-types/ebpf-cassandra_server/tests/Span.json
entity-types/ebpf-dns_server/definition.yml
entity-types/ebpf-dns_server/tests/Span.json
entity-types/ebpf-http_server/definition.yml
entity-types/ebpf-http_server/tests/Span.json
entity-types/ebpf-kafka_server/definition.yml
entity-types/ebpf-kafka_server/tests/Span.json
entity-types/ebpf-mongodb_server/definition.yml
entity-types/ebpf-mongodb_server/tests/Span.json
entity-types/ebpf-mysql_server/definition.yml
entity-types/ebpf-mysql_server/tests/Span.json
entity-types/ebpf-postgres_server/definition.yml
entity-types/ebpf-postgres_server/tests/Span.json

amqp, cassandra, dns, http, kafka, mongodb, mysql, postgres

[EBPF agent] Add ebpf entity definitions for remaining protocols

---

entity-types/ext-temporal/definition.yml
entity-types/ext-temporal/tests/Metric.json

**Description :** Updated the temporal entity.

fix(temporal): Updated temporal entity.

---

entity-types/ext-temporal/definition.yml
entity-types/ext-temporal/tests/Metric.json

**Description:** Updated the Temporal definition identifier.

fix(temporal): Updated temporal definition identifier.

---

relationships/synthesis/EXT-SERVICE-to-INFRA-DYNAMODBTABLE.yml

Adding new rules for DynamoDB calls

Added APM entity to Dynamodb relationship

---

entity-types/ext-envoy/definition.yml
entity-types/ext-envoy/tests/Metric.json

**Description:** Updated envoy identifier in definition.yml

fix: Updated envoy definition

---

entity-types/ext-apache_druid/definition.yml
entity-types/ext-apache_druid/tests/Metric.json

**Description**: Updated apache druid `identifier` in definition.yml and added tests

Updated apache druid definition and added tests

---

entity-types/ext-snowflake/definition.yml
entity-types/ext-snowflake/golden_metrics.yml
entity-types/ext-snowflake/snowflake_dashboard.json
entity-types/ext-snowflake/summary_metrics.yml
entity-types/ext-snowflake/tests/snowflakeLongestQueriesSample.json

**Jira Ticket:** https://new-relic.atlassian.net/browse/NR-262343
**Description:** Added new entity definition for Snowflake.

feat: Added new entity definition to Snowflake

---

entity-types/infra-azurerecoveryservicesvaults/definition.yml
entity-types/infra-azurerecoveryservicesvaults/golden_metrics.yml
entity-types/infra-azurerecoveryservicesvaults/summary_metrics.yml

[Product Partnerships] Added Azure Recovery Services Vault

---

relationships/synthesis/APM-APPLICATION-to-INFRA-AWSMSKTOPIC.yml

Adding produce and consume relationships between APM application and MSK topics.

Add APM to MSK Topic relationships

---

README.md

"Dummy change"

---

README.md

Revert "Dummy change"

---

entity-types/ext-snowflake/definition.yml
entity-types/ext-snowflake/golden_metrics.yml
entity-types/ext-snowflake/snowflake_dashboard.json
entity-types/ext-snowflake/summary_metrics.yml
entity-types/ext-snowflake/tests/snowflakeLongestQueriesSample.json

**Description:** Added new entity definition for Snowflake

Added new entity definition Snowflake.

---

entity-types/infra-rabbitmqqueue/definition.yml

Trailing tab broke PyYAML parsing of this file

Removing trailing whitespace for more compliant YAML

---

entity-types/infra-azureredisenterprisecache/definition.yml
entity-types/infra-azureredisenterprisecache/golden_metrics.yml
entity-types/infra-azureredisenterprisecache/summary_metrics.yml

Add Azure Cache RedisEnterprise entity

---

entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml

We will enable it again at the end of the quarter

Temporary disabling OTel synthesis.yml

---

entity-types/infra-kubernetes_cronjob/definition.yml
entity-types/infra-kubernetes_job/definition.yml
entity-types/infra-kubernetes_persistentvolume/definition.yml
entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml

Reenable synthesis for k8s OTel entities that were temporarily disabled for initial release

Re-enable synthesis for k8s OTel entities

---

entity-types/uninstrumented-memcachedcluster/definition.yml
entity-types/uninstrumented-memcachednode/definition.yml
relationships/candidates/HOST.yml
relationships/candidates/MEMCACHEDCLUSTER.yml
relationships/candidates/MEMCACHEDNODE.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-ELASTICACHEMEMCACHEDCLUSTER.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-ELASTICACHEMEMCACHEDNODE.yml
relationships/synthesis/EXT-SERVICE-to-INFRA-ELASTICACHEMEMCACHEDNODE.yml

Added relationship between an APM Service or an Otel Service to Memcached Node

Add New Relationship for APM/Otel Service to Memcached Node

---

entity-types/ext-linkerd/dashboard.json
entity-types/ext-linkerd/definition.yml
entity-types/ext-linkerd/golden_metrics.yml
entity-types/ext-linkerd/summary_metrics.yml
entity-types/ext-linkerd/tests/linkerd.json

Description: Created entity page for Linkerd

feat: Linkerd entity

---

entity-types/infra-container/definition.yml
entity-types/infra-container/tests/k8s-cadvisor-via-opentelemetry-prometheus-receiver.json
entity-types/infra-container/tests/k8s-ksm-via-opentelemetry-prometheus-receiver.json
entity-types/infra-container/tests/k8s-kubeletstats-opentelemetry.json
entity-types/infra-kubernetes_pod/definition.yml
entity-types/infra-kubernetes_pod/tests/k8s-ksm-via-opentelemetry-prometheus-receiver.json

- Added `k8s.deploymentName` tag to pod and container entity types

feat: Add deploymentName tag to pod and container

---

entity-types/uninstrumented-kubernetescluster/definition.yml
relationships/candidates/KUBERNETESCLUSTER.yml

Create a k8s unistrumented entity and the candidate relationship.

k8s unistrumented cluster and candidate relationship

---

relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml

Created a relationship definition file to define relationship between Otel Service and AWS MSK Topic (Produce and Consume)

Relationship definition for Otel service and AWS MSK Topic

---

relationships/synthesis/EXT_INFRA-DOCKER_CONTAINER-to-EXT-SERVICE.yml

- EXT Infra docker container to EXT service relationship fix

fix: Docker-ext-infra-relationship-fix

---

relationships/synthesis/EXT-SERVICE-to-INFRA-MQBROKER.yml

…ing to opentelemetry
changed origins of relationsship synthesis data from distributed tracing

changed origins of relationsship synthesis data from distributed tracing

---

relationships/synthesis/EXT-SERVICE-to-INFRA-MQBROKER.yml

quickfix: add potential origin just in case

---

entity-types/uninstrumented-host/definition.yml

Move UNINSTRUMENTED-HOST expiration to daily to facilitate data analysis.

Move UNINSTRUMENTED-HOST expiration to daily

---

entity-types/infra-awsvpcvpntunnel/golden_metrics.yml

Update code to use correct aggregator for tunnel state golden metrics

NR-264231 - FixVPCVPNIssue golden metrics for tunnel state

---

entity-types/synth-secure_cred/definition.yml

Going forward Synthetics secure credentials will no longer use a ttl and will instead use manual indexing.

chore: update synthetics secure cred indexing

---

entity-types/ext-service/definition.yml

EXT-SERVICE Update `instrumentation.provider` from `nr_ebpf_agent` to `nr_ebpf`

---

entity-types/tvs-screendevice/tests/Metric.json

Adding a test to the entity synthesis rule

add tests to TVS-screendevice Entity

---

entity-types/ext-cox_generic/dashboard.json
entity-types/ext-cox_generic/definition.yml
entity-types/ext-cox_generic/summary_metrics.yml
entity-types/ext-cox_generic/tests/Metric.json

Add generic device definition for Cox

feat: add cox_generic entity definition

---

relationships/candidates/CONTAINER.yml

Reverts newrelic/entity-definitions#1721

Revert "feat: Add a new lookup in for the CONTAINER candidate relationship definition"

---

entity-types/iast-scan-instance/definition.yml
entity-types/iast-scan_instance/definition.yml

New entity definition for IAST scan instance

New definition for IAST scan instance entity

---

docs/relationships/candidate_relationships.md

Update candidate_relationships.md w/ tags case sensitivity info.

Update candidate_relationships.md w/ tags case sensitivity info

---

relationships/synthesis/APM-APPLICATION-to-INFRA-LAMBDAFUNCTION.yml

Added a regex for Lambda function

Added a regex for Lambda function

---

entity-types/nr1-workitem/definition.yml

**Description** 
WorkItem is a lightweight ticket representing an action to be taken by the customer. WorkItems can sync with the customer’s ticketing system and serve as input to workflows.

feat(WorkItem): New definition for WorkItem entity

---

entity-types/nr1-scheduled_reports/definition.yml

**Relevant information**
**Description**
Scheduled-reports is a capability where we can configure recurring emails with PDFs of our dashboards.

feat(NR-308177): New definition for scheduled reports entity

---

entity-types/ext-onboarding_app/definition.yml

New temporal entity type to be used during the onboarding exercise in Entity Platform.
The entity type is going to be tested only in staging and reverted before doing the production release.

feat: Temp onboarding entity type

---

entity-types/nr1-workitem/summary_metrics.yml

Adding summary metrics to Workitem entity by using tags as input to them

Add summary_metrics

---

validator/tools/validate_relationship_synthesis_rules.js

* Fix the Synthesis rules validator unique name

Fix the unique validator for the Synthesis rules

---

relationships/synthesis/INFRA_KUBERNETES_CONTAINER-to-EXT_SERVICE.yml

add new origin for an existing rule

add origin for rule

---

entity-types/ngep-collection/definition.yml

Added the new collection NGEP entity type.

Add collection NGEP entity type

---

entity-types/ngep-fleet/definition.yml
entity-types/ngep-scorecard/definition.yml
entity-types/ngep-scorecard_rule/definition.yml

add two new scorecard entities using NGEP.

feat: add scorecard entities

---

entity-types/autoflows-workflow/definition.yml

Relevant information
Add two new workflow entity for Autoflows.
Checklist

feat: Add autfolows entities

---

relationships/candidates/CONTAINER.yml

Reverts newrelic/entity-definitions#1763

Revert "feat: Add new lookup defining container candidate relationship"

---

entity-types/infra-host/definition.yml
entity-types/infra-host/tests/Metric.json

update identifier as k8s.nodes for k8s-otel-collector

---

entity-types/ngep-application_settings/definition.yml

Description: This PR introduces a new entity type within the NGEP domain, specifically for Application Settings (APPLICATION_SETTINGS). The addition of this entity type allows us to store and manage configuration settings related to application performance monitoring, such as the Apdex Target (ApdexT) for OTel entities.
Key Configuration Details:
entityExpirationTime: MANUAL ensures that entities of this type do not expire automatically and require manual intervention for deletion.
alertable: true enables alerting features for this entity type, allowing users to set up alerts based on the configuration settings of their applications.

feat: Adding NGEP domain for app settings

---

entity-types/media_streaming-video/golden_metrics.yml
entity-types/media_streaming-video/summary_metrics.yml

Add Golden Metrics and Summary metrics to Media Streaming Entity

Add Golden and Summary metrics for Media Streaming

---

entity-types/ext-onboarding_application/definition.yml

Temporal entity type for the onboarding exercise in Entity Platform.
This will be only deployed in Staging and reverted after the exercise is complete.

feat: Add temporal EXT-OnboardingApplication entity

---

entity-types/ngep-security_finding/definition.yml

Create definition for new NGEP entity type 'SECURITY_FINDING'

Create definition for NGEP SecurityFinding

---

entity-types/ext-fluentbit/definition.yml

feat: add ref to dashboard json in definition

---

entity-types/ext-onboarding_application/definition.yml

Reverts newrelic/entity-definitions#1806

Revert "feat: Add temporal EXT-OnboardingApplication entity"

---

entity-types/autoflows-workflow/dashboard.json
entity-types/autoflows-workflow/definition.yml

This PR adds dashboard configuration for autoflows-workflow

Adding Dashboard for autoflows-workflow

---

relationships/synthesis/INFRA-KUBERNETES_DAEMONSET-to-EXT-FLUENTBIT_KUBERNETES.yml

This PR attempts to fix the issue of synthesis of relationship by properly identifying GUID of source and target entities.

fix: added extractGuid to source entity in relationship

---

entity-types/ext-fluentbit_kubernetes/summary_metrics.yml

feat: added summary metrics

---

entity-types/infra-aws_mediaconnect_flow/definition.yml
entity-types/infra-aws_mediaconnect_flow/golden_metrics.yml
entity-types/infra-aws_mediaconnect_flow/summary_metrics.yml
entity-types/infra-aws_mediaconnect_output/definition.yml
entity-types/infra-aws_mediaconnect_output/golden_metrics.yml
entity-types/infra-aws_mediaconnect_output/summary_metrics.yml
entity-types/infra-aws_mediaconnect_source/definition.yml
entity-types/infra-aws_mediaconnect_source/golden_metrics.yml
entity-types/infra-aws_mediaconnect_source/summary_metrics.yml
entity-types/infra-aws_medialive_channel/definition.yml
entity-types/infra-aws_medialive_channel/golden_metrics.yml
entity-types/infra-aws_medialive_channel/summary_metrics.yml
entity-types/infra-aws_mediapackage_live_egress/definition.yml
entity-types/infra-aws_mediapackage_live_egress/golden_metrics.yml
entity-types/infra-aws_mediapackage_live_egress/summary_metrics.yml
entity-types/infra-aws_mediapackage_live_ingest/definition.yml
entity-types/infra-aws_mediapackage_live_ingest/golden_metrics.yml
entity-types/infra-aws_mediapackage_live_ingest/summary_metrics.yml

Added relevant definition and summary/metric files for AWS elemental entities. Synthesis rules etc on internal github.

Add AWS elemental definitions and summary/golden metrics

---

relationships/candidates/KUBERNETESCLUSTER.yml

Updating the K8S candidate rule to match on lowercase displayname tag.
* [n/a] The value of the attribute marked as `identifier` will be unique and valid. 
* [n/a] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

Updating the K8S candidate rule to match on lowercase displayname tag.

---

entity-types/uninstrumented-awsappsyncapi/definition.yml
entity-types/uninstrumented-awsec2/definition.yml
entity-types/uninstrumented-awselasticsearchcluster/definition.yml
entity-types/uninstrumented-awskinesisdeliverystream/definition.yml
entity-types/uninstrumented-awskinesisstream/definition.yml
entity-types/uninstrumented-awsredshiftcluster/definition.yml
entity-types/uninstrumented-ebpfclient/definition.yml
entity-types/uninstrumented-ebpfserver/definition.yml

* Add the missing uninstrumented entities.

Add the missing uninstrumented entities

---

relationships/candidates/KUBERNETESCLUSTER.yml

Another attempt at resolving issues with k8s candidate relationships

Another attempt at resolving issues with k8s candidate relationships

---

relationships/synthesis/VIDEO-ACTION-to-ROKU-VIDEO.yml

feat: Add relationship for roku synthesis for videoaction event type

---

entity-types/ext-fluentbit_kubernetes/dashboard.json

fix: updated FB k8s dasboard

---

entity-types/ngep-git_repository/definition.yml

Entity definition for git repository entity

---

relationships/candidates/CONTAINER.yml

Adds back https://github.com/newrelic/entity-definitions/pull/1763

feat: Add new lookup defining container candidate relationship

---

relationships/synthesis/MOBILE-APPLICATION-to-VIDEO-ACTION.yml
relationships/synthesis/ROKU-VIDEO-to-VIDEO-ACTION.yml

feat(media-streaming): Update definition for roku, add for mobile (video action)

---

entity-types/infra-awselasticachevalkeycluster/definition.yml
entity-types/infra-awselasticachevalkeycluster/golden_metrics.yml
entity-types/infra-awselasticachevalkeycluster/summary_metrics.yml
entity-types/infra-awselasticachevalkeynode/definition.yml
entity-types/infra-awselasticachevalkeynode/golden_metrics.yml
entity-types/infra-awselasticachevalkeynode/summary_metrics.yml

To add support for valkey integration with AWS ElasticCache, new entity definitions required.

added valkey node and cluster support

---

relationships/candidates/KAFKATOPIC_EXPLICIT.yml
relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml

Add relationship to support otel service to msk topic using arn.

Add support for kafka manual instrumentation

---

relationships/candidates/AWSELASTICSEARCHCLUSTER_EXPLICIT.yml
relationships/synthesis/EXT-SERVICE-to-INFRA-AWSELASTICSEARCHCLUSTER.yml

Updated elasticsearch explicit relationship

feat: Updated elasticsearch explicit relationship

---

entity-types/video-connected_device_system/dashboard.json
entity-types/video-connected_device_system/definition.yml
entity-types/video-connected_device_system/golden_metrics.yml
entity-types/video-connected_device_system/summary_metrics.yml
entity-types/video-roku_system/dashboard.json
entity-types/video-roku_system/definition.yml
entity-types/video-roku_system/golden_metrics.yml

Add ConnectedSystemDevice eventType along with RokuSystem for the Entity

Nr 372109 Add Connected System Device to Roku entity

---

relationships/synthesis/EXT-SERVICE-to-INFRA-AWSMQBROKER.yml
relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
relationships/synthesis/EXT-SERVICE-to-MEMCACHED.yml

Remove present true condition when regex is present

Remove present true condition when regex is present

---

relationships/candidates/AWSELASTICSEARCHCLUSTER_EXPLICIT.yml
relationships/candidates/AWSMQBROKER_EXPLICIT.yml
relationships/candidates/KAFKATOPIC_EXPLICIT.yml
relationships/candidates/MEMCACHED_EXPLICIT.yml
relationships/candidates/REDIS_EXPLICIT.yml
relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
relationships/synthesis/EXT-SERVICE-to-MEMCACHED.yml

Update regex for ARN in _Explicit relationships

Update regex for ARN in _Explicit relationships

---

relationships/candidates/AWSELASTICSEARCHCLUSTER_EXPLICIT.yml
relationships/candidates/AWSMQBROKER_EXPLICIT.yml
relationships/candidates/KAFKATOPIC_EXPLICIT.yml
relationships/candidates/MEMCACHED_EXPLICIT.yml
relationships/candidates/REDIS_EXPLICIT.yml

Add No Op on miss in manual instrumentation

Add No Op on miss in manual instrumentation

---

relationships/synthesis/EXT-SERVICE-to-REDIS.yml

Updated the regex, so that it can be accepting the replication group arn of redis

feat: Adding replication group regex for redis

---

entity-types/media_streaming-video/golden_metrics.yml
entity-types/media_streaming-video/summary_metrics.yml

fix: Update golden metrics for Media Streaming

---

entity-types/infra-kubernetes_pod/definition.yml

Debugging I found out synthesis does not work because of this typo!

Typo in domain id

---

entity-types/infra-awslambdafunction/golden_metrics.yml
entity-types/infra-awslambdafunction/summary_metrics.yml

Ticket: https://new-relic.atlassian.net/browse/NR-376830
In an effort to enhance our monitoring capabilities, we have introduced summary and golden metrics to help identify whether Lambda functions are connected with APM for Lambda entities. This update aims to provide clearer insights into the instrumentation status and APM association of Lambda functions, allowing for more effective performance tracking.

feat: Added summary and golden metrics for lambda entities

---

entity-types/infra-awslambdafunction/golden_metrics.yml
entity-types/infra-awslambdafunction/summary_metrics.yml

Reverts newrelic/entity-definitions#1954

Revert "feat: Added summary and golden metrics for lambda entities"

---

relationships/candidates/HTTPSERVICE.yml

Fixing multiple matches for candidate entities with same endpoint tag.

DISCARD_ALL on multiple matches for candidates

---

entity-types/infra-container/golden_metrics.yml

* include windows specific metric for memory bytes
Windows metric name for memory bytes is different than linux. So, if linux one is not available, we choose the windows one from the same source.

feat(nri-docker): update golden metrics for nri-docker

---

entity-types/workflowauto-workflow_automation/dashboard.json

Updating Dashboard.json for workflow automation

Updating Dashboard.json for workflow automation

---

relationships/synthesis/EXT-AWS_LAMBDA_LOG_FORWARDER-to-INFRA-AWSLAMBDAFUNCTION.yml

This PR attempts to create a relationship between AWS lambda log forwarder entity and AWS lambda function entity. At the moment, we want to test this out in staging.

[NR-386021] Added is-a relationship from AWS lambda log forwarder to AWS lambda function

---

entity-types/ngep-github_connection/definition.yml
entity-types/ngep-jira_connection/definition.yml

Entity definitions for Jira and github connection

---

entity-types/ngep-jira_sync_configuration/definition.yml
entity-types/ngep-work_item/definition.yml

Corresponding ticket: https://new-relic.atlassian.net/browse/NR-333648
Approved IDD for Work Item primitive
https://newrelic.atlassian.net/wiki/spaces/GROWTHLIFECYCLE/pages/3742072969/WorkItem+Primitive+IDD

Added schema for Work Item related entities

---

entity-types/ext-service/definition.yml
entity-types/ext-service/tests/Span.json
relationships/candidates/EXTEBPFCLIENT.yml
relationships/candidates/EXTEBPFSERVER.yml
relationships/synthesis/EXT-SERVICE-to-EXT-SERVICE.yml

Changes in the PR:
1. Updated ext-service entity definition for eBPF entity
2. Added new synthesis rule for relationship between two ext eBPF entities
3. Created new candidate relationship for ext eBPF entities
There were already existing eBPF entity types but they are outdated with conditions that never fulfil. 
The team has concluded that we will continue with the ext eBPF entities for now and then move on to new eBPF domain entities later.

Ext ebpf relationships

---

entity-types/infra-awslambdafunction/definition.yml

As part APM Lambda fusion work, I've added a tag related code.

Added a tag code as part of APM Lambda fusion work

---

entity-types/uninstrumented-azureservicebusnamespace/definition.yml
relationships/candidates/AZURESERVICEBUSNAMESPACE.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-AZURESERVICEBUSNAMESPACE.yml

Added relationship files for APM and Azure Service Bus Namespace.

Added relationship files for APM and Azure Service Bus Namespace.

---

entity-types/ngep-budget/definition.yml

feat: Adding Budget entity.

---

entity-types/infra-container/definition.yml
entity-types/infra-kubernetes_cronjob/definition.yml
entity-types/infra-kubernetes_daemonset/definition.yml
entity-types/infra-kubernetes_deployment/definition.yml
entity-types/infra-kubernetes_job/definition.yml
entity-types/infra-kubernetes_persistentvolume/definition.yml
entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
entity-types/infra-kubernetes_pod/definition.yml
entity-types/infra-kubernetes_statefulset/definition.yml
entity-types/infra-kubernetescluster/definition.yml

add TTL for tags that can change value

---

entity-types/infra-gcpexternalloadbalancer/definition.yml
entity-types/infra-gcpexternalloadbalancer/golden_metrics.yml
entity-types/infra-gcpexternalloadbalancer/summary_metrics.yml
entity-types/infra-gcphttpexternalregionalloadbalancer/definition.yml
entity-types/infra-gcphttpexternalregionalloadbalancer/golden_metrics.yml
entity-types/infra-gcphttpexternalregionalloadbalancer/summary_metrics.yml
entity-types/infra-gcphttploadbalancer/golden_metrics.yml
entity-types/infra-gcphttploadbalancer/summary_metrics.yml
entity-types/infra-gcpinternalhttploadbalancer/definition.yml
entity-types/infra-gcpinternalhttploadbalancer/golden_metrics.yml
entity-types/infra-gcpinternalhttploadbalancer/summary_metrics.yml
entity-types/infra-gcptcpsslproxyloadbalancer/golden_metrics.yml
entity-types/infra-gcptcpsslproxyloadbalancer/summary_metrics.yml

GcpHttpExternalRegionalLoadBalancer, GcpInternalHttpLoadBalancer, GcpExternalLoadBalancer entities(along with Golden & Summary metrics) are added. For GcpTcpSslProxyLoadBalancer, Golden & Summary metrics are added.

NR-421295 -> new entity definitions, golden & summary metrics are added

---

entity-types/ext-performance_inbox_setting/definition.yml

In this PR I am creating a new entity. I have already created an entity in the new NGEP, which can be referred [here](https://source.datanerd.us/entity-platform/ep-next-gen-api/blob/c356201236640c4e3963ea5edc03dbb135f534dd/ep-next-gen-parser/src/main/resources/entityTypes/inbox.graphql#L71). I am also creating an here, as it is mentioned as an required step.

Add EXT-PERFORMANCE_INBOX_SETTING entity definition

---

entity-types/infra-mssqlinstance/definition.yml

add entityKey as tag for INFRA-MSSQLINSTANCE

add entityKey as tag for INFRA-MSSQLINSTANCE

---

entity-types/ebpf-service/golden_metrics.yml
entity-types/ebpf-service/summary_metrics.yml
entity-types/ext-service/definition.yml

Add check in eBPF rules to remove conflict.
Removing conflicts between new ebpf-service and ext-service entity definitions
Also added summary & golden metrics for the entity

fix: Update in eBPF rules to make them exclusive

---

relationships/candidates/KUBERNETES_DEPLOYMENT.yml
relationships/synthesis/INFRA-KUBERNETES_DEPLOYMENT-to-INFRA-KUBERNETES_POD.yml

Reverts newrelic/entity-definitions#2077

Revert "Update Deployment relationship to reflect the Deployment attribute fi…"

---

entity-types/infra-kubernetes_cronjob/definition.yml
entity-types/infra-kubernetes_daemonset/definition.yml
entity-types/infra-kubernetes_deployment/definition.yml
entity-types/infra-kubernetes_job/definition.yml
entity-types/infra-kubernetes_persistentvolume/definition.yml
entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
entity-types/infra-kubernetes_pod/definition.yml
entity-types/infra-kubernetes_statefulset/definition.yml
entity-types/infra-kubernetescluster/definition.yml

Reverts newrelic/entity-definitions#2105

Revert "updated entity name for kubernetes entity definitions"

---

entity-types/ngep-maintenance_window/definition.yml

Adding new maintenance window entity under NGEP domain

feat: Add maintenance window entity

---

entity-types/infra-oracledbinstance/definition.stg.yml
entity-types/infra-oracledbinstance/golden_metrics.stg.yml
entity-types/infra-oracledbinstance/opentelemetry_dashboard.stg.json
entity-types/infra-oracledbinstance/summary_metrics.stg.yml

feat: oracle db entity creation rules for otel

---

relationships/synthesis/APM-APPLICATION-to-INFRA-LAMBDAFUNCTION.yml

Add entitlements to apm to lambdafunction relationship.

[NR-435124] Add entitlements to apm to lambdafunction relationship

---

entity-types/infra-ocicontainerinstance/definition.yml
entity-types/infra-ocicontainerinstance/golden_metrics.yml
entity-types/infra-ocicontainerinstance/summary_metrics.yml
entity-types/infra-ocicontainerinstance/tests/Metric.json
entity-types/infra-ociinstancepool/definition.yml
entity-types/infra-ociinstancepool/golden_metrics.yml
entity-types/infra-ociinstancepool/summary_metrics.yml
entity-types/infra-ociinstancepool/tests/Metric.json
entity-types/infra-ocinlb/definition.yml
entity-types/infra-ocinlb/golden_metrics.yml
entity-types/infra-ocinlb/summary_metrics.yml
entity-types/infra-ocinlb/tests/Metric.json
entity-types/infra-ociqueue/definition.yml
entity-types/infra-ociqueue/golden_metrics.yml
entity-types/infra-ociqueue/summary_metrics.yml
entity-types/infra-ociqueue/tests/Metric.json
entity-types/infra-ocistreaming/definition.yml
entity-types/infra-ocistreaming/golden_metrics.yml
entity-types/infra-ocistreaming/summary_metrics.yml
entity-types/infra-ocistreaming/tests/Metric.json

Add entity definitions for Network Load Balancer, Queue, Streaming, Container Instance
LINK: https://new-relic.atlassian.net/browse/NR-447024
Checklist
I've read the guidelines and understand the acceptance criteria.
The value of the attribute marked as identifier will be unique and valid.
I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

chore(oci): Add entity definitions for Network Load Balancer, Queue, Streaming, Container Instance 

---

entity-types/ext-digitalordering/dashboard.json
entity-types/ext-digitalordering/golden_metrics.yml
entity-types/ext-digitalordering/summary_metrics.yml

update golden metrics

---

entity-types/agent-infraagent/definition.yml
entity-types/infra-kafkacluster/definition.stg.yml
entity-types/infra-mongodb_instance/definition.stg.yml
entity-types/infra-mssqlinstance/definition.stg.yml
entity-types/infra-mysqlnode/definition.stg.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-AZURECOSMOSDBDATABASE.yml
relationships/synthesis/APM-APPLICATION-to-INFRA-AZURESQLDATABASE.yml

Validate that the job is triggering as expected and fix any definition that triggers it

Fix invalid definitions

---

entity-types/ext-argocd/dashboard.json
entity-types/ext-calico/dashboard.stg.json
entity-types/ext-keda/dashboard.stg.json
entity-types/ext-nginx_ingress_controller/dashboard.stg.json
entity-types/ext-prometheus_server/dashboard.stg.json

Updating the layout and queries for some k8s dashboards (KEDA, Calico, NGINX Ingress, Prometheus Server).

fix: Update some k8s dashboards

---

entity-types/infra-nginxserver/definition.stg.yml
entity-types/infra-nginxserver/golden_metrics.stg.yml
entity-types/infra-nginxserver/newrelic_dashboard.stg.json
entity-types/infra-nginxserver/opentelemetry_dashboard.stg.json
entity-types/infra-nginxserver/tests/Metric.stg.json

feat(nginx): add synthesis rules for otel nginx telemetry ingest

---

entity-types/ngep-work_item_link/definition.yml

Added a new WorkItemLink entity. This is going to be used as a CollectionEntity in an existing WorkItem entity.

Added Work Item Link entity

---

relationships/synthesis/APM-APPLICATION-to-INFRA-MONGODB.stg.yml

**Description:** Created a new entity relationship for MongoDB, linking APM to INFRA MongoDB.

MongoDB: Added new relationship between APM and INFRA MongoDB.

---

entity-types/ngep-component/definition.yml
entity-types/ngep-customer_impact/definition.yml
entity-types/ngep-customer_impact_query/definition.yml
entity-types/ngep-status_page_incident/definition.yml

add 4 new cssp entities using NGEP

feat: add cssp entities

---

entity-types/infra-kafkabroker/definition.stg.yml
entity-types/infra-kafkabroker/opentelemetry_dashboard.stg.json
entity-types/infra-kafkatopic/opentelemetry_dashboard.stg.json

Test Results:
1. In_Sync_Replicas
2. bytes_out
3. retry_rate

fix: topic dashboard queries

---

validator/schemas/entity-schema-v1.json

NR-455273: Add ownership to entity schema

---

entity-types/infra-elasticsearchcluster/definition.stg.yml

Update cluster identifier to fix no cluster entity creation issue in staging

fix(elasticsearch-cluster): Update cluster identifier to fix no cluster entity creation issue in staging

---

relationships/candidates/DATABASE.yml

Removing AZURESQLDATABASE from DATABASE candidate file as AZURESQLDATABASE candidate file already exists.

feat: Removing AZURESQLDATABASE from DATABASE candidate file

---

entity-types/ext-argocd/dashboard.json
entity-types/ext-argocd/definition.yml
entity-types/ext-calico/dashboard.json
entity-types/ext-calico/definition.yml
entity-types/ext-coredns/definition.yml
entity-types/ext-envoy/definition.yml
entity-types/ext-envoy/tests/Metric.json
entity-types/ext-istio_ingress/dashboard.json
entity-types/ext-istio_service/definition.yml
entity-types/ext-keda/dashboard.json
entity-types/ext-keda/definition.yml
entity-types/ext-nginx_ingress_controller/dashboard.json
entity-types/ext-nginx_ingress_controller/definition.yml
entity-types/ext-prometheus_server/dashboard.json
entity-types/ext-prometheus_server/definition.yml

Fixes to the prometheus entity dashboards and synthesis rules.

fix: Fix prometheus dashboard queries and synthesis rules

---

entity-types/ext-coredns/dashboard.json

fix: Fix coredns query

---

entity-types/ext-prometheus_server/definition.yml

fix: Remove pod from prometheus_server

---

entity-types/ext-nginx_ingress_controller/definition.yml
entity-types/ext-nginx_ingress_controller/opentelemetry_dashboard.json

Fixed layout and removed widget with deprecated metric name

fix: Update nginx ingress dashboard

---

entity-types/ext-keda/dashboard.json
entity-types/ext-keda/golden_metrics.yml
entity-types/ext-keda/opentelemetry_dashboard.json

fix: Clean up keda definition

---

entity-types/ext-istio_service/dashboard.json
entity-types/ext-istio_service/opentelemetry_dashboard.json

fix: Fix istio queries

---

entity-types/ext-istio_service/opentelemetry_dashboard.json

Update percentile to histogram in istio open telelemtry dash

fix: Update percentile to histogram in istio open telelemtry dash

---

validator/tools/utils.js
validator/tools/validate_folders.js
validator/tools/validate_rules.js

- Ensure all references to dashboard files do exist
- Ensure PROD definition files cannot reference STG override dashboard files
- Ensure definitions only present in STG do not contain any PROD definition files

NR-472461: fix stg override validations
