- README.md
I've added Workloads as an example of experience where entity types are essential, in particular for customers to see the golden metrics and the status surfaced on the Workloads UI. 
I haven't followed the checklist strictly, because I'm proposing a minor change in the README.md file.
> Mention workloads in the README

- README.md
- definitions/infra-etcd_cluster/definition.yml
- definitions/infra-kubernetes_apiserver/definition.yml
- docs/example-entity-definition.yml
- validator/schemas/entity-schema-v1.json
- validator/tools/utils.js
- validator/tools/validate_uniqueness.js
Updated the entity definition schema so that we can start composite metrics for entities that will not be synthesized from this repository. 
> Update definition schema to allow non-synthesizable entities

- .github/CODEOWNERS
- .github/pull_request_template.md
Based on feedback, remove last step on PR checklist `I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.`
Add codeowners. Maybe I should take out @gvassallo since he's actively working on other things, but I rather you choose.
> Github workflow improvements

- definitions/infra-etcd_cluster/definition.yml
- definitions/infra-kubernetes_apiserver/definition.yml
- docs/example-entity-definition.yml
- validator/schemas/entity-schema-v1.json
In a previous schema iteration, we moved everything except for the domain and type into the synthesis section, but non-synthesizable entities also have composite metrics and golden tags and they are not really part of the synthesis.
> Take the composite metrics and golden tags out of the synthesis section

- definitions/infra-kubernetes_apiserver/definition.yml
The domainId of kubernetes_apiserver is too long so the entity GUIDs break the spec size limit
> Set encodeIdentifierInGUID in kubernetes_apiserver

- docs/golden_metrics.md
- validator/schemas/golden-metrics-schema-v1.json
Make the golden metrics key have a valid format.
The format decided is: a-z A-Z 0-9 _ and from 1 character until 100.
All current definitions are ok with this validator so no further changes are required! \o/
> Validate golden metrics keys contain valid characters

- definitions/infra-win_service/definition.yml
- definitions/infra-win_service/summary_metrics.yml
This PR adds a new entity type for the nri-winservice integration. Since we had to change the entity type format (camelCase -> SNAKE_CASE) we decided to create new entities and nerdlets in NR1. 
Once all customers from private beta are migrated to the new release that will use this definition the [old definition](https://github.com/newrelic-experimental/entity-synthesis-definitions/tree/main/definitions/infra-windowsservice) sill became obsolete and could be removed. 
> feat: Add infra-win_service

- definitions/ext-browser_app/definition.yml
- definitions/ext-host/definition.yml
- definitions/ext-mobile_app/definition.yml
- definitions/ext-service/definition.yml
Added the missing synthesis rules for EXT-BROWSER_APP, EXT-MOBILE_APP, EXT-SERVICE and INFRA-HOST. Still didn't add the rules for containers since there's still a discussion about the approach (and it'll be a breaking change).
> Add missing synthesis rules for entity types

- definitions/ext-browser_app/definition.yml
- definitions/ext-host/definition.yml
- definitions/ext-mobile_app/definition.yml
- definitions/ext-service/definition.yml
These types had synthesis rules, but no conditions!
> Missing conditions in EXT- rules

- definitions/infra-container/definition.yml
* Missing aliasing one tag (docker.state should create container.state).
We have to add this feature to the config files.
* Missing defining a second set of rules for Kubernetes containers,
which needs adding the multiple-telemetry support feature to these
files.
This will however allow us to start seeing some synthesized containers.
> Add synthesis rules for INFRA-CONTAINER

- README.md
- docs/example-entity-definition.yml
- validator/schemas/entity-schema-v1.json
Added an optional TTL configuration section, replacing indexStrategy for deletionStrategy, since I think that it's easier to understand. We can also default the deletionFrequency based on the deletionStrategy, so I modified that as well. 
If we do want to keep our original naming convention I can just revert the second commit, so just let me know what you think.
> Add expiration configuration

- definitions/infra-gcpcloudfunction/definition.yml
- definitions/infra-gcpcloudfunction/summary_metrics.yml
Another poor entity type that we missed to migrate its summary metrics.
> Add summary metrics for GCP Cloud Function

- definitions/apm-application/golden_metrics.yml
Changing the order of the applications metrics to align with the service summary page.
> Changing the order of application metrics

- definitions/infra-gcpcloudfunction/summary_metrics.yml
This option should not be used in general. But when used the value is DOMAIN_IDS or ENTITY_GUIDS
> remove invalid options

- definitions/ext-redis/definition.yml
Since we're using the cluster name as domainId, the full GUID tends to
exceed the max size.  Use the encoding option to avoid this.
> Encode EXT-REDIS identifier

- definitions/apm-application/golden_metrics.yml
Use `AS ...` to specify a more human readable title for golden metrics (currently showing up as "Binop" and "newrelic.timeslice.value" in chart legends)
> Add titles to golden metrics

- definitions/infra-awss3bucket/definition.yml
- definitions/infra-awss3bucket/golden_metrics.yml
- definitions/infra-awssnstopic/definition.yml
- definitions/infra-awssqsqueue/definition.yml
- definitions/infra-awssqsqueue/golden_metrics.yml
I've done some small tweaks on the definition of the three mentioned entity types. 
- Added awsRegion as golden tag to the three
- Reviewed S3 golden metrics to align them better with summary metrics
- Caption changes on SQS
> Review definition, golden and summary metrics for AWS SQS, SNS and S3

- README.md
- definitions/ext-fastly_pop/definition.yml
- definitions/ext-redis/definition.yml
- definitions/ext-tinyproxy/definition.yml
- definitions/infra-container/definition.yml
- definitions/infra-etcd_cluster/definition.yml
- definitions/infra-kubernetes_apiserver/definition.yml
- docs/example-entity-definition.yml
- validator/schemas/entity-schema-v1.json
In future we will need to add behavior to the tags. For example single value tags as this PR introduces. Aliases for tags, etc..
In order to do that we need to allow a broad configuration to the tags instead of just a simple string.
> Tags definitions are now a map instead of a list

- definitions/infra-awsnlbtargetgroup/golden_metrics.yml
Removed extraneous open paren (`(`).
> fix: Removed extraneous open paren

- definitions/infra-awskinesisdeliverystream/golden_metrics.yml
Added missing open paren in the select clause of `infra.awskinesisdeliverystream.getRecordsThroughput` and `infra.awskinesisdeliverystream.getThroughput`  
Added missing `(`
> fix: Added missing open parens

- definitions/infra-awsnlb/golden_metrics.yml
There is one too many open paren's in the select clause.
Deleted extraneous `(`
> fix: Fix typo in infra.awsnlb.failedClientNlbTlsHandshakes

- definitions/mobile-application/summary_metrics.yml
Changed Newtwork failure rate to Network failure rate
Just a simple spelling error fix
These seem mostly irrelevant for a spell check
> Metric name Spell Check

- README.md
- definitions/infra-container/definition.yml
- docs/example-entity-definition.yml
- validator/schemas/entity-schema-v1.json
Add entityTagName configuration to tags so that users can specify their desired tag key. If not specified we use the default (the attribute name)
> Add entityTagName configuration to tags

- definitions/ext-router/definition.yml
- definitions/ext-router/golden_metrics.yml
- definitions/ext-router/summary_metrics.yml
adding `ROUTER` entity for the `EXT` domain. Original definition is based on network device metrics sent via Kentik technical partnership, but this definition is being kept ambiguous to allow for other technical partnerships to use the entity in the future.
`ROUTER` relates to any L3 device in the networking space that has the capability to route packets based on defined protocols. This entity can also be decorated with Flow telemetry (NetFlow/sFlow/jFlow/IPFIX/etc), among other things. 
> adding ext-router entity definition and metrics

- definitions/ext-switch/definition.yml
- definitions/ext-switch/golden_metrics.yml
- definitions/ext-switch/summary_metrics.yml
- definitions/mobile-application/summary_metrics.yml
adding `SWITCH` entity for the `EXT` domain. Original definition is based on network device metrics sent via Kentik technical partnership, but this definition is being kept ambiguous to allow for other technical partnerships to use the entity in the future.
`SWITCH` relates to any L2 device in the networking space that lacks the capability to route packets.
> adding ext-switch entity definition and metrics

- validator/schemas/golden-metrics-schema-v1.json
Enforce maximum of 10 GM per definition file
For SM we 'recommend' a max of 10, so it cannot be enforced on the schema.
Btw, I checked and we are indeed validating correctly that we only receive 1 and only 1 condition here @srvaroa.
> Enforce maximum of 10 GM per definition file

- definitions/infra-container/golden_metrics.yml
`memoryUtilization` is not the correct metric to monitor, we should be monitoring `memoryWorkingSetBytes` instead. This because `memoryUtilization` includes filesystem caching and memory that could be reclaimed, so it isn't a true indicator for OOM prevention.
> Use the correct metric for K8s container mem usage

- definitions/infra-kubernetespod/definition.yml
This adds support for indexing Kubernetes Pods as entities. 
> Add definition and synthesis rule for KUBERNETES_POD

- definitions/infra-awsrdsdbcluster/summary_metrics.yml
- definitions/infra-awsrdsdbinstance/summary_metrics.yml
Added the provider filter to RDS entities. We're seeing shimming errors and we believe it might be because of this missing filter.
> Fix: add provider filter for RDS

- definitions/ext-host/definition.yml
This is a legacy type that was adde in the original version of synthesis
but is proving problematic as the matching rule is too broad (anything
with a `host` attribute will match).  We're disabling this for now,
although the type is respected.
> Remove synthesis from EXT-HOST

- definitions/infra-vspherecluster/summary_metrics.yml
- definitions/infra-vspheredatacenter/summary_metrics.yml
- definitions/infra-vspheredatastore/summary_metrics.yml
- definitions/infra-vspherehost/golden_metrics.yml
- definitions/infra-vspherehost/summary_metrics.yml
- definitions/infra-vsphereresourcepool/summary_metrics.yml
- definitions/infra-vspherevm/summary_metrics.yml
We don't currently support metrics that return strings.
So remove them for now
> Remove vsphere metrics that return a string value

- definitions/infra-container/definition.yml
- definitions/infra-kubernetespod/definition.yml
Fix the `encodeIdentifierInGUID` setting for Kubernetes pods and containers.
> Fix encodeIdentifierInGUID for Kubernetes pods and containers

- definitions/infra-kubernetes_deployment/definition.yml
- definitions/infra-kubernetes_pod/definition.yml
These tags are considered metrics in the system, so they cannot be tags otherwise things go bad.
> Remove tags that are considered metrics in Kubernetes entities

- validator/schemas/golden-metrics-schema-v1.json
For GMs we were wrongly validating the name of the 'provider' in `queries` against our GM key regex, but the provider doesn't need to have the same restrictions (i.e. no dashes). 
This will fix a [PR that is failing](https://github.com/newrelic-experimental/entity-synthesis-definitions/pull/145) because of the wrong validation.
> Remove GM queries provider validation and add to query instead

- definitions/infra-kubernetes_pod/summary_metrics.yml
1. The pod's summary is getting slightly crowded. We will stop showing network tx and rx metrics there. Network errors stay. 
2. Added the pod's status to the summary metrics
3. Fixed the pod creator name and kind in the pod summary metrics
> Improve and fix the summary for k8s pods

- definitions/ext-service/definition.yml
We want to synthesize ext-service entities from telemetry that contains any of the following attributes:
- service.name
- service_name
- serviceName
> Add multiple synth rules for ext-service

- definitions/ext-unix_host/dashboard.json
- definitions/ext-unix_host/definition.yml
Add a dashboard for EXT-UNIX_HOST based on the GMs defined for the entity. In the old format since we need to have this working today.
> Add dashboard for unix host

- definitions/ext-network_synth/summary_metrics.yml
- definitions/ext-router/summary_metrics.yml
- definitions/ext-switch/summary_metrics.yml
The SM for some EXT entity types were null despite the data being available on the telemetry. Looking into it with @naxhh we saw that the eventId seemed to be wrong and changing it from `entityGuid` to `entity.guid` fixed the queries. 
I saw that some infra entities are also using `entityGuid` but it seems like those SM are working, we might want to take a better look at them, because if we could change them to `entity.guid` we could add a validation to prevent people from using `entityGuid` (there are also many golden metrics using `entityGuid`).
> Fix misconfigured EXT summary metrics

- definitions/infra-kubernetes_daemonset/definition.yml
- definitions/infra-kubernetes_daemonset/golden_metrics.yml
- definitions/infra-kubernetes_daemonset/summary_metrics.yml
Add summary metrics, golden metrics and tags for K8s daemonset entity.
Also remove the `k8s.status` from its synthesis definition since it's not a tag that is available for this entity.
> Add summary metrics, golden metrics and tags for K8s daemonset

- definitions/infra-host/summary_metrics.yml
Migrate the summary metrics definition of the Infra host entity to the new `Metric` syntax.
We're not migrating the golden metrics because the service is not ready for the new format yet.
> Migrate host summary metrics to Metric event type

- definitions/ext-router/definition.yml
We've found that this attribute contains a very wide range IPs, which doesn't seem to be what you'd expect for a router.  E.g. we're seeing the entire space of IPs in various ranges, like 10.1.1.0/24 and others for the same entity.  Our suspicion is that this value is the src_addr of TCP flows / devices that the router may be talking to / have entries in its MAC table, etc.
This is problematic for us as the tag will have a lot of churn (e.g. we're seeing millions of changes per minute for an account with just 250 routers) and cause excessive writes to the entity store (which works under the assumption of storing objects that don't change that often).
We're removing this for now so that we can re-enable the entity type.
Describe what you have done and any details that you think are …
> Remove src_addr from EXT-ROUTER

- README.md
- Explain that we add any attributes prefixed with `tags.` as entity tags.
- Explain that we prefer these entity tags over rule-defined tags in case of collision.
We could also add here the list of reserved tags that only we can use if we want.
> Improve tags documentation

- validator/schemas/summary-metrics-schema-v1.json
I did the same mistake in SM as in GM: https://github.com/newrelic-experimental/entity-synthesis-definitions/pull/148
Validating the provider not the query properties. Fix that
> Fix summary validation

- definitions/infra-kubernetes_daemonset/dashboard.json
- definitions/infra-kubernetes_daemonset/definition.yml
- definitions/infra-kubernetes_deployment/dashboard.json
- definitions/infra-kubernetes_deployment/definition.yml
- definitions/infra-kubernetes_pod/dashboard.json
- definitions/infra-kubernetes_pod/definition.yml
- definitions/infra-kubernetes_statefulset/dashboard.json
- definitions/infra-kubernetes_statefulset/definition.yml
Adding dashboard definitions for the following Kubernetes entities:
- Kubernetes pod
- Kubernetes deployment
- Kubernetes daemonset
- Kubernetes statefulset
> Add dashboard templates for multiple K8s entities

- definitions/ext-rf_scanner/definition.yml
THD_RF_TRANSACTION**S** -> THD_RF_TRANSACTION (the correct name of the event)
> Fix event name typo

- definitions/ext-pihole/dashboard.json
During the translation to the new format the widgets for the ext-pihole dashboard became huge, fixing it here.
> Fix widget size in dashboards

- definitions/ext-service/definition.yml
This PR adds Kubernetes tags that are aligned with the Infra Kubernetes tags to the Pixie services.
> Add Kubernetes cluster and namespaces tags for Pixie services.

- definitions/ext-pihole/dashboard.json
- definitions/ext-pihole/definition.yml
I've added a synthesis rule to support prometheus as a data source.
So far in order to create pi-hole entities the `metricAPI` was used adding the attribute `piHoleName` to the metrics being sent to New Relic, so creating the definition file was fairly easy. The Metrics looked like this until now:
```
{
"metricName": "pihole_domains_being_blocked",
"newrelic.source": "metricAPI",
"piHoleName": "foo_bar",
"pihole_domains_being_blocked": {
"type": "gauge",
"count": 1,
"sum": 79808,
"min": 79808,
"max": 79808,
"latest": 79808
},
"timestamp": 1619094002120
},
```
Using the prometheus exporter leads to things that look a bit different:
```
{
"hostname": "host.docker.internal",
"instance": "host.docker.internal:9617",
"instrumentation.name": "remote-write",
"instrumentation.provider": …
```
> Added more synthesis rules for pi-hole entities

- definitions/ext-service/golden_metrics.yml
- definitions/ext-service/summary_metrics.yml
* In the summary metrics, we are not returning a percentage at the moment so the values are 100x too small in the UI.
* In the golden metrics, some cleanup to make it more consistent with the summary metrics.
> Cleaning up golden and summary metrics from Services.

- README.md
- definitions/infra-container/definition.yml
- definitions/infra-kubernetes_pod/definition.yml
- validator/schemas/entity-schema-v1.json
- Add support for FOUR_HOURS entity expiration time
- Change infra-container and infra-k8s_pod expiration time from DAILY to FOUR_HOURS
> Add support for FOUR_HOURS entity expiration time

- definitions/ext-service/golden_metrics.yml
Ext-Service
Update the golden metric queries to make sure the service can determine the data type of the queries. The issues is that count and sum don't have the same data type, so we need to give the service a hint which one to use.
The golden metrics service supports the devision in the format Numerator / Denominator, to comply with the format the * 100 was moved to the numerator.
> Update ext-service golden metrics to automatically determine the data type

- definitions/ext-service/golden_metrics.yml
- definitions/ext-service/summary_metrics.yml
Labels on OpenTelemetry Metrics are string values. Hence the http.status_code label on the Pixie http.server.duration metric is a string. We need to cast to a numerical value in order to calculate the error rate correctly.
> Fix error metrics for Pixie service entities.

- definitions/ext-service/definition.yml
This PR stamps an entity guid when instrumentation.provider is opentelemetry
> Add instrumentation.provider=opentelemetry to ext-service definitions.

- definitions/ext-service/definition.yml
Restoring an original rule that matched based on the pressence of the
attribute.  Added a warning to note that this rule matches too broadly
in some instrumentation sources, and we're ignoring in certain ingestion
paths until we add a configuration in rules that allows selecting the
right ingest paths to apply it.
> EXT-SERVICE: match on service.name

- definitions/ext-router/definition.yml
- Add back the correct attribute for kentik rules (`instrumentation.provider` -> `provider`)
- Fix tags for `mikrotik` rules
> Fix EXT-ROUTER definition

- definitions/ext-router/definition.yml
Remove instrumentation provider override for Kentik Router, it was added by mistake ([reported](https://newrelic.slack.com/archives/C01CFRKGPMK/p1622667619119200?thread_ts=1622667288.118400&cid=C01CFRKGPMK))
> Remove instrumentation provider override for Kentik Router

- definitions/synth-private_location/definition.yml
- definitions/synth-private_location/summary_metrics.yml
Adds summary metrics to synthetics private location entity.
> feature: add summary metrics to synth private location

- definitions/infra-awsvpcnetworkinterface/definition.yml
- definitions/infra-awsvpcvpntunnel/definition.yml
It seems there is a misconfiguration from very old domain-types that should be 1 DAY, like rest of INFRA domain-types, this is confirmed by #beyond
Also, AWSVPCNETWORKINTERFACE do have metrics, so it can be potentially alertable.
> Update TTL to 1 day + make VPCNETWORKINTERFACE alertable

- README.md
Document the behaviour for the `instrumentation.provider` attribute as a default tag.
> Add instrumentation provider to default tags

- definitions/ext-firewall/dashboard.json
- definitions/ext-firewall/definition.yml
- definitions/ext-firewall/golden_metrics.yml
- definitions/ext-firewall/summary_metrics.yml
Adding `ext-firewall` entity definition from Kentik SNMP integration using Metrics API. 
**NOTE: This definition would only apply to a single vendor's data (Fortigate); future vendors will need to be added as additional sources much like the `ext-router` definition has today**
> feat: adding ext-firewall entity definition

- definitions/ext-host/definition.yml
- definitions/infra-apacheserver/golden_metrics.yml
- definitions/infra-cassandranode/golden_metrics.yml
- definitions/infra-elasticsearchnode/golden_metrics.yml
- definitions/infra-f5pool/golden_metrics.yml
- definitions/infra-f5poolmember/golden_metrics.yml
- definitions/infra-f5virtualserver/golden_metrics.yml
- definitions/infra-host/golden_metrics.yml
- definitions/infra-kafkabroker/golden_metrics.yml
- definitions/infra-kubernetes_daemonset/golden_metrics.yml
- definitions/infra-kubernetes_deployment/golden_metrics.yml
- definitions/infra-kubernetes_pod/golden_metrics.yml
- definitions/infra-kubernetes_statefulset/golden_metrics.yml
- definitions/infra-mssqlinstance/golden_metrics.yml
- definitions/infra-mysqlnode/golden_metrics.yml
- definitions/infra-nginxserver/golden_metrics.yml
- definitions/infra-oracledbinstance/golden_metrics.yml
- definitions/infra-postgresqlinstance/golden_metrics.yml
- definitions/infra-rabbitmqexchange/golden_metrics.yml
- definitions/infra-rabbitmqnode/golden_metrics.yml
- definitions/infra-rabbitmqqueue/golden_metrics.yml
- definitions/infra-redisinstance/golden_metrics.yml
- definitions/infra-vspherecluster/golden_metrics.yml
- definitions/infra-vspheredatacenter/golden_metrics.yml
- definitions/infra-vspheredatastore/golden_metrics.yml
- definitions/infra-vspherehost/golden_metrics.yml
- definitions/infra-vsphereresourcepool/golden_metrics.yml
- definitions/infra-vspherevm/golden_metrics.yml
This reverts commit `f6362152360bf2ad0d3cced2e98d3a157e1232ae` and `a289bbf5bbbcc6ed1d4da6acd619d58d87d42ccc`. I'll really this last one after this PR is merged 
> Revert ext-host rule and golden metric changes 

- definitions/ext-pdu/dashboard.json
- definitions/ext-pdu/definition.yml
- definitions/ext-pdu/golden_metrics.yml
- definitions/ext-pdu/summary_metrics.yml
adding definition for power distribution unit (pdu) devices from kentik partnership metrics
> feat: adding ext-pdu entity definition

- definitions/ext-nas/definition.yml
- definitions/ext-nas/golden_metrics.yml
- definitions/ext-nas/readynas-dashboard.json
- definitions/ext-nas/summary_metrics.yml
adding `ext-nas` entity type; tested on Netgear ReadyNAS device
**NOTE: This entity should end up in the `Other entities` section of the Explorer UI**
> feat: adding ext-nas entity for netgear readynas

- docs/summary_metrics.md
Update SM docs to explain that STRING unit is not supported for NRDB queries
> Update SM docs to explain that STRING unit is not supported for NRDB queries

- definitions/infra-container/definition.yml
There are some containers that use the same name (which determines the identifier) but get restarted often.   As the tag is set to multi value, we'll keep accumulating the containerId tag.
> Make containerId single value.

- docs/golden_metrics.md
- docs/summary_metrics.md
Update docs to reflect default behavior of roll-up composite metrics: The first query is selected, not the one with the `newRelic` discriminator. 
> Update docs to reflect default behavior of roll-up composite metrics

- validator/schemas/summary-metrics-schema-v1.json
This ones goes in had with: https://github.com/newrelic/entity-definitions/pull/257
Add the CELSIUS unit into the validator. All the internal work is already done.
> Add CELSIUS unit into the validator

- definitions/ext-ups/summary_metrics.yml
Update Summary Metric definition for `ext-ups` entity to use new metric unit introduced in PR #257 
> chore: updating to new celsius metric unit in SM

- definitions/ext-kentik_default/dashboard.json
- definitions/ext-kentik_default/definition.yml
- definitions/ext-kentik_default/summary_metrics.yml
adding a default entity type for telemetry received from Kentik's ktranslate agent
> feat: adding kentik-default entity type

- definitions/ext-kentik_default/dashboard.json
Updating dashboard for `EXT-Kentik_Default` entity with links to new [snmp-profiles](https://github.com/kentik/snmp-profiles) repository
> chore: update links to new repo location

- definitions/infra-awsvpcnetworkinterface/summary_metrics.yml
Corrected the values of eventId for the summary_metric.yml in the infra-awsvpcnetworkinterface entity.
'entity.guid' was not the correct way to reference the guid.
> fix: Correct awsvpcnetworkinterface summary metric eventId

- definitions/infra-github_actions/definition.yml
- definitions/infra-github_api/definition.yml
- definitions/infra-github_repo/definition.yml
Removing GITHUB-*  entityType definitions which are unused to avoid conflicts with new entities.
> Removes GITHUB-* entityType definitions from INFRA domain

- definitions/ext-istio_service/golden_metrics.yml
- definitions/ext-istio_service/summary_metrics.yml
Original queries had `WHERE` clauses embedded in the `select:` key.
Fixed by moving them to the proper `where:` key
> fix WHERE clauses in golden and summary metrics queries

- definitions/ext-deeper_connect/golden_metrics.yml
- definitions/ext-deeper_connect/summary_metrics.yml
Fixes summary and golden metrics, was previously using `device.sn` when should be `entity.guid`.
> fix: summary and golden metric eventId's for EXT-DEEPER_CONNECT

- definitions/infra-host/golden_metrics.yml
- definitions/infra-host/summary_metrics.yml
The previous GM definition for OTEL hosts contained the derivative function, which is not supported. In this PR, this is changed to `average`. What's more, the summary metric definition is also provided.
> Fix network golden and summary metrics for OTEL hosts

- definitions/infra-host/golden_metrics.yml
Looks like the GM definition for OTEL break the Lookout for hosts. This PR is to remove it.
> Remove GM definitions for OTEL hosts

- definitions/infra-container/definition.yml
This attribute is not present in all the K8s containers (there are some circumstances where a container doesn't have an id yet), so we're missing some of them.
`k8s.containerName` is enough to identify a K8s container since this attribute is only present in container metrics, so there is no need to add any other extra attribute to the synthesis condition.
> Don't use k8s.containerId as a synthesis condition

- definitions/infra-container/definition.yml
This an attempt to synthesize containers monitored by the opentelemetry collector. The semantic conventions are described [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/container.md).
Note that this rule will only be applied when a specific attribute is sent (nr.entity_type). This is because I'm still testing it and I don't want to release it just yes.
Also note that I haven't defined golden metrics yet. This will come as a follow-up PR.
> Add entity synthesis for otel containers

- definitions/ext-endpoint/definition.yml
- definitions/infra-awsalblistener/definition.yml
- definitions/infra-awsalblistenerrule/definition.yml
- definitions/infra-azureappservicehostname/definition.yml
- definitions/infra-azureloadbalancerbackend/definition.yml
- definitions/infra-azureloadbalancerfrontendip/definition.yml
- definitions/infra-azureloadbalancerinboundnatpool/definition.yml
- definitions/infra-azureloadbalancerinboundnatrule/definition.yml
- definitions/infra-azureloadbalancerprobe/definition.yml
- definitions/infra-azureloadbalancerrule/definition.yml
- definitions/infra-azuresqlfirewall/definition.yml
- definitions/infra-azuresqlreplicationlink/definition.yml
- definitions/infra-azuresqlrestorepoint/definition.yml
- definitions/infra-azurevirtualnetworksipconfiguration/definition.yml
- definitions/infra-azurevirtualnetworksnetworkinterface/definition.yml
- definitions/infra-azurevirtualnetworkspeering/definition.yml
- definitions/infra-azurevirtualnetworksroute/definition.yml
- definitions/infra-azurevirtualnetworksroutetable/definition.yml
- definitions/infra-azurevirtualnetworkssecuritygroup/definition.yml
- definitions/infra-azurevirtualnetworkssecurityrule/definition.yml
Changing `alertable` from `true` to `false` in EXT-ENDPOINT, which represents a network endpoint.
Changing `alertable` from `true` to `false` on Infra entities which should not have `health`.
> change alertable to false

- definitions/ext-router/cisco-asr-dashboard.json
- definitions/ext-switch/arista-dashboard.json
- definitions/ext-switch/cisco-catalyst-dashboard.json
- definitions/ext-switch/cisco-nexus-dashboard.json
- definitions/ext-switch/dell-force10-dashboard.json
Updating `ROUTER` and `SWITCH` entity dashboards to add a new metric name style to the NRQL as an `OR` option to support newer versions of NPM agent. 
> chore: adding new metric name style to NRQL

- definitions/ext-router/golden_metrics.yml
- definitions/ext-router/mikrotik-dashboard.json
- definitions/ext-router/summary_metrics.yml
- The agent was updated time ago to report the memory utilization: https://github.com/OscarDCorbalan/mikrotik-newrelic/pull/6/files
- So it's no longer needed to calculate it derive it, in golden metrics and dashboard, from the reported used and total memory values.
👉  This PR updates those to directly read the memory load value
> EXT-ROUTER: Update Mikrotik to read memory.load metric

- definitions/ext-service/summary_metrics.yml
Update all ext-service summary metric titles to title case and move response time to the first position.
> Update EXT-SERVICE summary metrics order and title case

- definitions/infra-host/golden_metrics.yml
This is adding the cpu golden metric definition for hosts monitored by the opentelemetry collector.
> INFRA-HOST: add cpu gm for otel

- definitions/ext-service/golden_metrics.yml
- definitions/ext-service/summary_metrics.yml
This PR fixes error rates for Otel services. Currently, all Otel services have a summary metric value of 0% for error rate, because Otel services don't have an error metric. This PR updates the golden metric to use span data for error rates, and then uses the golden metric as the summary metric for error rates.
> fix: change otel golden error rate, use in summary metric

- definitions/infra-host/golden_metrics.yml
Since summing two different dimensional metrics is not supported,
the network traffic metric is split into the tx and rx components.
> Split the host network traffic into rx and tx

- definitions/infra-host/golden_metrics.yml
The OTEL definition broke the golden metric harvester - removing it
> Remove opentelemetry host network gm

- definitions/infra-container/definition.yml
- validator/schemas/entity-schema-v1.json
Allow to configure the use of the entityType override as a legacy feature.
This will allow existing types to still use the NA type in the guid while allowing new rules to use the actual type.
Add the configuration into the INFRA-CONTAINER entity type rules that come from the old system.
> Add legacy features & apply to infra-containers

- definitions/infra-ibmmq_manager/definition.yml
- definitions/infra-ibmmq_manager/golden_metrics.yml
- definitions/infra-ibmmq_manager/summary_metrics.yml
- definitions/infra-powerdns_authoritative/definition.yml
- definitions/infra-powerdns_recursor/definition.yml
- docs/synthesis.md
The Core Integrations team is working on the IBMMQ integration based on prometheus exporters, and this PR adds the IBMMQ_MANAGER entity.
[This](https://onenr.io/0nVjYkXgKw0) is a metric example that we are currently ingesting. 
This entities can be either synthesized with the Prometheus Open Metrics integration using the rules specified in the `definitions.yaml` file, or by the Infra Agent (register endpoint of infra pipeline) when the integration is running as an on-host integration. 
**Duplication entity note**:
There are already 2 entities `ext-ibmmqmanager` and `ext-ibmmqqueue` that are used to create entities from an existing integration which will be deprecated with the new supported one. 
I try to combine both entities but `instrumentation.provider` is `newRelic` for both of them …
> Add Infra IBMMQ_MANAGER entity

- definitions/ext-sap_qrfc/dashboard.json
- definitions/ext-sap_qrfc/definition.yml
- definitions/ext-sap_qrfc/golden_metrics.yml
- definitions/ext-sap_qrfc/summary_metrics.yml
Add definition files for new entity type ext-sap_qrfc. This entity type is used to monitor the RFC Queue status.
> Add entity definition file for new entity type ext-sap_qrfc.

- definitions/ext-sap_rfcdest/dashboard.json
- definitions/ext-sap_rfcdest/definition.yml
- definitions/ext-sap_rfcdest/golden_metrics.yml
- definitions/ext-sap_rfcdest/summary_metrics.yml
Add definition files for new entity type ext-sap_rfcdest. This entity type is used to monitor RFC destinations in SAP system.
RFC destination are used by SAP to connect to remote systems. Note: It has a few more tags defined than the document shared during discussion last week.
> Add ext sap rfcdest

- definitions/ext-sap_httpdest/golden_metrics.yml
- definitions/ext-sap_rfcdest/golden_metrics.yml
- definitions/ext-sap_transaction/golden_metrics.yml
It was reported that entities in Span table cause system load up as the system to scan through too many records.
Solution: Limit the number of records the system will look at.
Modify golden metrics for ext-sap_httpdest, ext-sap_rfcdest, ext-sap_transaction, add where clause for contion instrumentation.provider = 'SAP' and SAP_ETYPE = intended SAP ETYPE.
> Add where clause for sap entity golden metrics.

- definitions/ext-service/definition.yml
This PR pulls Kubernetes metadata on telemetry from "OpenTelemetry-flavored" service entities and maps it as tags. These tags are useful for filtering in NR1 as well as powering future curated experiences.
While this function could be useful for all types of providers, I chose to scope it for now only to those with a provider value of `opentelemetry` so we can validate its value before applying it widely. Also note that the `pixie` entities already have something similar except their tags map the OTel semantic casing to the New Relic casing -- this aligns with the existing NR Infra instrumentation but is something we're looking to eventually change.
> Add K8s tags to ext service opentelemetry entities

- docs/synthesis.md
Add a section to note if an attribute is required.
Move the default value into the end of the description
> Add required section on synthesis

- definitions/ext-environment_sensor/definition.yml
- definitions/ext-environment_sensor/summary_metrics.yml
- definitions/ext-environment_sensor/vertiv-watchdog-dashboard.json
Adding `Vertiv Watchdog` as a vendor for the environment sensor entity type.
> chore: adding new vendor to env sensor entity type

- definitions/ext-kentik_default/dashboard.json
fixes a syntax error found in the dashboard definition for the `round()` function
> fix: syntax typos on round() function

- definitions/ext-service/definition.yml
This repeats the tag additions from #429 but for the other OpenTelemetry synthesis rule. I failed to notice that this rule will add the `instrumentation.provider=opentelemetry` value when `telemetry.sdk.name=opentelemetry` which makes it equivalent to the first rule.
> Add K8s tags to all OpenTelemetry synthesis rules

- definitions/ext-service/definition.yml
- docs/synthesis.md
We have two rules for otel services that are the same on the main definition.
The main difference is that for one of them the instrumentation.provider tag of the entity is taken from another attribute rather than the original one.
This must only happen when the instrumentation.provider attribute is not in the telemetry (i think?) hence overriding it.
Before it was not possible to define this behavior but now we can make the rule not match when instrumentation.provider is present.
@erabug could you double check this makes sense to you?
> Improve Service otel rule when provider is not given

- definitions/infra-host/golden_metrics.yml
This is adding the memory golden metric definition for hosts monitored by the opentelemetry collector.
In Linux systems, the resulting value will be different than the one provided by the infra-agent host. The agent uses the `MemAvailable` and `MemTotal` fields from `/proc/meminfo` to compute the memory usage, while the Open Telemetry Collector relies on a sum of some already provided fields. We consider `MemAvailable` more fine-grained as it is computed in the kernel and it takes into account memory low watermarks. 
Issue proposing `MemAvailable` as a new state for the Open Telemetry Collector: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417
> feat: host opentelemetry memory utilization

- definitions/infra-host/definition.yml
In a previous PR, I tried adding an event_type condition for otel host entities, but it looks like it didn't work. I'm hoping to fix it in this PR.
> Fix event type for otel host definition

- definitions/infra-host/definition.yml
Add more conditions into the otel rule for Metrics so we ensure only the important events are being processed.
There are 2 more conditions missing that we will add in the future.
> Add more conditions into otel Metric

- definitions/ext-isilon/golden_metrics.yml
- definitions/ext-isilon/summary_metrics.yml
- definitions/ext-kentik_default/definition.yml
This is an update after initial entity creation to correct what metrics to show.
Summary metric and golden metric can be a single metric/value. In this entity case, there can be many disk pools but only single metric (latest) for one of the pools is shown. This is the update to show average used capacity of all pools. Bugfix.
> Update summary and golden metric NRQL query

- definitions/ext-environment_sensor/definition.yml
- definitions/ext-environment_sensor/summary_metrics.yml
- definitions/ext-environment_sensor/sunbird-dctrack-dashboard.json
Adding telemetry from Sunbird DcTrack devices to `EXT-Environment_Sensor` entity type. 
> feat: adding sunbird dctrack as telemetry source

- definitions/ext-service_level/definition.yml
Rename `env` golden tag to `environment` for Service level entities
> feat: Rename 'env' golden tag for Service Levels

- definitions/infra-container/definition.yml
- docs/synthesis.md
- validator/schemas/entity-schema-v1.json
Document the new `entityTagNames` property for renaming attributes into tags.
Removed the old `entityTagName` this is mostly to avoid confussing users on deciding which one to use, since one is a subset of the other.
We may want to run a script to change all existing `entityTagName` into `entityTagNames` for simplicity.
Finally do the change in containers since this was required for them.
> Document new functionality

- definitions/infra-host/golden_metrics.yml
:sigh: The previous definitions didn't work as expected. Trying out new definitions using gauges, which should work better. This can be done because a couple of PRs were merged in the otel collector, adding these new metrics.
> Use *.utilization metrics to define OTEL host GMs

- definitions/ext-service/tests/Log.json
- definitions/infra-host/tests/Log.json
- definitions/infra-host/tests/MetricRaw.json
Since the entity definitions for OTEL hosts and services are getting a bit complex, I wanted to add a couple of tests:
1. A metric containing host.id will create to a Host
2. A log containing host.id but not service.name will create a Host
3. A log containing host.id and service.name will create a service
> Add tests for OTEL hosts and services

- definitions/ext-cloudflare_host/dashboard.json
- definitions/ext-cloudflare_host/definition.yml
- definitions/ext-cloudflare_host/golden_metrics.yml
- definitions/ext-cloudflare_host/summary_metrics.yml
Customer is emitting metrics from Cloudflare logs that they process themselves. They would like Cloudflare host entities to be generated from these metrics.
* [ x ] I've read the guidelines and understand the acceptance criteria.
* [ x ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ x ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
> Add cloudflare host entity

- definitions/ext-cloudflare_host/golden_metrics.yml
The definition for `errorRate` is not currently supported internally. Fixing it here while we work on a long-term solution
> Fix Cloudflare Host error metric

- definitions/ext-nas/definition.yml
- definitions/ext-nas/golden_metrics.yml
- definitions/ext-nas/summary_metrics.yml
* Corrected a typo on the `instrumenation.name` for NetApp clusters
* Removed deprecated tab from SM
* Removed memory util from SM and GM as it's not a standard metric across NAS devices
* Updated CPU util in SM and GM to add the NetApp clusters
> fix: update netapp instrumentation.name and cleanup SM and GM

- definitions/ext-network_synth/network-synth-dashboard.json
Fixed a mistake with the math of a particular dashboard metric
> fix: change network synthetic metric calculation

- definitions/ext-service/tests/Log.json
- definitions/infra-host/definition.yml
- definitions/infra-host/tests/MetricRaw.json
The OTEL entity synthesis for hosts is currently being restricted by a condition (`nr.entity_type: host`). This was done while we tested the rule, and also because we didn't have the option to have multiple rules to restrict synthesis as we wanted to. Now that we can have multiple rules, I'd like to remove this condition.
I'd like to test this in staging before merging if that's possible!
> otel: remove dummy condition for hosts

- definitions/ext-service/tests/Log.json
- definitions/infra-host/definition.yml
- definitions/infra-host/tests/MetricRaw.json
The previous [PR](https://github.com/newrelic/entity-definitions/pull/497) was inadvertently released. It was reverted, and now I'm reopening it.
The OTEL entity synthesis for hosts is currently being restricted by a condition (nr.entity_type: host). This was done while we tested the rule, and also because we didn't have the option to have multiple rules to restrict synthesis as we wanted to. Now that we can have multiple rules, I'd like to remove this condition.
> Otel host remove dummy condition

- definitions/ext-vpc_network/aws-kinesis-firehose-vpc-flow-logs-dashboard.json
- definitions/ext-vpc_network/definition.yml
- definitions/ext-vpc_network/golden_metrics.yml
- definitions/ext-vpc_network/summary_metrics.yml
* Updated to use `Log_VPC_Flows` data partition
* Added `numeric` conversion where needed (`sample_rate` will sometimes be a string value)
* Added `sample_rate` as a golden tag
* Aligned the kinesis-based dashboard to match the existing ktranslate-based dashboard
* Note: since the kinesis approach currently lacks geo-location and ASN data, the widgets corresponding to Geo Regions and ASN data were left out. We can explore ways to decorate logs with this data if it's important enough to have.
For reference, here's a sample of this dashboard in Staging with real data: https://staging.onenr.io/0x0jlpYeBjW
> feat: enhance kinesis-based VPC_Network entity definition

- definitions/ext-vpc_network/summary_metrics.yml
Quick fix to make remaining summary metrics select from the `Log_VPC_Flows` data partition.
> fix(vpc_network): use correct data partition

- definitions/ext-oracle/dashboard.json
- definitions/ext-oracle/definition.yml
- definitions/ext-oracle/golden_metrics.yml
- definitions/ext-oracle/summary_metrics.yml
- definitions/ext-oracle/tests/MetricRaw.json
Add ext-oracle entity type as part of the SAP entities definitions. This was proposed with the first batch of SAP entities, but not put in as we didn't have Oracle data collected then. Now we have worked out to collect metrics for ORACLE based on  customer request, it's time to add it.
> Add ext-oracle definition to entity definitions

- definitions/ext-cdn_generic/golden_metrics.yml
- definitions/ext-cdn_generic/summary_metrics.yml
- definitions/ext-firewall/golden_metrics.yml
- definitions/ext-firewall/summary_metrics.yml
- definitions/ext-host/golden_metrics.yml
- definitions/ext-host/summary_metrics.yml
- definitions/ext-unix_host/golden_metrics.yml
- definitions/ext-unix_host/summary_metrics.yml
Rewrite golden metric queries for EXT-UNIX_HOST, EXT-GDP_GENERIC, EXT-HOST and EXT-FIREWALL to be able to generate golden metrics out of it. 
> Rewrite some GM queries

- definitions/ext-nas/golden_metrics.yml
- definitions/ext-nas/summary_metrics.yml
- definitions/ext-redis/golden_metrics.yml
Follow up of https://github.com/newrelic/entity-definitions/pull/511 
Rewritten queries for EXT-NAS and EXT-REDIS
> Rewrite GM queries for EXT-NAS and EXT-REDIS

- definitions/ext-environment_sensor/definition.yml
- definitions/ext-environment_sensor/sinetica-eagle-i-dashboard.json
- definitions/ext-environment_sensor/summary_metrics.yml
Adding another vendor to the existing `EXT-ENVIRONMENT_SENSOR` entity type 
> chore: add Sinetica Eagle-i to existing entity definition

- definitions/ext-cisco_ucs/cisco-ucs-dashboard.json
- definitions/ext-cisco_ucs/definition.yml
- definitions/ext-cisco_ucs/golden_metrics.yml
- definitions/ext-cisco_ucs/summary_metrics.yml
adding new entity def for Cisco UCS chassis. these are a bespoke device type that do not have a directly comparable competitor, hence the granularity at the vendor level for these entities.
> feat: adding ext-cisco_ucs definition

- definitions/ext-dell_compellent/summary_metrics.yml
- definitions/ext-dell_recoverpoint/summary_metrics.yml
- definitions/ext-dell_vmax/summary_metrics.yml
- definitions/ext-dell_vnx/summary_metrics.yml
- definitions/ext-dell_vplex/summary_metrics.yml
- definitions/ext-dell_xtremio/summary_metrics.yml
- definitions/ext-pure/summary_metrics.yml
- definitions/ext-synology/summary_metrics.yml
- definitions/infra-ibmmq_manager/summary_metrics.yml
Remove the `as` fields in the summary metric since this is not allowed in summary metrics queries. 
> Remove the as in the summary metrics

- definitions/ext-service/definition.yml
Configure 1 day of TTL for k8s. tags in ext-service.
This will help lower the number of tags from K8s
Format is in ISO-8601, I will do a follow up PR to document and add validations on this new field
> Add TTL for k8s tags in ext service

- definitions/ext-service/definition.yml
Fix the time for ttl tags.
The `T` is only needed when defining time.
Like: `P1DT30M` or `PT1H`
Will add validators once finished all the testings
> EXT-SERVICE: Fix ttl times for k8s tags

- definitions/ext-postman_monitor/definition.yml
- definitions/ext-postman_monitor/postman-monitor-dashboard.json
Added a Postman Monitor entity type based off of [the Postman quickstart](https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/postman).
> Add Postman Monitor entity type

- definitions/ext-service/definition.yml
In https://github.com/newrelic/entity-definitions/pull/535 I added TTL for K8s tags but forgot about the pixie ones.
This PR also adds the same TTL for the tags when they come from pixie
> TTL k8s tags from pixie

- definitions/ext-vpc_network/summary_metrics.yml
Looks like a minor copy-paste issue with VPC Flow Logs Ingress Bytes
> Fix typo in VPC Ingress Bytes

- docs/synthesis.md
- validator/schemas/entity-schema-v1.json
Validate the TTL field on the schema.
I noticed that we where not actually validating anything on the tags field since `additionalProperties` was not set to false.
So, as with TTL, any property could be set in the tags section.
I changed `properties` into `patternProperties` to allow any key under the tags map and it validates if it either has a map with the expected keys or a null
> Validate ttl

- validator/schemas/dashboard-schema-v1.json
Allowed the property linkedEntityGuids in the dashboard schema though it is unsupported.
The dashboard exporter will always provide the field, so it's quite common that it is present. It is inconvenient to remove those fields manually, so it's syntactically allowed but only with a null value.
* ~~[ ] The value of the attribute marked as `identifier` will be unique and valid.~~ Does not apply here. 
* ~~[ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
explanation above.~~ Does not apply here.
> feat: More convenient dashboard schema validation for linkedEntityGuids

- definitions/ext-oracle/dashboard.json
Update ext-oracle dashboard definition. The unit of the DB Size conversion to GB from MB, not from KB.
For SAP Observability, add the proposed ext-mssql entity for MicroSoft SQL Server. Metrics are collected by NR SAP agents. 
>  On branch fix-ext-oracle-dashboard-units

- definitions/ext-oracle/golden_metrics.yml
- definitions/ext-oracle/summary_metrics.yml
The data source for db size is in Megabytes, the golden metrics and summary metrics are expecting it in bytes, Convert db space size metric to be in bytes.
> Fix unit for Oracle golden metrics. 

- definitions/ext-argocd/definition.yml
Removed the `debug:true` key from the `definition.yaml` file as requested post entity merge.
> Update: [argocd] Remove 'debug' from definition for ArgoCD

- definitions/infra-azurepostgresqlserver/summary_metrics.yml
Change summary metric `storage` for entity types infra-azurepostgresqlserver to be the same as golden metric
This is part of the epic to make all the summary metrics to be a subset of golden metrics.
> ESA-1239 metric name for infra-azurepostgresqlserver

- definitions/infra-kubernetes_pod/summary_metrics.yml
change summary metric name `errorsNetwork` to `networkErrors` to be equivalent to golden metrics
This is part of the epic to make all the summary metrics to be a subset of golden metrics.
> ESA-1239 metric name for infra-kubernetespod

- definitions/ext-host/definition.yml
This sample was meant to be included in the original PR but was missed.
As previously mentioned needed for the cloud accelerator initiative. 
> feat: ext-host add missing sample

- definitions/ext-email_gateway/cisco-ironport-email-dashboard.json
- definitions/ext-email_gateway/definition.yml
- definitions/ext-email_gateway/golden_metrics.yml
- definitions/ext-email_gateway/summary_metrics.yml
adding Cisco IronPort telemetry to existing `EXT-EMAIL_GATEWAY` definition.
> chore: add cisco ironport to email gw definition

- definitions/ext-host/definition.yml
- definitions/infra-host/definition.yml
https://issues.newrelic.com/browse/NR-6568
Per the ticket above, we want to use entity synthesis on log data that has host information but is missing a service name or container. If it has either of those, we want entity synthesis to use the service name if available, or container name instead. 
> feat: Add entity synthesis for host from log data

- definitions/ext-firewall/cisco-asa-dashboard.json
- definitions/ext-firewall/definition.yml
- definitions/ext-firewall/pulse-secure-dashboard.json
Added a new dashboard for pulse-secure vpn appliances
updated definition to link to that dashboard
updated ASA (default) dashboard to be in line with other current dashboards.
> feat: add new dashboard under ext-firewall

- definitions/ext-ibmmqqueue/golden_metrics.yml
From ticket NR-17236 this copy SummaryMetric into GoldenMetric with the purpose of have all SummaryMetric be a subset of GoldenMetric for ext-ibmmqueue
> fix ext-ibmmqueue SM

- definitions/ext-service/golden_metrics.yml
This PR corrects the where clause on the error rate for golden metrics of ext-services. Replacing the In keyword with the like keyword will allow this metric to catch relevant values for error rates.
> fix: Correct where clause on error rate for golden metric of ext

- validator/schemas/summary-metrics-schema-v1.json
Add goldenMetric into summary-metric validation
https://issues.newrelic.com/browse/NR-17236
Fix -> https://github.com/newrelic/entity-definitions/pull/635 
> Fix_goldenMetric-schema-validator

- definitions/infra-host/definition.yml
This reverts commit 4fa697c922ee9ca22aa272ac316b6fb6568f7c99.
We have found a few cases where these new rules are not working as it's expected.
To be cautious we decided to roll-back the rules that are related to logs
> Revert "feat: Add entity synthesis for host from log data (#598)"

- definitions/infra-awsalb/golden_metrics.yml
I want the requests metric to be processed by the golden metric harvester, but Its not. I guess is because the event name field was missing.
> Add eventName to awsalb requests sample GM

- definitions/infra-awselb/golden_metrics.yml
- definitions/infra-awsnlb/golden_metrics.yml
surgequeue golden metric is missing the Sample table query.
> fix awselb goldenmetric

- definitions/infra-mysqlnode/golden_metrics.yml
- definitions/infra-mysqlnode/summary_metrics.yml
The goal of this PR is to make SM a subset of GM
To achieve that, and to not add more than 5 GM, I changed a bit the `slowQueries` SM  so now is "per minutes" like the GS
> NR-17236 Make SM subset of GM for mysqlnode

- definitions/infra-azurerediscache/golden_metrics.yml
- definitions/infra-azurerediscacheshard/golden_metrics.yml
Both types have missing or wrong metrics that are not able to be processed.
> Fix azurerediscacheshard and azurerediscache

- definitions/infra-awsapigatewaystage/golden_metrics.yml
- definitions/infra-awsapigatewaystage/summary_metrics.yml
The main goal of this PR was to set the same units for latency metrics in SM and GM.
Apart from that, I assumed that the latency for the GM was wrong, since this is a gatewaystage, so I guess we need to pick the xxx.byStage rather than the byApi.
> Fix metrics for infra-awsapigatewaystage

- definitions/infra-host/summary_metrics.yml
Summary metrics for hosts should use host metrics if available, and then fall back to cloud if available
https://github.com/newrelic/infrastructure-agent/issues/1219
> Infra host metrics have precedence over cloud metrics

- definitions/infra-gcpkubernetesnode/golden_metrics.yml
the golden metrics for gcpkubernetesnode did not have the Metric queries...
this PR adds them.
> fix GM for gcpkubernetesnode

- definitions/infra-awsiotrule/golden_metrics.yml
After checking the golden signals for some accounts, I've realized the queries ara not 100% accurate.
> Fix golden metrics for aws-iot-rule

- definitions/ext-cloudflare_host/golden_metrics.yml
- definitions/ext-istio_service/golden_metrics.yml
- definitions/infra-awsalbtargetgroup/golden_metrics.yml
- definitions/infra-awsapigatewayapi/golden_metrics.yml
- definitions/infra-awsapigatewayresourcewithmetrics/golden_metrics.yml
- definitions/infra-awselasticsearchcluster/golden_metrics.yml
- definitions/infra-awselasticsearchnode/golden_metrics.yml
- definitions/infra-awslambdafunction/golden_metrics.yml
- definitions/infra-awslambdafunction/summary_metrics.yml
- definitions/infra-awslambdafunctionalias/golden_metrics.yml
- definitions/infra-awsmediapackagevodpackagingconfiguration/golden_metrics.yml
- definitions/infra-awsstatesstatemachine/golden_metrics.yml
- definitions/infra-azureapplicationgateway/golden_metrics.yml
- definitions/infra-azurefrontdoorfrontdoor/golden_metrics.yml
- definitions/infra-azurekeyvaultvault/golden_metrics.yml
- definitions/infra-azurepowerbidedicatedcapacity/golden_metrics.yml
- definitions/infra-gcpbigtabletable/golden_metrics.yml
- definitions/infra-gcphttploadbalancer/golden_metrics.yml
- definitions/infra-mssqlinstance/golden_metrics.yml
The goal of this PR is to fix those metrics that are reported in Milliseconds but the UNIT is wrong. Also those metrics that are reported in RPM, but the unit is wrong.
> NR-30515 fix units of metrics in MS or RPM

- definitions/infra-azurerediscache/summary_metrics.yml
Fix SM aggregation to use `max` on `Maximum` metric
> fix Azure Redis SM aggregation

- definitions/ext-istio_service/definition.yml
The current entity definition produces non-unique entities that are common across K8s clusters (e.g. prod, pre-prod, etc). This makes it unusable. This change updates entity synthesis to incorporate composite identifiers that include the K8s cluster name.
> Address non-unique istio entities (fixed omitted tags)

- definitions/ext-db2/golden_metrics.yml
- definitions/ext-db2/summary_metrics.yml
Introduced missing units in the GM definitions, aligned the name of the `errorRate` metric, added a new GM so that it can be referenced in the SM definition file. 
> Align SM and GM definitions for EXT-DB2

- definitions/ext-vpc_network/aws-kinesis-firehose-vpc-flow-logs-dashboard.json
- definitions/ext-vpc_network/golden_metrics.yml
- definitions/ext-vpc_network/summary_metrics.yml
This PR updates the AWS VPC dashboard (derived from AWS VPC Flow Logs) to use a new table name. For all of the dashboard queries, I had them fetch from both event types (for backwards compatibility). After the beta customers have migrated to the new event type, we will make another PR to remove the old name.
This dashboard has only been exposed to a few beta customers and we are working with the appropriate contacts there to make sure they update their event types before we make the next PR
One place where this will introduce a breakage is in golden and summary metrics. I don't believe these definitions let me select two event types as the "from" field but let me know if I'm wrong there.
> Update AWS VPC Flow Log event type

- definitions/ext-vpc_network/definition.yml
- definitions/ext-vpc_network/gcp-pubsub-dataflow-vpc-flow-logs-dashboard.json
- definitions/ext-vpc_network/golden_metrics.yml
- definitions/ext-vpc_network/summary_metrics.yml
This PR adds support for synthesizing VPC entities from GCP VPC Flow Logs. I tried to follow the same pattern that AWS Flow Logs use but things are a little more awkward in GCP for a couple reasons:
1. VPC IDs are not annotated onto flow logs like in GCP. As a result, I had to make the entity identifier the VPC name and the project ID. GCP Project IDs [must be globally unique](https://cloud.google.com/resource-manager/docs/creating-managing-projects#:~:text=A%20globally%20unique%20identifier%20for%20your%20project) and then VPC names [must be unique in a project](https://cloud.google.com/vpc/docs/create-modify-vpc-networks#:~:text=Each%20new%20network%20that%20you%20create%20must%20have%20a%20unique%20name%20within%20the%20same%20project). Also, VPC names cannot be changed after they are …
> feat: Add support for GCP VPCs

- definitions/ext-wireless_controller/cisco-wlc-dashboard.json
- definitions/ext-wireless_controller/definition.yml
- definitions/ext-wireless_controller/golden_metrics.yml
- definitions/ext-wireless_controller/summary_metrics.yml
adding `cisco-wlc` as a new source of data for the existing `EXT-WIRELESS_CONTROLLER` entity definition. also has a few small fixes on the existing Meraki and Aruba items in the same definition.
> chore: add cisco-wlc to existing wireless controller entity

- definitions/ext-network_synth/golden_metrics.yml
- definitions/ext-network_synth/network-synth-dashboard.json
- definitions/ext-network_synth/summary_metrics.yml
One of the attribute names used in the dashboard and golden metrics needed to be updated from an earlier version.
> Fix network synth metric name

- definitions/infra-host/summary_metrics.yml
Remove the OTel metrics from the summary metric definition file of INFRA-HOST. They were added in the previous PR and might be causing all queries to time out. 
> Remove otel summary metrics for infra-host

- definitions/infra-host/summary_metrics.yml
Hopefully, this will be the last PR to fix the infra-host's summary metric definition. The Otel metric was supposed to be deleted in one of the previous PRs, but instead, the host one got deleted. 
> Add missing metric for infra-host

- definitions/infra-vspherehost/golden_metrics.yml
- definitions/infra-vspherehost/summary_metrics.yml
change summaryMetrics and GoldenMetrics  infra-vspherehost to be compatible
> NR-30537 sm gm infra-vspherehost

- definitions/infra-awsdynamodbtable/golden_metrics.yml
- definitions/infra-awsdynamodbtable/summary_metrics.yml
NR-30543 fix GoldenMetric SummaryMetric of infra-awsdynamodbtable 
> NR-30543 fix gm sm awsdynamodbtable

- definitions/ext-firewall/golden_metrics.yml
- definitions/ext-firewall/summary_metrics.yml
Rewrite max(smth) / max(smth) expressions as max(smth / smth) 
Rewrite max(smth) + max(smth) as max(smth + smth)  
Golden metrics cannot be synthesized for EXT-FIREWALL as some of its queries are not valid. 
> Rewrite some queries for EXT-FIREWALL metrics

- definitions/apm-application/golden_metrics.yml
- definitions/apm-application/summary_metrics.yml
The correct unit is RPS instead of RPM. 
> Fix units for throughput metric of APM-APPLICATION entities

- definitions/apm-application/golden_metrics.yml
- definitions/apm-application/summary_metrics.yml
This reverts commit 6895507c0a467c988837866e27a32b9da8f83b18. 
> Revert "Fix units for throughput metric of APM-APPLICATION entities

- definitions/browser-application/summary_metrics.yml
Currently, the Browser summary metrics come from the summary metric service, which we want to get away from. This provides summary metrics that match the golden metrics for browser. 
> feat: Add browser summary metric file

- definitions/external-service/definition.yml
After talking to the DT team and @areina we reached the conclusion that 24h for the External Service is good enough for all parties.
> Lower TTL for External Service

- definitions/ext-wireless_controller/golden_metrics.yml
- definitions/ext-wireless_controller/summary_metrics.yml
updating GM/SM definitions for `EXT-WIRELESS_CONTROLLER` to align all sources of telemetry to the same metric kind for the GMH.
> fix: GM/SM queries for aruba wireless controllers

- definitions/ext-nas/golden_metrics.yml
- definitions/ext-nas/summary_metrics.yml
updating `EXT-NAS` GM/SM queries for ReadyNAS telemetry
> fix: gm/sm queries for ReadyNAS telemetry

- definitions/ext-email_gateway/golden_metrics.yml
- definitions/ext-email_gateway/summary_metrics.yml
Fixing CPU query for GM/SM on the `EXT-EMAIL_GATEWAY` entity definition for Barracuda telemetry.
> fix/email gateway gm/sm

- definitions/apm-application/golden_metrics.yml
- definitions/apm-application/summary_metrics.yml
Add missing `rate(, 1 minute)` for APM-APPLICATION's throughput metric in both golden & summary metric definitions. 
> Fix APM-APPLICATION throughput metric definition

- docs/summary_metrics.md
- Updated the docs to reflect the new `goldenMetric` reference capability
- Removed mentions to `hidden` and `derive` since we're using them internally only
- Leaving for the time being `query`, mentioning its deprecation in favor of `goldenMetric`
> Updated documentation for golden metric references

- definitions/mlops-machine_learning_model/golden_metrics.yml
- definitions/mlops-machine_learning_model/summary_metrics.yml
The total for 30 minutes is shown, instead of request per minute.
This is a fix that divides by 30.
> Fix Total inference to actually show data per minute

- validator/schemas/summary-metrics-schema-v1.json
The two fields are not required as, when not present, default values will be assigned for them. 
> Remove eventId and from as required fields in SM query configuration

- definitions/infra-varnishinstance/golden_metrics.yml
As the telemetry does not contain `entity.name`, but `entityName` attributes only, we need to explicitly tell the configuration to not use the default eventName. 
> Add missing eventName for INFRA-VARNISHINSTANCE GM definitions

- definitions/mlops-machine_learning_model/golden_metrics.yml
- definitions/mlops-machine_learning_model/summary_metrics.yml
Adjusts metrics to work for both SMs and GMs by using uniqueCount wrapped in rate.
Fixes the code changes from the previous PR [here](https://github.com/newrelic/entity-definitions/pull/740).
> Update mlops-machine_learning_model metrics to use rate

- definitions/infra-host/definition.yml
Added an entity Synthesis rule for Azure Hosts (resourceType `Microsoft.Compute/virtualMachines`). 
> Add Azure HOST entity synthesis rule

- definitions/ext-kentik_default/ping-dashboard.json
Based on customer feedback swapped out the where condition so that it matched up with devices being pinged by kentik\ktranslate
> Update ext-kentik_default ping-dashboard

- definitions/ext-kentik_default/ping-dashboard.json
fixing dashboard widget that was missing a data formatter option
> fix: add datetime format to widget

- docs/synthesis.md
change the doc to reflect that we hash the identifier not necode.
Hash is not reversible while encoding is
> we hash de identifier not encode

- definitions/infra-awselasticachecluster/definition.yml
- definitions/infra-awselasticachecluster/golden_metrics.yml
- definitions/infra-awselasticachecluster/summary_metrics.yml
- definitions/infra-awselasticachememcachedcluster/golden_metrics.yml
- definitions/infra-awselasticachenode/definition.yml
- definitions/infra-awselasticachenode/golden_metrics.yml
- definitions/infra-awselasticachenode/summary_metrics.yml
Create 2 new entities that englobes the elasticache (redis | memcached) cluster and node. 
This is needed because in some scenarios (Metric Streams) there is no way to distinguish between redis or memcached, then we need a way to somehow assign an entity to those metrics
> Add new generic elastic cache entities

- definitions/infra-container/summary_metrics.yml
- definitions/infra-host/summary_metrics.yml
- validator/schemas/summary-metrics-schema-v1.json
The validation was failing when no query was provided. SMs can just contain pointers to GMs to be valid. 
> Allow specifying only the goldenMetric pointer in summary metric definitions

- definitions/infra-gcpappengineservice/golden_metrics.yml
Incorrect query in GM fixed: missing to dived by the total number of responses.
> NR-46389: Fix INFRA-GCPAPPENGINESERVICE

- definitions/ext-meraki_controller/definition.yml
updating the `synthesis.name` and `synthesis.identifier` attributes on the `EXT-MERAKI_CONTROLLER` definition to isolate the entity at the controller level. The current `device_name` attribute is used for multiple items below the controller and is causing `n+1` entities when we only want 1 created. 
> fix: update synthesis name and identifier

- definitions/ext-not_instrumented/definition.yml
This new type will hold entities that are not yet  instrumented but detected by an internal system in NR.
For now this is on experimental so we are not providing an overview.
> Create NOT_INSTRUMENTED entity type

- docs/README.md
The documentation was still referencing the old format for defining summary metrics. This PR addresses that. 
> Update summary metrics docs

- definitions/ext-not_instrumented/definition.yml
- definitions/uninstrumented-database/definition.yml
This new type will replace EXT-NOT_INSTRUMENTED
We will have a type under this domain for each generic type of entity.
So for DB's we have database instead of mysqldb, psqldb, awspsqldb etc
We also move to UNINSTRUMENTED to be inside the domain length limits.
A follow-up PR will delete the not-instrumented type once we shutdown the poc.
> Introduce uninstrumented entities domain

- definitions/ext-firewall/golden_metrics.yml
- definitions/ext-firewall/palo-alto-dashboard.json
* Updates the fortigate GM definition to only use a single dimensional metric (old query had issues in golden signals pipeline)
* Also reverts the memoryUtilization query for palo alto devices back to a previous working state
> fix(firewall): Use single dimensional metric for GM rule

- definitions/ext-pixie_kafkabroker/dashboard.json
- definitions/ext-pixie_kafkabroker/definition.yml
- definitions/ext-pixie_kafkabroker/tests/MetricRaw.json
- definitions/ext-pixie_kafkabroker/tests/Span.json
The Pixie Kafka entity name uses the wrong field at the moment. It should be `px.cluster.id` not `pixie.cluster.id`. Discovered this during testing.
> Fix Pixie Kafka entity name

- definitions/ext-pixie_dns/dashboard.json
Discovered that I didn't change the DNS dashboard span filter. I was filtering on an old field that doesn't show up in the data anymore. This diff points to a new filter that actually shows up in the data.
> Fix the condition for capturing traces inside of the Pixie DNS dashboard

- definitions/ext-pixie_cassandra/definition.yml
- definitions/ext-pixie_cassandra/tests/MetricRaw.json
- definitions/ext-pixie_cassandra/tests/Span.json
Not all Cassandra requests have a req_body, which means that those requests won't show up under the Pixie Cassandra entity. This PR updates the entity definition to use a column that is always present in CQL requests. cc @philkuz 
> Update Pixie-Cassandra entity definition.

- definitions/ext-not_instrumented/definition.yml
We have decided on using the UNINSTRUMENTED domain.
So we need to cleanup this ext-not_instrumented
> Remove not_instrumented type

- definitions/infra-host/definition.yml
Adding the overrideGuidType = false to the Azure host to keep backwards compatibility with old integrations hosts. 
> Azure host overrideGuidType

- definitions/ext-otelcol/definition.yml
This is a small modification of the existing Opentelemetry Collector definition. Right now, the uid of an agent is implicitly defined as the entity name. This could cause some confusion in the future, so I'd like to add a separate tag for the agent uid instead.
Note: this rule is still protected by a dummy condition (nr.entity_type), so it's not used by anyone in practice.
> Add the agent uid as a separate attribute

- definitions/ext-pixie_dns/dashboard.json
Switch to use `rcode_name` instead of `rcode for Pixie DNS dashboard. rcode_name is more readable after our conversions.
After: 
Before:
> Fix: Use rcode name instead of rcode for Pixie DNS

- definitions/ext-pixie_dns/golden_metrics.yml
- definitions/ext-pixie_kafkabroker/golden_metrics.yml
- definitions/ext-pixie_mysql/golden_metrics.yml
Discovered after the entity update that `percentage()` did not render properly inside of the golden metrics view. The golden metrics platform does not support percentage at the moment. This diff makes a work around:  we're "manually" calculating the percentage by replacing the aggregate with the following:
```
s/percentage\(count\((.*?)\), WHERE (.*)\)/filter(count($1), WHERE $2) \/ count($1)_)/g
```
`percentage(count(mysql.latency), WHERE mysql.resp_status>2)` became
`filter(count(mysql.latency), WHERE mysql.resp_status>2) / count(mysql.latency)`
> fix: Replace pixie golden metrics percentage aggregate

- definitions/ext-pixie_dns/golden_metrics.yml
- definitions/ext-pixie_kafkabroker/golden_metrics.yml
- definitions/ext-pixie_mysql/golden_metrics.yml
There's a bug in the golden metrics platform right now that we ran into with the Pixie Golden Metrics: https://issues.newrelic.com/browse/NEWRELIC-5496
This diff is a work-around that fixes the issue where error % metrics didn't show up for Pixie entities that had this golden metric. 
To prevent further churn: I worked with the golden metrics team to test each metric using the ephemeral golden metric service on staging. Each of these metrics should work to the best of my knowledge.
> Fix: Pixie Golden Metrics order of operations

- definitions/infra-host/definition.yml
The NR agent uses `vmId` this change is to preserve intercompatibility between both sources of data. 
> Change Azure host identifier

- definitions/infra-host/golden_metrics.yml
```
Following this change in the specs, direction will disappear as an attribute and be part of the metric name. For instance system.network.io will be replaced by system.network.io.transmit and system.network.io.receive. This directly impacts the golden metric definitions, which should be updated.
```
> NEWRELIC-4198 : Update OTEL Host golden metrics (network.io)

- definitions/ext-pixie_amqp/summary_metrics.yml
- definitions/ext-pixie_cassandra/summary_metrics.yml
- definitions/ext-pixie_dns/summary_metrics.yml
- definitions/ext-pixie_kafkabroker/summary_metrics.yml
- definitions/ext-pixie_mysql/summary_metrics.yml
- definitions/ext-pixie_postgres/summary_metrics.yml
- definitions/ext-pixie_redis/summary_metrics.yml
It can sometimes be difficult to know which Kubernetes cluster Pixie entities are coming from. For example, in the `DNS - Pixie` entity list view, we have many `kube-dns` entities:
Our goal is to add the cluster name as a column to the (above) entity list view. It appears that the `summary_metrics.yml` file controls this view, so we've added the cluster name there. Cluster name is already part of the tags for each Pixie entity. 
> Add cluster name to Pixie entities list view

- definitions/infra-host/definition.yml
All the dashboards are defined using metrics from the Agent, if we allow cloud metrics to register and index an entity, it won't have any metrics unless the agent is also installed.
> Avoid Cloud metrics showing empty agent Hosts

- definitions/infra-awsfsxvolume/definition.yml
- definitions/infra-awsfsxvolume/golden_metrics.yml
added def and golden metrics for aws fsx volumne ent type. 
* [ X] I've read the guidelines and understand the acceptance criteria.
* [X ] The value of the attribute marked as `identifier` will be unique and valid. 
* [X ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
Please see Mike Krichevsky for review if needed.
> Infra aws fsx volumes

- definitions/ext-key_transaction/golden_metrics.yml
https://issues.newrelic.com/browse/NR-70592
changed summary metrics query  to display throughput value.
> fix: NR-10056 modified the query for summary metrics for KT throguput

- .github/workflows/validate-definition.yml
- definitions/ext-dell_datadomain/dashboard.json
- definitions/ext-influxdb/dashboard.json
- definitions/ext-rubrik/dashboard.json
- definitions/ext-shelled_spa/dashboard.json
- definitions/ext-zerto/dashboard.json
I keep finding that contributors fail to sanitize their dashboards. It's very annoying to run the sanitize dashboard commands and find other users' dashboards show up. This diff adds the sanitize command and a git repo dirty check to the workflows that must be run before a PR is accepted. 
I tested this on this PR with a few commits. Ran it first with the dashboards not sanitized: https://github.com/newrelic/entity-definitions/actions/runs/3842474241
Then ran it with the dashboards sanitized:
https://github.com/newrelic/entity-definitions/actions/runs/3842481940
> Validate that sanitize dashboards was run

- definitions/ext-pixie_amqp/definition.yml
- definitions/ext-pixie_cassandra/definition.yml
- definitions/ext-pixie_dns/definition.yml
- definitions/ext-pixie_kafkabroker/definition.yml
- definitions/ext-pixie_mysql/definition.yml
- definitions/ext-pixie_postgres/definition.yml
- definitions/ext-pixie_redis/definition.yml
Pixie entities required a namespace to exist, this relaxes that restriction while still keeping namespace around to distinguish between different entities.
Checklist
> NEWRELIC-5915: Ensure that off-cluster Pixie entities are properly captured

- definitions/ext-pixie_redis/dashboard.json
> NEWRELIC-5898: Add breakdown of Redis metrics based on responding pods and requesting pods

- definitions/ext-pixie_postgres/dashboard.json
> NEWRELIC-5898 Postgres split by requesting pod and split by responding pod

- definitions/ext-pixie_kafkabroker/dashboard.json
> NEWRELIC-5898 Pixie Kafka split by requesting pod and split by responding pod

- definitions/ext-pixie_mysql/dashboard.json
Signed-off-by: Phillip Kuznetsov <pkuznetsov@pixielabs.ai>
> NEWRELIC-5898 Pixie MySQL split by requesting pod and split by responding pod

- definitions/ext-pixie_cassandra/dashboard.json
Signed-off-by: Phillip Kuznetsov <pkuznetsov@pixielabs.ai>
> NEWRELIC-5898 Pixie Cassandra Dashboard updates: split by requesting pod and split by responding pod

- definitions/ext-pixie_amqp/dashboard.json
Signed-off-by: Phillip Kuznetsov <pkuznetsov@pixielabs.ai>
Users have requested that we breakdown these metrics by the pods that service them as well as the pods that request them.
This diff adds new charts to the dashboard to breakdown metrics by pod. Also reorganizes the 
dashboard so that the user can gradually get more in-depth info as they scroll lower.
> NEWRELIC-5898 Pixie AMQP Dashboard updates: split by requesting pod and split by responding pod

- definitions/ext-pixie_dns/dashboard.json
Signed-off-by: Phillip Kuznetsov <pkuznetsov@pixielabs.ai>
> NEWRELIC-5898 Pixie DNS Dashboard updates: split by requesting pod and split by responding pod

- definitions/ext-otelcol/definition.yml
We discovered that this is not the best place to populate the `opamp.agent.uid`, as it can fall back to a value that doesn't always correspond to an agent in our OpAMP agents database.
Instead, it will be better to populate this tag more intentionally with a resource processor in the pipeline that exports the collector's o11y data.
> Remove opamp.agent.uid tag taken from instance.id

- definitions/ext-ssl_certificate/dashboard.json
- definitions/ext-ssl_certificate/definition.yml
- definitions/ext-ssl_certificate/golden_metrics.yml
- definitions/ext-ssl_certificate/summary_metrics.yml
- definitions/ext-ssl_certificate/tests/Log.json
Adding an Entity Definition for SSL Certificates. The goal is to provide an entity that will show the common name for a certificate as the entity where entity uniqueness is based on the certificate serial number. The summary dashboard should include the expiration date and the number of days left until a certificate expires.
```
import os
from datetime import datetime
from newrelic_telemetry_sdk import GaugeMetric, MetricClient
metric_client = MetricClient(os.environ["NEW_RELIC_INSERT_KEY"])
TODAY = "01-20-2023"
tags = {
"ssl.cert.common_name": "www.epochalypse.today",
"ssl.cert.serial_number": "03:2F:E5:F0:34:8C:21:15:7F:32:CB:ED:90:63:A8:51:41:A6",
"ssl.cert.expiration_date": "01-19-2038",
"provider": "ext-ssl"
}
a = datetime.strptime(TODAY, "%m-%d-%Y")
b = …
```
> Add SSL Certifcate Entity Definition

- definitions/infra-azureappserviceplan/golden_metrics.yml
https://issues.newrelic.com/browse/NR-81315
Fix golden metrics for `azure app service plan`
The awsSample metric is not able to be captured internally by our golden metric synthetizer.
> Fix golden metrics for azureappserviceplan

- docs/entity_summary.md
- validator/schemas/entity-schema-v1.json
We want to support more powerful entity dashboards. In the backend, we've gone ahead and supported `filterNRQLByEntityID` as an optional parameter. This change propagates that upwards and adds the documentation here.
> Add support for filterNRQLByEntityID in definition.yml

- definitions/infra-kubernetes_cronjob/definition.yml
- definitions/infra-kubernetes_cronjob/summary_metrics.yml
- definitions/infra-kubernetes_cronjob/tests/MetricRaw.json
- definitions/infra-kubernetes_job/definition.yml
- definitions/infra-kubernetes_job/summary_metrics.yml
- definitions/infra-kubernetes_job/tests/MetricRaw.json
Reverts newrelic/entity-definitions#924
Reverting the revert so the changes that were accidentally deployed are back in the BETA channel.
> Revert "Revert "Add Kubernetes Job, CronJob entities""

- definitions/ext-gigamon_dns/definition.yml
> Fix: typo in gigamon definition

- definitions/ext-billable_user/definition.yml
After the successfully validation of ext-billable_user, we are removing the `debug` flag and will be releasing it.
> Enable ext-billable_user

- definitions/aiops-workflow/definition.yml
Until we are fully ready with workflow entity UI, we want to make sure that workflows are invisible on all-entities page
> make workflows non-alertable

- definitions/uninstrumented-awss3bucket/definition.yml
- definitions/uninstrumented-awssnstopic/definition.yml
- definitions/uninstrumented-awssqsqueue/definition.yml
Relevant information
Follow-up from https://github.com/newrelic/entity-definitions/pull/902 introducing more uninstrumented types.
> Introduce uninstrumented S3, SQS, SNS

- definitions/infra-squid_cachemgr/definition.yml
- definitions/infra-squid_cachemgr/tests/MetricRaw.json
This PR adds entities for the upcoming squid open telemetry integration (using the prometheus expoter and its otel receiver) being worked by Coreint Team.
> Add squid exporter otel definition (NR-83160)

- definitions/mobile-application/golden_metrics.yml
- definitions/mobile-application/summary_metrics.yml
We noticed that the golden metric that was labeled `HTTP errors count` was actually querying for an `average`. We want to change the name of the query to `HTTP errors rate`. I also updated the summary metric to stay in sync with the golden metric.
* [ X] I've read the guidelines and understand the acceptance criteria.
* [ X] The value of the attribute marked as `identifier` will be unique and valid. 
* [ X] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
> Mobile golden metrics -  change title to reflect query

- definitions/ext-coredns/golden_metrics.yml
This reverts commit 015745c56bd5642fe96392760534fd5884fd3e9c.
The `bucketpercentile` value function doesn't seem to be supported well by the platform. While we investigate the issue, we'll revert to the previous commit.  
cc. @RagalahariP 
> Revert "Adding request duration metric with histogrampercentile (#939)"

- definitions/synth-runtime_validation/definition.yml
- definitions/synth-runtime_validation/summary_metrics.yml
purpose: this will give us a way to index information for the ui to display about a monitors current runtime upgrade validation.
account|SYNTH|RUNTIME_VALIDATION|domainId
domainId is a 32 char uuid.
> feat: create synthetics runtime upgrade validation entity

- definitions/ext-service/definition.yml
Added a deployment tag for service data that comes from Pixie. We've had this data for a while
now coming from Pixie, we just haven't utilized it yet: https://github.com/pixie-io/pixie-plugin/commit/ce56307508c79421a683a0bb72baa095e87de0d4
This will help connect service data that comes from Pixie to infrastructure data available in New Relic.
> ext-service: Add deployment tag for data that comes from Pixie

- definitions/ext-site/golden_metrics.yml
- definitions/ext-site/summary_metrics.yml
Fix summary metrics / golden metric definition for EXT_SITE to query from SITE table instead of the default Metric one.
Also slightly changed some summary metric names to be more consistent with existing ones.
> Fix EXT_SITE summary metrics

- definitions/ext-billable_user/definition.yml
- definitions/ext-billable_user/summary_metrics.yml
- Definition now uses composite to stamp guid
- Added relevant tag to summary metrics
> billable_user: update definition to composite

- definitions/infra-kubernetes_job/summary_metrics.yml
This PR fixes a typo in a golden metric name. 
> Fix: Kubernetes Job golden metrics typo

- definitions/infra-kubernetes_cronjob/golden_metrics.yml
- definitions/infra-kubernetes_cronjob/summary_metrics.yml
This PR adds golden metrics for the new Kubernetes CronJob entity. 
> Feat: add Kubernetes CronJob golden metrics

- definitions/infra-kubernetes_persistentvolume/summary_metrics.yml
This PR adds summary metrics to the new Kubernetes PersistentVolumeClaim entity.
> feat: add Kubernetes PersistentVolume summary metrics

- definitions/infra-kubernetes_job/definition.yml
This PR changes the Kubernetes Job entity expiration time from daily ---> 4 hours. 
> fix: update Kubernetes Job entityExpirationTime from daily to 4 hours

- definitions/ext-service/definition.yml
- definitions/ext-service/tests/Log.json
We're developing a New Relic distribution of the java otel agent that sends metrics for our normal APM UI.
https://github.com/newrelic/newrelic-opentelemetry-java
This agent sets `instrumentation.provider` to `newrelic-opentelemetry` and the UI uses this as the signal to indicate which views to render.
We want to generate an `entity.guid` for this agent, hence the PR.
cc @erabug 
> Add entity definition for New Relic OpenTelemetry distribution

- definitions/ext-aws_elemental/golden_metrics.yml
- definitions/ext-aws_elemental/summary_metrics.yml
This entity does not report a cpu %, it reports a count of items in the processor queue. Matched GM query to dashboard query.
> fix: swap CPU % with processorLoad

- definitions/ext-ups/definition.yml
- definitions/ext-ups/golden_metrics.yml
- definitions/ext-ups/kentik-apc_ups-dashboard.json
- definitions/ext-ups/kentik-ups-dashboard.json
- definitions/ext-ups/kentik-vertiv_ups-dashboard.json
Updating the existing `EXT_UPS` entity dashboards to align with consistent styling in other network entities. 
Also adding new telemetry source `instrumentation.name: vertiv-ups` to the definition.
> chore: update EXT_UPS entity dashboards

- definitions/infra-kubernetes_persistentvolume/summary_metrics.yml
Rearrange + add a new attribute to the summary metrics for K8s `PersistentVolume` entity. 
> Add new attribute to K8s PersistentVolume summary metrics

- definitions/ext-environment_sensor/golden_metrics.yml
Adding the default provider to the GM definition to capture entities that don't match any other `instrumentation.source/instrumentation.name` pattern
> chore: add default provider to GM definition

- definitions/infra-kubernetes_cronjob/dashboard.json
- definitions/infra-kubernetes_job/dashboard.json
Currently, we only have status states `Failed` and `Complete`. Assuming that a job can only have a third state `Running` ignores the fact that we could be in `Unknown` state if nothing gets reported.
* [y] I've read the guidelines and understand the acceptance criteria.
* [y] The value of the attribute marked as `identifier` will be unique and valid. 
* [y] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
> Improve CronJob, Job dashboards

- definitions/synth-monitor/golden_metrics.yml
Add `unit` to each golden metric for `synth-monitor`
> Update synth-monitor golden_metrics.yml

- definitions/ext-firewall/default-dashboard.json
This PR tweaks the firewall dashboard to line up better with the router and switch dashboard visual styles. Instead of having summary info in one scrollable billboard, we'll have it across 3 billboards in the top row. Also, changed the size of a couple charts
> Tweak firewall dashboard for readability

- validator/schemas/entity-schema-v1.json
We added prefixed tags in the past into our definitions & docs.
But seems we never updated the schema so if someone tries to use them like here: https://github.com/newrelic/entity-definitions/pull/1109/files
It will fail the schema validation.
This schema allows any key to be defined but the payload bust be null (for now we don't allow any configuration on the prefixed tags)
> Allow to configure prefixedTags into the definitions

- definitions/ext-service/golden_metrics.yml
sum(apm.service.error.count) for NR Otel distro because counters are broken in Dirac.
For timeslice blobs in Dirac, count() sums the count column, and sum() sums the total column.  For counter metrics, count() is the # of data points, and sum() is the sum of the counts.  It's sad.  Anyway, this will fix the error rate for the new NR Otel distro agent.
But!  It's almost working!
> sum(apm.service.error.count) for NR Otel distro

- definitions/browser-micro_frontend/definition.yml
- definitions/browser-micro_frontend/golden_metrics.yml
- definitions/browser-micro_frontend/summary_metrics.yml
- Updated the attribute to match the entity synthesis to something that can be shared between all the different event types (MicroFrontendView, MicroFrontendLoadTiming, MicroFrontendJavaScriptError, etc.).
- Added the Golden Metrics definition for the entity type
- Added the Summary Metrics definition for the entity type pointing to the Golden Metrics definitions.
> feat: Update Micro Frontend synthesis rules and add golden metrics

- definitions/ext-firewall/pulse-secure-dashboard.json
The query below has mismatched brackets (the `}` should be a `)`) and a missing comma
> Fix dashboard typo

- relationships/synthesis/INFRA-HOST-to-INFRA-KUBERNETES_POD.yml
Add relationship from infra-host into k8s pod.
> Add host to k8s pod relationship

- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE-AMQP.yml
- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE-CASSANDRA.yml
- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE-KAFKA.yml
- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE-MYSQL.yml
- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE-POSTGRES.yml
- relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_REDIS.yml
- relationships/synthesis/INFRA-HOST-to-EXT-SERVICE.yml
Bring another batch of rules into the public repo.
The two main things to note are:
- otelServiceHost is currently generating relationships from tracing but nothing from otel, so we only neabled the tracing origin.
- otelServiceHostMetric has a condition by `service.name` I believe that was for testing and was never removed, I'm following up with the team owning that relationship but for now we are migrating them as-is
> Migrate another batch of rules

- relationships/synthesis/APM-APPLICATION-to-INFRA-REDISINSTANCE.yml
Create a relationship of APM apps calling redis instances.
Uses the Spans from distributed tracing to detect when an app calls a redis db.
> Bring apm calls redis instance relationship

- entity-types/infra-host/definition.yml
Needs to be tested in staging before releasing
Changing entity name from host.id to host.name for OTEL hosts
> NR-142172: Use host.name for the entity name 

- relationships/synthesis/APM-APPLICATION-to-DATABASE.yml
Regex is wrongly crafted and makes the system fail
this should be detected automatically once we add the engine for tests so I don't think a new validator is needed.
> remove not needed parenthesis

- relationships/synthesis/INFRA-HOST-to-INFRA-KUBERNETES_POD.yml
Attempt to fix the rule for k8sHostContainsPod.
> Update k8sHostContainsPod entityType

- entity-types/ext-pdu/definition.yml
- entity-types/ext-pdu/golden_metrics.yml
updating the order of filtering on the PDU entity to move the "catchall" to the end on dashboard and GM
> chore: re-order to put generic filter last

- relationships/synthesis/APM-APPLICATION-to-INFRA-REDISINSTANCE.yml
Bring the rule again that we removed in: https://github.com/newrelic/entity-definitions/pull/1174
So we can switch systems to create relationships for APM.
For the team:
The internal rule we used for testing is named `apmApplicationCallsInfraRedisInstanceAPMVersion` and is not present on our FF's
This means that is currently creating relationships, once we switch from the internal to the public version no relationships will be created without this PR.
So we need to have the rule defined & also need to remove it from all existing FF's.
> Add APM-APPLICATION-to-INFRA-REDISINSTANCE again

- relationships/synthesis/INFRA-HOST-to-INFRA-KUBERNETES_POD.yml
We migrated the rule correctly internally but when moving into the public repo we changed to `entity.guid` by mistake
> Fix k8sHostContainsPod rule

- docs/entities/synthesis.md
Small docs update on revised tag rule precedence in synthesis.
Explicit definitions are now evaluated first and implicit conventions are applied later on if no explicit definitions matched.
n/a
> Reflecting tag rule precedence change in our docs

- entity-types/ext-key_transaction/golden_metrics.yml
Key Transaction Errors are supposed to be a measured in `percentage` but queried as `count`
> Key Transaction Error %

- entity-types/ext-package/definition.yml
I found an error in the previous [PR](https://github.com/newrelic/entity-definitions/pull/1232/files) for OTEL packages. This PR fixes it.
> fix: use correct entity name for OTEL packages

- relationships/synthesis/INFRA-HOST-to-EXT-PACKAGE.yml
This is another fix for the package entity definition. This time, I'm trying to fix the relationship synthesis rule.
> fix: use account attribute in the package relationship

- entity-types/infra-redisinstance/definition.yml
Temporary debugging PR: It looks like otel ingest only takes strings into account. This commit is to test this assumption.
Not intended to go to prod.
> Redis Instance - Use a string field for the composite identifier temporarily.

- entity-types/infra-redisinstance/definition.yml
Reverts newrelic/entity-definitions#1240
> Revert "Redis Instance - Use a string field for the composite identifier temporarily."

- relationships/synthesis/APM-APPLICATION-to-INFRA-MSSQLINSTANCE.yml
Adding the relationship APM<->MSSQL 
Note: this rule match only when the MSSQL Instance name defined in the database is equal to the lower cases hostname of that instance.
> feat: add mssql relationship match (hostname==instance)

- entity-types/infra-awselasticacheredisnode/golden_metrics.yml
AWS Elasticache Redis Node swap was a %, but it's bytes.
AWS Elasticache Redis Node Swap Usage [should be `BYTES`](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.WhichShouldIMonitor.html#metrics-swap-usage), but it's currently `PERCENTAGE`.
> Fix unit: AWS EC Redis Node swap usage

- entity-types/infra-azurefunctionsapp/definition.yml
Create tag providerAccountName and newrelic.cloudIntegrations.providerAccountName from newrelic.cloudIntegrations.providerAccountName:
Rename newrelic.cloudIntegrations.providerAccountName to providerAccountName and keep newrelic.cloudIntegrations.providerAccountName
Azure polling provides the tag providerAccountName, while Azure Monitor newrelic.cloudIntegrations.providerAccountName
This tag rename aims to have both values tagged as providerAccountName. It should apply to all rules.
> Fixes #1239, correct tag renaming

- entity-types/infra-host/golden_metrics.yml
This PR is to update several prometheus golden metrics so that these metrics will actually calculate values for customers.
Prometheus CPU usage golden metric had a condition where the value was used in a way that could lead to a divide by zero instance. Added a where clause to prevent this from occurring.
Prometheus memory usage and storage usage both needed to utilize two different metrics to compute the value. We have created a script that will precompute these values on the host and can be sent in via the prometheus node_exporter using a textfile collector. With this, both metrics can be simplified to a single value.
> Updating INFA-HOST golden metric definitions for prometheus.

- entity-types/ext-rservicev2/dashboard.json
- entity-types/ext-rservicev2/definition.yml
- entity-types/ext-rservicev2/golden_metrics.yml
- entity-types/ext-rservicev2/summary_metrics.yml
New entity-type (similar to entity ext-rservice) for specific services that have a different source for its golden metrics.
> New entity-type for products with different golden metric sources

- relationships/candidates/HOST.yml
Add matching rules for non-cloud hosts.
It is part of the effort to collect more metrics on uninstrumented relationships. 
Based on the reference definition from the hardcoded rules ([link](https://source.datanerd.us/entity-platform/entity-fingerprint-definitions/blob/master/src/main/resources/fingerprints/hosts.yml#L17)).
Internal links:
- https://issues.newrelic.com/browse/NR-165879
> [NR-165879] Add matching rules for non-cloud hosts

- relationships/candidates/HOST.yml
This reverts commit eebc9d00da19d11a46442d85ac19b37b7895f38a.
Reverts add matching rules for non-cloud hosts.
> Revert "[NR-165879] Add matching rules for non-cloud hosts (#1263)"

- relationships/candidates/AWSRDSDBCLUSTER.yml
- relationships/synthesis/INFRA-AWSRDSDBCLUSTER-to-INFRA-AWS_RDS_DB_INSTANCE.yml
This reverts commit 0c8c576674e5144de0292cce0a386936e57e1e4c.
Adds back relationships for AWS RDS Cluster/Instance: https://github.com/newrelic/entity-definitions/pull/1146
> Add back relationship for AWS RDS Cluster/Instance (#1146)

- entity-types/ext-kentik_ping/summary_metrics.yml
fixing a tag name on the summary metric for `EXT-KENTIK_PING`
> fix: update tag name for SM

- relationships/synthesis/INFRA-AWSRDSDBCLUSTER-to-INFRA-AWSRDSDBINSTANCE.yml
Added underscore entity.type for rds cluster <> instance relationship.
> Add entity.type with underscores for rds definition

- entity-types/ext-rservicev2/definition.yml
Initially, as part of the ext-rservicev2 entities, only raw metrics were declared - this PR will also include logs as well.
> Include log events as part of rservicev2

- relationships/candidates/HOST.yml
This reverts commit 3839662fc01e4a2c2ec9090d93307d7b050a3a64.
Remove hosts non-cloud rule included here: https://github.com/newrelic/entity-definitions/pull/1275
> Revert "[NR-165879] Add matching rules for non-cloud hosts (#1275)"

- entity-types/ext-service/golden_metrics.yml
This updates one golden metrics query to use the new NRDB `convert` function to convert the measurement to `ms` instead of assuming the unit is in `s`.  This only applies when the `instrumentation.provider` is `newrelic.opentelemetry`.  We do not have any production agents reporting this configuration.  We are started to alpha test this with a small handful of customers.  The risk is very low.
Before deploying this change to production, we need to verify that the NRDB team has enabled the `convert` function in the production environment.
https://docs.google.com/document/d/1nuRiK9HM-x2d52mtMLuiPUkSUzONfKFtTFFmRpOocoU/edit?usp=sharing
> Use the convert function for newrelic-opentelemetry data

- entity-types/infra-host/definition.yml
Updating `entityExpirationTime` for INFRA-HOST entities to 8 days.
> fix: Update infra-host entityExpirationTime from daily to 8 days

- entity-types/infra-apacheserver/newrelic_dashboard.json
This PR updates the Apache dashboard to use the ApacheSample instead of Metric.
> Update Apache dashboard to use samples

- entity-types/infra-cassandranode/newrelic_dashboard.json
This PR updates the Cassandra dashboard to use the CassandraSample instead of Metric.
> Convert dashboard back to sample

- entity-types/mobile-application/golden_metrics.yml
Siva would like to use dimensional metrics (NRDB) instead of our legacy timeslice metrics that are exposed in NRQL through MTQW.  One of the easier products to update is mobile because many of the metrics are generated in backend service(s) instead of in agents.  Many mobile timeslice metrics have been mapped to dimensional metrics in MTQW:
https://source.datanerd.us/collector-collective/metric-timeslice-query-worker/blob/master/mtqw-dimensional-metrics/src/main/resources/com/newrelic/dimensionalmetricbridge/metricformat/mobile-dimensional-metrics.csv
https://source.datanerd.us/collector-collective/metric-timeslice-query-worker/blob/master/mtqw-dimensional-metrics/src/main/resources/com/newrelic/dimensionalmetricbridge/metricformat/mobile-exact-metrics.csv
This document provides more …
> Use apm.mobile.* metrics

- entity-types/infra-host/golden_metrics.yml
Updated prometheus select based on recommendations in this [slack thread](https://newrelic.slack.com/archives/C0446Q75V7E/p1704810845334949?thread_ts=1703005436.571799&cid=C0446Q75V7E). Should resolve an issue where the order of operations within the select were causing incorrect calculations.
> fix: Prometheus cpuUsage query select

- entity-types/infra-host/definition.yml
As per [this thread](https://newrelic.slack.com/archives/C05888HE0QK/p1702999430090749?thread_ts=1702498776.806249&cid=C05888HE0QK) we're adding `overrideGuidType` for prometheus hosts.
> Feat: overrideGuidType for prometheus hosts

- relationships/candidates/CONTAINER.yml
Include `docker.shortContainerId` tag in `CONTAINER`'s candidate definition.
This way we will be able to also find the container when the provided id is the short one.
By the way, I've checked that 100% of docker container entities that have the `docker.containerId` tag also have the `docker.shortContainerId` one.
> Include short container id tag in candidate definition

- docs/entities/guid_spec.md
The regular expression for the type field requires at least 3 characters, but the NA type only has 2. The documentation needs to be updated to reflect this requirement
> Update the GUID Spec Regex For the Type

- entity-types/infra-host/definition.yml
Removed the `newrelicOnly` attribute from the entity synthesis conditions for Prometheus hosts. This should enable Prometheus hosts in production
> Feat: Enable Prometheus hosts in production

- entity-types/infra-nginxserver/golden_metrics.yml
> Remove metric queries from nginxserver golden metrics

- entity-types/infra-host/golden_metrics.yml
> Remove metric queries from host golden metrics

- entity-types/infra-apacheserver/golden_metrics.yml
> Remove metric queries from apacheserver golden metrics

- entity-types/infra-cassandranode/golden_metrics.yml
> Remove metric queries from cassandranode golden metrics

- entity-types/infra-elasticsearchnode/golden_metrics.yml
> Remove metric queries from elasticsearchnode golden metrics

- entity-types/infra-f5node/golden_metrics.yml
> Remove metric queries from f5node golden metrics

- entity-types/infra-memcachedinstance/golden_metrics.yml
> Remove metric queries from memcachedinstance golden metrics

- entity-types/infra-f5pool/golden_metrics.yml
> Remove metric queries from f5pool golden metrics

- entity-types/infra-f5virtualserver/golden_metrics.yml
> Remove metric queries from f5virtualserver golden metrics

- entity-types/infra-kafkabroker/golden_metrics.yml
> Remove metric queries from kafkabroker golden metrics

- entity-types/infra-kubernetes_cronjob/golden_metrics.yml
> Remove metric queries from kubernetes_cronjob golden metrics

- entity-types/infra-kubernetes_deployment/golden_metrics.yml
> Remove metric queries from kubernetes_deployment golden metrics

- entity-types/infra-kubernetes_job/golden_metrics.yml
> Remove metric queries from kubernetes_job golden metrics

- entity-types/infra-kubernetes_persistentvolume/golden_metrics.yml
> Remove metric queries from kubernetes_persistentvolume golden metrics

- entity-types/infra-kubernetes_statefulset/golden_metrics.yml
> Remove metric queries from kubernetes_statefulset golden metrics

- entity-types/infra-mssqlinstance/golden_metrics.yml
> Remove metric queries from mssqlinstance golden metrics

- entity-types/infra-mysqlnode/golden_metrics.yml
> Remove metric queries from mysqlnode golden metrics

- entity-types/infra-oracledbinstance/golden_metrics.yml
> Remove metric queries from oracledbinstance golden metrics

- entity-types/infra-rabbitmqnode/golden_metrics.yml
> Remove metric queries from rabbitmqnode golden metrics

- entity-types/infra-rabbitmqqueue/golden_metrics.yml
> Remove metric queries from rabbitmqqueue golden metrics

- entity-types/infra-redisinstance/golden_metrics.yml
> Remove metric queries from redisinstance golden metrics

- entity-types/infra-vspherecluster/golden_metrics.yml
> Remove metric queries from vspherecluster golden metrics

- entity-types/infra-vspheredatacenter/golden_metrics.yml
> Remove metric queries from vspheredatacenter golden metrics

- entity-types/infra-vspherehost/golden_metrics.yml
> Remove metric queries from vspherehost golden metrics

- entity-types/infra-rabbitmqexchange/golden_metrics.yml
> Remove metric queries from rabbitmqexchange golden metrics

- entity-types/infra-postgresqlinstance/golden_metrics.yml
> Remove metric queries from postgresqlinstance golden metrics

- entity-types/infra-vspherevm/golden_metrics.yml
> Remove metric queries from vspherevm golden metrics

- entity-types/ext-billable_user/definition.yml
-Adding `userId` as tag to user entity type
> feat: add `userId` as tag to billable_user entity type

- entity-types/infra-host/definition.yml
The PR is adding the host.id tag, that is the unique identifier of the HOST needed for creating relationships when the otel-collector is deployed in a Cloud VM (ie. EC2)
> infra-host: add host.id tag

- entity-types/infra-kubernetes_deployment/definition.yml
Adds synthesis of K8s Deployments from `kube-state-metrics` received via OTel endpoint.
> feat: Synthesis deployment from ksm->otel

- entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
Adds synthesis of K8s PersistentVolumeClaim from kube-state-metrics received via OTel endpoint.
> feat: K8s pvc synthesis from ksm->otel

- entity-types/infra-kubernetes_persistentvolume/definition.yml
Adds synthesis of K8s PersistentVolume from kube-state-metrics received via OTel endpoint.
> feat: K8s persistentvolume synthesis from ksm->otel

- entity-types/infra-kubernetes_job/definition.yml
Adds synthesis of K8s Jobs from kube-state-metrics received via OTel endpoint.
> feat: K8s job synthesis from ksm->otel

- entity-types/infra-kubernetes_cronjob/definition.yml
Adds synthesis of K8s CronJobs from kube-state-metrics received via OTel endpoint.
> feat: K8s cronjob synthesis from ksm->otel

- entity-types/infra-kubernetes_statefulset/definition.yml
Adds synthesis of K8s StatefulSets from kube-state-metrics received via OTel endpoint.
> feat: K8s statefulset synthesis from ksm->otel

- entity-types/infra-kubernetes_daemonset/definition.yml
Adds synthesis of K8s Containers from kube-state-metrics received via OTel endpoint.
> feat: K8s daemonset synthesis from ksm->otel

- entity-types/infra-kubernetes_pod/definition.yml
Adds synthesis of K8s Pods from kube-state-metrics received via OTel endpoint.
> feat: K8s pod synthesis from ksm->otel

- entity-types/infra-awsprivatelinkservice/definition.yml
- entity-types/infra-awsprivatelinkservice/golden_metrics.yml
- entity-types/infra-awsprivatelinkservice/summary_metrics.yml
> AWS PrivateLink Service

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_PERSISTENTVOLUME.yml
Adds synthesis of K8s Cluster-PersistentVolume relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-persistentvolume relation from ksm->otel

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_PERSISTENTVOLUMECLAIM.yml
Adds synthesis of K8s Cluster-PeristentVolumeClaim relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-pvc relation from ksm->otel

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_DAEMONSET.yml
Adds synthesis of K8s Cluster-Daemonset relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-daemonset relation from ksm->otel

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_DEPLOYMENT.yml
Adds synthesis of K8s Cluster-Deployment relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-deployment relation from ksm->otel

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_STATEFULSET.yml
Adds synthesis of K8s Cluster-Statefulset relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-statefulset relation from ksm->otel

- entity-types/ebpf-client/definition.yml
- entity-types/ebpf-client/tests/Span.json
- entity-types/ebpf-redis_server/definition.yml
- entity-types/ebpf-redis_server/tests/Span.json
- relationships/candidates/EBPFCLIENT.yml
- relationships/candidates/EBPFSERVER.yml
- relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml
This PR provides initial prototype entity definitions for the eBPF agent.
Main ideas:
1. Construct guid from self information, e.g. the “local” IP addr., port, and pid.
2. Enable relationship synthesis from tags that include local IP addr. and port, i.e. because those columns will be available as “remote IP addr. & port”
Note that in the agent, one span represents both a request and response. Currently, *we cannot create two entities from a single span with NR synthesis rules*. We can, however, trace a span from the client’s perspective and from the server’s point of view, as long as the ebpf agent is deployed on all hosts. Thus for entity and relationship synthesis, we can connect these two spans, one client-side and one server-side. If one side of the connection is missing, we create an …
> Entity relationship synthesis with the `New Relic eBPF agent`

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_POD.yml
Adds synthesis of K8s Cluster-Pod relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-pod relation from ksm->otel

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_CRONJOB.yml
Adds synthesis of K8s Cluster-CronJob relationship from kube-state-metrics received via OTel endpoint.
> feat: K8s cluster-cronjob relation from ksm->otel

- entity-types/nr1-fleet/definition.yml
We are add this change because currently our entity list doesn't show on the all entities. We already made relevant change on the entity-type-ui-definition-service
* [ x] I've read the guidelines and understand the acceptance criteria.
* [x ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.
> feat(fleet): Switch fleet to be alertable

- entity-types/infra-kubernetes_cronjob/definition.yml
- entity-types/infra-kubernetes_daemonset/definition.yml
- entity-types/infra-kubernetes_deployment/definition.yml
- entity-types/infra-kubernetes_job/definition.yml
- entity-types/infra-kubernetes_persistentvolume/definition.yml
- entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
- entity-types/infra-kubernetes_statefulset/definition.yml
A tag remapping for golden tag on OS instrumented K8s workloads, persistentvolume, pvc.
> feat: Add renaming for golden tags in OS K8s entities

- entity-types/ebpf-client/definition.yml
Enables debug mode for ebpf-client rule. It should allow us to dig deeper into the matching rules affecting this domain/type.
> Debug ebpf-client rule

- entity-types/ebpf-client/definition.yml
- entity-types/ebpf-client/tests/Span.json
- entity-types/ebpf-redis_server/definition.yml
- entity-types/ebpf-redis_server/tests/Span.json
- relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml
Entity synthesis for ebpf data based on the `span.kind` column (which is an [enum](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) ([sdk docs](https://open-telemetry.github.io/opentelemetry-js/enums/_opentelemetry_otlp_transformer.ESpanKind.html#SPAN_KIND_CLIENT)) is currently not working due to a known issue where the engine doesn’t support numbers (https://new-relic.atlassian.net/browse/NR-164291).
This PR changes the entity defs to use a new column 'trace_role' which is set to the strings "server" and "client". It also adds quotes missing around the value for `instrumentation.provider` in the client definition.
> Ebpf entity defs: change span.kind to trace_role

- entity-types/infra-kubernetes_persistentvolume/golden_metrics.yml
Add Kubernetes persistentvolume golden metric queries for kube-state-metrics -> OpenTelemetry
> feat: Golden metrics for OS k8s persistentvolume

- entity-types/infra-kubernetes_cronjob/golden_metrics.yml
Add Kubernetes cronjob golden metric queries for kube-state-metrics -> OpenTelemetry
> feat: Golden metrics for OS k8s cronjob

- entity-types/infra-kubernetes_pod/golden_metrics.yml
Add Kubernetes pod golden metric queries for kube-state-metrics -> OpenTelemetry
> feat: Golden metrics for OS k8s pod

- relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml
Changes `EBPF_CLIENT` to `CLIENT` and adds `instrumentation.provider`. Also removes a redundant condition `trace_role` which is captured by `entity.type`
> Update ebpf client to redis server relationship rule

- relationships/synthesis/EBPF-CLIENT-to-EBPF_REDIS.yml
Don't use entity type in EBPF relationships rule and use the `trace_role` (as it's done in entity synthesis) instead.
> Don't use entity type in EBPF relationships rule

- entity-types/infra-kubernetes_daemonset/golden_metrics.yml
Add Kubernetes daemonset golden metric queries for kube-state-metrics -> OpenTelemetry
> feat: Golden metrics for OS k8s daemonset

- entity-types/infra-container/golden_metrics.yml
Adds support for K8s Infra-Container golden metrics via OpenTelemetry [kubeletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver). Uses `or` to support this and related values provided by `dockerstatsreceiver` which are alternatively available outside K8s context.
> feat: CpuUtilization, memoryUsage, storageUsage using otel kubeletstats

- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_CRONJOB.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_DAEMONSET.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_DEPLOYMENT.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_JOB.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_PERSISTENTVOLUME.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_PERSISTENTVOLUMECLAIM.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_POD.yml
- relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-INFRA-KUBERNETES_STATEFULSET.yml
- relationships/synthesis/INFRA-KUBERNETES_CRONJOB-to-INFRA-KUBERNETES_JOB.yml
- relationships/synthesis/INFRA-KUBERNETES_DAEMONSET-to-INFRA-KUBERNETES_POD.yml
- relationships/synthesis/INFRA-KUBERNETES_JOB-to-INFRA-KUBERNETES_POD.yml
- relationships/synthesis/INFRA-KUBERNETES_PERSISTENTVOLUME-to-INFRA-KUBERNETES_PERSISTENTVOLUMECLAIM.yml
- relationships/synthesis/INFRA-KUBERNETES_STATEFULSET-to-INFRA-KUBERNETES_POD.yml
OS K8s relationships have had condition that required attribute `eventType` to have value of `Metric`. OTel metrics do not have an `eventType` attribute similar to Event Samples. This removes that condition.
> fix: OS K8s relations not require eventType Metric

- relationships/synthesis/INFRA-KUBERNETES_DEPLOYMENT-to-INFRA-KUBERNETES_POD.yml
Unlike other K8s workloads (e.g. StatefulSets, DaemonSets) which directly create K8s Pods, K8s Deployments create K8s ReplicaSets which create K8s Pods.
The Deployment<->Pod relationship is therefore not included the in the KSM `kube_pod_owner` metric the same way that it is for other workloads (the owner name is for the ReplicaSet, rather than what we think of as the workload). There is a second metric (`kube_replicaset_owner`) that includes the deployment name. However, we can't join these two metrics in this streaming context. Therefore, this PR takes advantage of the fact that K8s has a defined naming convention where the replicaset is named by appending a hash to the deployment name. For example, if the deployment name was `small-apple-tree` the replicaset might be …
> fix: Use capture to get deployment part of replicaset name when building relation source guid

- entity-types/infra-kubernetes_persistentvolume/definition.yml
Synthesis for OpenTelemetry instrumented K8s PersistentVolumes was requiring a `namespace` attribute. Unlike most other K8s resources, PersistentVolumes do not have a namespace. This removes that requirement and adjusts the guid encoding to reflect that.
> fix: PersistentVolume synthesis should not require namespace

- relationships/synthesis/INFRA-KUBERNETES_POD-to-INFRA-CONTAINER.yml
Adds relationship synthesis for K8s Pod <-> Container relationship derived from kube-state-metrics telemetry received via OpenTelemetry.
> feat: K8s pod-container relation from KSM via OTel

- entity-types/ext-pixie_dns/tests/Metric.json
- entity-types/ext-pixie_dns/tests/Span.json
After an upgrade in the validator service (fixing a bug that prevented some checks to be performed), the validation of `EXT-PIXIE_DNS` started to fail because the test data is incorrect.
> Fix EXT-PIXIE_DNS test data

- entity-types/infra-kubernetes_pod/definition.yml
- entity-types/infra-kubernetes_pod/tests/Span.json
The existing rule does not create k8s pod entities from ebpf data. 
In particular, we're missing `metricName` and we have `service.name` set to the `local_addr` (which is supposed to not be present in the current rule).
> EBPF entities <> Kubernetes: Add new entity def rule for k8s pods from ebpf data (depends on #1551)

- entity-types/infra-host/definition.yml
`host.id` is a required tag for host-apm relationships
> feat: Add instanceid and host.id tags for prometheus on a host

- entity-types/infra-kubernetes_persistentvolume/definition.yml
Add remapping of golden tags for KSM based K8s PersistentVolumes – `k8s.persistentvolume.statusPhase`, `k8s.pvcNamespace`, `k8s.pvcName` and `k8s.persistentvolume.storageClass`.
> feat: Golden tags for OS K8s PersistentVolume

- entity-types/infra-kubernetes_deployment/definition.yml
- relationships/candidates/KUBERNETES_DEPLOYMENT.yml
- relationships/synthesis/INFRA-KUBERNETES_DEPLOYMENT-to-INFRA-KUBERNETES_POD.yml
Synthesizes a K8s Pod <-> Deployment relation using OpenTelemetry data from kube-state-metrics.
Deployments own ReplicaSets which in turn own Pods. This is a level deeper relationship than other K8s workloads (e.g. StatefulSets own Pods; Daemonsets own Pods). In order to achieve this relationship:
- Adds rule to deployment synthesis which uses [kube_replicaset_owner](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/replicaset-metrics.md#replicaset-metrics) to add `k8s.replicasetName` tag to deployment.
- Adds `KUBERNETES_DEPLOYMENT` relationship candidate which maps tags to `replicaset`, `namespace` and `cluster` fields.
- Adds relationship rule which uses [kube_pod_owner](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md#pod-metrics) with …
> feat: OS K8s deployment-pod relation using candidate lookup

- docs/entities/synthesis.md
- validator/schemas/entity-schema-v1.json
Make it possible to define a TTL for `prefixedTags` in entity synthesis definitions.
This way it's possible make these tags to expire when the tag is nor reported in a given period of time.
> Include TTL for prefixed tags

- entity-types/browser-application/golden_metrics.yml
- entity-types/browser-application/summary_metrics.yml
The Browser team is rolling out its support for [Interaction to Next Paint](https://web.dev/articles/inp), the Core Web Vital metric that has been recently released. We're in the process of replacing all First Input Delay metrics with that of INP, as it was chosen to be its replacement.
This PR replaces FID metrics with equivalent INP metrics on the Browser Entity Summary table to reflect our incorporation of the new standard.
- Ticket: https://new-relic.atlassian.net/browse/NR-249585
- INP Product Brief: https://newrelic.atlassian.net/wiki/spaces/APPEXP/pages/2764505110/Product+Brief+-+Interaction+to+Next+Paint
> feat(Browser): Change FID metrics to INP (NR-249585)

- entity-types/infra-container/definition.yml
Adds tags to synthesis rules for OS K8s containers synthesis from kube-state-metrics, cAdvisor & kubletstatsreceiver.
> feat: Add tags for OS K8s containers

- entity-types/infra-kubernetes_deployment/definition.yml
- entity-types/infra-kubernetes_deployment/tests/k8s-ksm-via-opentelemetry-prometheus-receiver.json
Corrects attribute used for name in OS K8s deployment synthesis from `kube_replicaset_owner` – should be `owner_name`. Adds test data to validate synthesis rules.
> Os k8s deployment pod lookup

- entity-types/infra-container/definition.yml
- entity-types/infra-kubernetes_cronjob/definition.yml
- entity-types/infra-kubernetes_daemonset/definition.yml
- entity-types/infra-kubernetes_deployment/definition.yml
- entity-types/infra-kubernetes_job/definition.yml
- entity-types/infra-kubernetes_persistentvolume/definition.yml
- entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
- entity-types/infra-kubernetes_pod/definition.yml
- entity-types/infra-kubernetes_statefulset/definition.yml
Add useNonStandardAttributes to new infra k8s definitions
> Add useNonStandardAttributes to new infra k8s definitions

- entity-types/infra-host/definition.yml
We recently added support for opentelemetry hosts with the `service.name` attribute (https://github.com/newrelic/entity-definitions/pull/1527).  However `service.name` was not added as a tag to be copied from telemetry to the entity.  
This PR adds the `service.name` attribute as a tag to infra-host entities that are synthesized following the rules introduced in https://github.com/newrelic/entity-definitions/pull/1527
> Add service.name tag for explicitly defined infra hosts (otel)

- entity-types/ext-load_balancer/a10-thunder-dashboard.json
fixing the netmon load balancers dashboard for a10 devices to account for some situations where a single metric isn't being reported by the device
> chore: update nrql to account for bespoke missing metrics

- entity-types/uninstrumented-kafkatopic/definition.yml
- relationships/candidates/KAFKATOPIC.yml
- relationships/synthesis/APM-APPLICATION-to-KAFKATOPIC.yml
This change makes the uninstrumented entities for Kafka topics independent from MSK. In the same way we have an uninstrumented database entity instead of an uninstrumented RDS entity. We need this to support other Kafka providers in the future.
> Rename AWSMSKTOPIC candidate relationships to KAFKATOPIC

- relationships/candidates/HOST.yml
- relationships/synthesis/INFRA-VSPHEREVM-to-INFRA-HOST.yml
This PR introduces back the relationship defined in #1616, but this time it creates _uninstrumented_ HOST entities on miss.
> feat: add optional VSPHEREVM to HOST relationship

- entity-types/infra-kubernetes_pod/definition.yml
We want to be able to create OTel service entities from the eBPF agent data if the attribute `service.name` is present. The current rule seems to be matching against all data we export from the agent even if we provide a `service.name` since the rule only checks for relevant k8s metadata. This PR adds a condition to make sure that a k8s pod entity is created from the eBPF agent only if `service.name` is not present.
> Add condition to make sure `service.name` is not present in eBPF data when creating a pod entity

- entity-types/ext-dbt_failed_resource_run/definition.yml
- entity-types/ext-dbt_failed_test_row/definition.yml
- entity-types/ext-dbt_job_run/dashboard.json
- entity-types/ext-dbt_job_run/definition.yml
[Dbt](https://www.getdbt.com/) is a data transformation tool that comes in both cloud and open source versions. It is used by many companies in analytics and data engineering.
These entities allow observability for dbt job runs, failed models/tests, and failed test rows. The primary purpose of these entities is to generate alerts and notifications with custom descriptions and simple summary dashboards. Without these entities, we would need to resort to faceting and that makes the notifications unreadable. All entities are short lived (8 day retention)
Definitions:
* DBT_JOB_RUN: A set of data transformations and tests that are run in a DAG 
* DBT_FAILED_RESOURCE_RUN: A single task from the DBT_JOB_RUN that failed
* DBT_FAILED_TEST_ROW: A single instance of a row in a database that failed …
> Add id tags for dbt_job_run dashboard. Fix golden tags

- relationships/candidates/AWSMQBROKER.yml
Corrected the type name for uninstrumented entity to be created on lookup miss through the candidate definition
> Corrected the uninstrumented type name in candidate

- entity-types/ext-trap_device/kentik-trap-events-dashboard.json
fix to update the facet on the dashboard from `TrapName` (deprecated) to the proper `TrapOID` attribute.
> fix: update facet to proper attribute

- entity-types/ext-trap_device/golden_metrics.yml
fixes a typo in the `instrumentation.provider/instrumentation.name` selector on the golden metrics definition that was breaking signal creation.
> fix: instrumentation.name selector on gm

- entity-types/ext-service/definition.yml
Adds an explicit entity synthesis rule for data collected by the NR eBPF agent in order to populate `k8s.` tags. Previously, eBPF data matched the most generic rule.
> Add `EXT-SERVICE` rule for data from eBPF agent

- relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
Updated the attribute names in the relationship file as per span data.
Updated the regular expression to capture broker name and region. It now matches the AWS broker URL folloed my any string. This is because python instrumentation records the broker url enclosed in double quotes ("<broker_url>").
Also changed the origin to open telemetry.
> Bugfix for Otel to AWS MSK relationship

- entity-types/infra-awsvpcvpntunnel/golden_metrics.yml
Fix AWS VPC VPN not showing golden metrics in entity explorer since Wrong aggregater had used. Updated the aggregator to sum() in VPC VPN Tunnel entity
>  AWS VPC VPN not showing golden metrics in entity explorer

- entity-types/uninstrumented-host/definition.yml
Move UNINSTRUMENTED-HOST expiration to eight days for data analysis on uninstrumented data.
> Move UNINSTRUMENTED-HOST expiration to eight days

- entity-types/ext-service/definition.yml
This rule is no longer necessary. It was introduced in #1004 in support of a prototype that we do not plan on advancing.
> Remove ext-service rule for newrelic-opentelemetry provider

- entity-types/ext-service/definition.yml
The rule modified in this PR should behave identically to the following rule - namely the entity tags applied should be the same between the two rules. Both rules support OpenTelemetry.
https://github.com/newrelic/entity-definitions/blob/8e618b24a77a85db6dba6a0f5f3c49e3cae37d7e/entity-types/ext-service/definition.yml#L39-L62
> Update OTel-related ext-service rule

- entity-types/uninstrumented-host/definition.yml
Move UNINSTRUMENTED-HOST expiration back to 4 hours after the data analysis was completed.
> Move UNINSTRUMENTED-HOST expiration back to 4 hours

- entity-types/infra-host/definition.yml
- relationships/synthesis/INFRA-HOST-to-INFRA-KUBERNETES_POD.yml
- Infra Host synthesis rule missing k8s.cluster.name tag for entities that are k8s Otel Hosts added new rule to capture that 
- Add Relationship for k8s Otel to infra host k8sHostContainsPodOtel
> Add synthesis rule for k8s Otel in infra Host

- relationships/candidates/CONTAINER.yml
Add a new lookup in for the CONTAINER candidate relationship definition to allow creating relationship between K8s container and Services without container id.
> feat: Add a new lookup in for the CONTAINER candidate relationship definition

- entity-types/ext-service/definition.yml
See https://new-relic.atlassian.net/browse/NR-285288.
cc @alanwest
> Stop classifying INFRA-WIN_SERVICE data as EXT-SERVICE

- relationships/synthesis/APM-APPLICATION-to-INFRA-ELASTICACHEMEMCACHEDCLUSTER.yml
The Node.js agent creates the memcached metrics without a trailing `d`. We cannot update these metric names without making a breaking change.  We have no intention of making this breaking change so this PR updates the regex to allow for the omission of the trailing `d`
> chore: Updated the regex for apm to elasticache memcached cluster to optionally allow for `Memcache` instead of `Memcached` in the metric name

- relationships/candidates/AWSAUTOSCALINGGROUP.yml
- relationships/synthesis/INFRA-AWSAUTOSCALINGGROUP-to-INFRA_AWSEC2.yml
This PR is a proxy to existing approved PR since the DEV is out on emergency vacation.
Existing Approved PR - https://github.com/newrelic/entity-definitions/pull/1722
[Description Copied from Previous PR]
Created candidate and synthesis files for AWSAUTOSCALINGGROUP to AWSEC2 relationship
as part of this story : https://new-relic.atlassian.net/browse/NR-299138
[YES] I've read the guidelines and understand the acceptance criteria.
[YES] The value of the attribute marked as identifier will be unique and valid.
[YES] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.
> [NR-299138] Added Relationships file for Autoscaling group to EC2

- relationships/candidates/AWSEC2.yml
- relationships/synthesis/INFRA-AWSAUTOSCALINGGROUP-to-INFRA_AWSEC2.yml
- relationships/synthesis/INFRA-AWSCLOUDFRONT-to-INFRA-AWSS3BUCKET.yml
Changes made to Auto-Scaling to Ec2 Relationship, Inverted the logic for extract and look-up guild.
* [ Yes] I've read the guidelines and understand the acceptance criteria.
* [ Yes] The value of the attribute marked as `identifier` will be unique and valid. 
* [ Yes] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.
> [N-239138] - Changes to AutoScaling -> Ec2 relationship 

- entity-types/uninstrumented-awslambdaalias/definition.yml
- entity-types/uninstrumented-awslambdafunction/definition.yml
Add uninstrumented definitions for awslambdaalias/awslambdafunction.
> [NR-301930] Add uninstrumented definitions for awslambdaalias/awslambdafunction

- relationships/synthesis/INFRA-AWSMSKCLUSTER-to-INFRA-AWSS3BUCKET.yml
Corrected Entity Type in AWS_MSK_CLUSTER to AWS_S3 Bucket.
Reference - https://newrelic.slack.com/archives/CH5MLECNN/p1724324396433309
* [Yes ] I've read the guidelines and understand the acceptance criteria.
* [ Yes] The value of the attribute marked as `identifier` will be unique and valid. 
* [ Yes] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.
> Corrected AWS_MSK to AWS_S3 relationship with correct entityType

- relationships/synthesis/INFRA-HOST-to-INFRA-KUBERNETES_POD.yml
- Add Relationship for k8s Otel to infra host k8sHostContainsPodOtel
> add relationship for k8s pod and host for otel

- relationships/synthesis/INFRA_KUBERNETES_CONTAINER-to-EXT_SERVICE.yml
We think that a particular service is sending the data to a different destination in Prod and EU-Prod. This PR either confirms it or discards the hypothesis.
> add origin to rule

- entity-types/report-scheduled_report/definition.yml
**Description**
This PR changes to the 'Scheduled-Report' entity which was added last week. Key updates include:
- Change of Domain: The domain has been updated from `NR1` to `REPORT`.
- Change of Type syntax: Previously, the type was declared as `type: SCHEDULED_REPORTS`. However, this resulted in a display issue in the UI, leading to the appearance of `Scheduled Reportses` because the system appended an `es` at the end. This inconsistency has been addressed and resolved in this PR.
> feat(ScheduledReport): Update entity definition for scheduled reports

- entity-types/mobile-application/golden_metrics.yml
- entity-types/mobile-application/summary_metrics.yml
GTSE https://new-relic.atlassian.net/browse/NR-309927
One customer issued a ticket because the `network error count` and the `http error rate` were not properly displayed in the UI.
In collector, they did some changes to fix the http error rate (which is fixed now, see the image) but the `network error count` should be moved to a `rate`. In fact, the metric used to determine the golden signal is already a rate. 
In collector, they started creating this new golden metric `networkFailuresRateMetric`.
> NR-309927 Fix http error metrics for mobile applicatoins

- relationships/candidates/CONTAINER.yml
Add a new lookup in for the CONTAINER candidate relationship definition to allow creating relationship between K8s container and Services without container id, using the clusterName, namespaceName, podName and containerName instead.
> feat: Add new lookup defining container candidate relationship

- entity-types/infra-awsmemorydbcluster/golden_metrics.yml
MemoryDB golden metrics are not showing up properly in the summary page. After some querying I found that getting the 'latest' value isn't working but getting the 'average' I can see the metrics. 
I'm not changing the core of the entity, just updating the queries to use average instead of latest so they appear properly.
> chore: Fix issues with memdb golden metrics

- relationships/synthesis/APM-APPLICATION-to-INFRA-KINESISSTREAM.yml
The relationship for APM and kinesis stream relies on an ARN to make the connection. The ARN pattern in the yml file doesn't seem to make what is expected. 
The current pattern is expecting a `:` after the word `stream`, but a `/` is what is expected. 
The [PR that added this file](https://github.com/newrelic/entity-definitions/pull/1774) notes in the description the expected pattern: `arn:${realm}:kinesis:${region}:${accountId}:stream/${StreamName}`
This PR updates the pattern to match.
> Update expected ARN pattern

- docs/entities/synthesis.md
- entity-types/infra-awssqsqueue/definition.yml
In this [previous PR](https://github.com/newrelic/entity-definitions/pull/1785), I introduced a synthesis rule for the `AWSSQSQUEUE` entity type that incorrectly extracted some tags. This PR fixes it and also enhances the documentation to avoid this misunderstanding.
* [-] The value of the attribute marked as `identifier` will be unique and valid. 
* [-] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.
> Fix tags in AWSSQSQUEUE entity

- entity-types/ext-nvidia_jetson/definition.yml
Removing unnecessary condition for this definition. metricName was added as a condition but it does not make sense.
> Update definition.yml to remove the metricName condition

- entity-types/media_streaming-video/definition.yml
As media streaming video agent would be ingesting `Video*` event types, We have added this definition for curating media streaming of type video entity from the telemetry being ingested by the media-streaming agents.
> Entity definition for Media streaming video type entity

- entity-types/uninstrumented-httpservice/definition.yml
- relationships/candidates/HTTPSERVICE.yml
This PR introduces a new candidate category for HTTP services and its corresponding uninstrumented entity definition.
This category will be used internally, so there won't be any synthesis rule associated to it.
> Introduce a new candidate category for HTTP services

- entity-types/infra-awsalb/definition.yml
- entity-types/infra-awselb/definition.yml
- entity-types/infra-awsnlb/definition.yml
I believe that these rules that were modified [here](https://github.com/newrelic/entity-definitions/pull/1791/files#diff-d7c8eedfd84ca7402cefbce12cfcdb6da85d3a58c49cf184915ad6f3432e16af) are having an impact to the rest of AWS synthesis rules, so I'm adding back the check for these specific attributes.
> fix: Fixes ALB, NLB and ELB definitions

- entity-types/ngep-team/definition.yml
- entity-types/ngep-teams_organization_settings/definition.yml
The `Team` and `TeamOrganizationSettings` entity type aren't alertable. The current gen [EXT-TEAM](https://github.com/newrelic/entity-definitions/blob/main/entity-types/ext-team/definition.yml) entity type isn't alertable either.
> fix(NR-313566): Team and TeamOrganizationSettings aren't alertable

- relationships/candidates/HTTPSERVICE.yml
Allow non-prefixed `endpointHostname` tag in HTTPSERVICE candidate definition.
`nr.endpointHostname` will be used for the ingest tag produced by NR.
`endpointHostname` will be used by customers to manually tag their services.
> Use non-prefixed `endpointHostname` tag in HTTPSERVICE definition

- relationships/candidates/HTTPSERVICE.yml
Fix typo in HTTPSERVICE candidate category
> Fix typo in HTTPSERVICE candidate category

- entity-types/ext-fluentbit/dashboard.json
Added more widgets to the fluent bit dashboard and removed the cluster name variable from the NRQL queries
> feat: added widgets and modified nrql queries

- entity-types/infra-awslambdafunction/definition.yml
**What is the problem the customer is trying to solve?**
There are many functions that invoke infrequently. They expect the associated entities to stick around in New Relic for at least [as long as APM entities](https://github.com/newrelic/entity-definitions/blob/19401c852e528dbbdc5a5347957b52dbf9d64b77/entity-types/apm-application/definition.yml#L34)
, which is quarterly.
**Why is it important for users that we fix that problem?**
Lambda function entities that get [deleted after 24 hours](https://github.com/newrelic/entity-definitions/blob/19401c852e528dbbdc5a5347957b52dbf9d64b77/entity-types/infra-awslambdafunction/definition.yml#L17)
lose tags and other entity-related data. It makes alerting on these entities difficult/impossible.
**What is the objective they are pursuing?**
Make …
> changed lambda expiration to quarterly

- entity-types/infra-awsec2subnet/definition.yml
- entity-types/infra-awsec2vpc/definition.yml
Added two new definitions for AWS: AWS::EC2::SUBNET and AWS::EC2::VPC
> add new AWS::EC2::SUBNET and AWS::EC2::VPC

- entity-types/infra-awssqsqueue/definition.yml
The AWSSQSQUEUE entity definition included a rule that verified that the telemetry data point was coming from an `eventType` that starts with `Log` (to be able to support data partitions such as `Log_MyDataPartition`).
Nevertheless, logs originated from CloudTrail (this is where SQS logs come from) also include an `eventType` attribute (with value `AwsApiCall`). Because the `eventType` attribute is a reserved keyword by NRDB, this attribute is removed _after_ the entity synthesis step in the Logs pipeline. However, the entity synthesis step still observes it with `eventType: AwsApiCall`.
This PR modifies the existing synthesis rules to not rely on the `eventType` attributes at all. Instead, it verifies that `eventSource` is `sqs.amazonaws.com` (this is the value set by CloudTrail to …
> fix: Fixes AWSSQSQUEUE synthesis rules

- relationships/candidates/DATABASE.yml
Also include both `endpoint` and `nr.endpoint` as lookup tags
Include all db entity types in `DATABASE` candidate category and also include both `endpoint` and `nr.endpoint` as lookup tags so (potentially) any uninstrumented db could be resolved using manual tagging.
> Include all db entity types in `DATABASE` candidate category

- relationships/synthesis/INFRA-HOST-to-EXT-FLUENTBIT_HOST.yml
- relationships/synthesis/INFRA-KUBERNETES_DAEMONSET-to-EXT-FLUENTBIT_KUBERNETES.yml
This PR attempts to change the source of telemetry of fluent bit entity relationship to allow creation of relationship
> fix: changed source of telemetry for fluent bit relationships

- entity-types/infra-host/definition.yml
This PR modifies the synthesis rule of HOST entities only for Log datapoints (feature currently not being used). The identifier of HOST entities needs to be aligned with the identifier used by the Metric Streams integration, which also uses the instanceId as the identifier as opposed to the ARN.
> fix: fix infra-host definition so it uses the EC2 instanceId as the identifier of the entity

- relationships/synthesis/APM-APPLICATION-to-DATABASE.yml
This new rule allows any hostname as DB endpoint, not limiting it to RDS.
It includes a more strict regex which only includes those providers that are supported in the `DATABASE` candidate category. The regex also filters out those unsupported metric names that contain a `;` in the endpoint (legacy format to concat different endpoints in a single metric).
This new rule, which will be internally rolled out, will eventually replace the two other rules present in the file.
> Add a generic rule for APM->DB relationships

- relationships/synthesis/APM-APPLICATION-to-INFRA-AWSAPPSYNCAPI.yml
In our spec conversation [here](https://source.datanerd.us/agents/agent-specs/pull/716/files) we mentioned that `peer.hostname` is for database spans not external client spans.  The attribute the agents will be setting the app sync url is `http.url`
> chore: Updated the app sync relationship to look at `http.url` which is where the app sync URL will live on external client calls

- relationships/synthesis/INFRA-KUBERNETES_DAEMONSET-to-EXT-FLUENTBIT_KUBERNETES.yml
This PR attempts to fix the issue of entity relationship not getting created between fluent bit and kubernetes daemonset
> fix: modified entity relationship for fluentbit kubernetes

- entity-types/ext-pdu/definition.yml
Reverts newrelic/entity-definitions#1830
Blocking other rules to proceed due to invalid dashboard.
> Revert "Update definition.yml"

- entity-types/ext-fluentbit_host/summary_metrics.yml
This PR adds summary metrics for Fluent Bit onhost entity.
> NR-353035 added summary metrics to fluentbit onhost

- relationships/synthesis/INFRA_DOCKER_CONTAINER-to-EXT_SERVICE.yml
- relationships/synthesis/INFRA_KUBERNETES_CONTAINER-to-EXT_SERVICE.yml
This PR adjusts the relationship rules for OTel instrumented services and infra entities.
1. Removed `entityType` from `extractGuid` because I believe it is unnecessary for these use cases.
2. The rules now match spans, logs, and metrics. This is because some otel services may not emit metrics.
@gkadapa-nr since you originally created these rules, please take a look.
> Revise OTel service to infra relationships

- relationships/synthesis/INFRA-KUBERNETES_DAEMONSET-to-EXT-FLUENTBIT_KUBERNETES.yml
This PR attempts to fix the k8sDaemonsetManagesFluentBitKubernetes Relationship by changing the origin of telemetry
> fix: changed origin of fluenbit entity relationship

- entity-types/infra-awsefsmounttarget/definition.yml
- entity-types/infra-awsekscluster/definition.yml
- Added `definition.yml` for `infra-efsmounttarget` with domain `INFRA` and type `AWSCOGNITOUSERPOOL`
- Added `definition.yml` for `infra-awsekscluster` with domain `INFRA` and type `AWSEKSCLUSTER`
> Add entity definitions for AWS EKS Cluster and AWS Mount target

- entity-types/ext-fluentbit_kubernetes/dashboard.json
This PR fixes the bug with a NRQL query in fluentbit kubernetes entity dashboard.
> fix: added where clause to nrql query

- relationships/candidates/CONTAINER.yml
Reverts newrelic/entity-definitions#1893
Removes rule for containers.
It is impacting the persistency layer performance and causing kafka consumer lag in our pipelines.
> Revert "feat: Add new lookup defining container candidate relationship"

- relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
The origin in Ext Service to Kafka Topic should be Distributed Tracing as we are receiving this event as a trace from trace-analyzer.
> fix: Change origin

- entity-types/ext-fluentbit_kubernetes/definition.yml
This PR attempts to make the version tag on the fluent bit entity single value so that any change in version would override the only available version.
> fix: restrict fb version to be single-valued

- relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
- relationships/synthesis/EXT-SERVICE-to-MEMCACHED.yml
Updated the span attributes used in relationship synthesis condition and mapping fields as per the latest Otel Symantic Conventions. Ref: https://opentelemetry.io/docs/specs/semconv/
> fix: Update the attribute names to latest semantic convention

- entity-types/ext-ibm_iseries/definition.yml
Added a new External IBM iSeries entity definition with the main goal being that our custom insights metric generated with an attribute of includeInIseriesEntity should be used to automatically create our IBM iSeries as an Entity and visible on distributed tracing maps
> Add ibm iseries

- relationships/candidates/HTTPSERVICE.yml
It was decided to change the lookup into nr.endpoint & endpoint instead of the current one
Updating to reflect the decision
> Change to endpoint for HTTPSERVICE lookup

- entity-types/infra-awsalb/definition.yml
- entity-types/infra-awscloudfrontdistribution/definition.yml
- entity-types/infra-awselb/definition.yml
- entity-types/infra-awslambdafunction/definition.yml
- entity-types/infra-awsnlb/definition.yml
- entity-types/infra-awsrdsdbinstance/definition.yml
- entity-types/infra-awss3bucket/definition.yml
- entity-types/infra-awssqsqueue/definition.yml
- entity-types/infra-host/definition.yml
This PR simply adds more explanatory comments as to where the data used by the affected rules comes from. For these rules, the Logs Pipeline pre-enriches the logs with some attributes like the `aws.Arn`, optionally an `entityId` and an entity name (`aws.lambda.FunctionName` or `aws.alb.loadBalancer`, for instance) so that entity synthesis can work. More information can be found here: https://docs.newrelic.com/docs/logs/logs-context/aws-logs-in-context/ (still being reviewed)
> Extends comments to clarify that these rules apply only to logs

- relationships/candidates/MEMCACHED_EXPLICIT.yml
- relationships/synthesis/EXT-SERVICE-to-MEMCACHED.yml
To simplify relationship creation between Otel service and AWS Memcached using manual instrumentation if auto instrumentation not supported, I have added a relationship called `extServiceCallsAwsElastiCacheMemcached_Explicit`. This only requires the client to send AWS resource arn to NR and the relationship will be created.
> Add relationship to support manual instrumentation

- entity-types/infra-awsefsmounttarget/definition.yml
- entity-types/infra-awsekscluster/definition.yml
These entities doe not have metrics and do not have to be shown in the Entity Explorer.
This is the same as other AWS entities such as VPC or Subnet
> alertable:false for AWSEFSMOUNTTARGET

- relationships/synthesis/EXT-SERVICE-to-INFRA-AWSMQBROKER.yml
- relationships/synthesis/EXT-SERVICE-to-KAFKATOPIC.yml
- relationships/synthesis/EXT-SERVICE-to-MEMCACHED.yml
- relationships/synthesis/EXT-SERVICE-to-REDIS.yml
For the explicit matching using arn, changed the regex by removing the capturing group. This is needed to create exclusinve matching conditions.
> Remove capturing group in arn regex

- relationships/synthesis/EXT-SERVICE-to-INFRA-AWSMQBROKER.yml
Attempt to fix regex for extServiceCallsAwsMqBroker_Explicit.
> Update extServiceCallsAwsMqBroker_Explicit regex

- entity-types/infra-kubernetes_cronjob/definition.yml
- entity-types/infra-kubernetes_daemonset/definition.yml
- entity-types/infra-kubernetes_deployment/definition.yml
- entity-types/infra-kubernetes_job/definition.yml
- entity-types/infra-kubernetes_persistentvolumeclaim/definition.yml
- entity-types/infra-kubernetes_statefulset/definition.yml
Expanding on the typo for k8s namespace name in k8s Otel
> Fix typo in k8s namespace attributes for Otel

- entity-types/ext-fluentbit_kubernetes/definition.yml
This PR attempts to add a new entity synthesis rule to the fluent bit kubernetes entity to synthesise entity from Log event types.
> feat: added new rule for fb k8s entity with log event

- entity-types/ext-fluentbit_host/definition.yml
- relationships/synthesis/INFRA-HOST-to-EXT-FLUENTBIT_HOST.yml
This reverts commit 7d22deb3d633a10f0aefe72c133b806130d61da2.
Reverting this change since it was meant to be just in STG and it was deployed to PROD. Will redeploy to STG afterwards
> Revert "fix: change fluent bit host entity identifier (#1962)"

- entity-types/infra-host/definition.yml
this rule will be removed soon as the next agent release for now making it a test entity only
> Update k8s Host entity rule to test entities only

- entity-types/ext-fluentbit_host/definition.yml
- relationships/synthesis/INFRA-HOST-to-EXT-FLUENTBIT_HOST.yml
This reverts commit e89aaf9e4c53a7cb1692335f553042e226e9a601.
Reapplying https://github.com/newrelic/entity-definitions/pull/1962 after it was reverted as it was only needed to test in STG.
> Revert "Revert "fix: change fluent bit host entity identifier (#1962)……" (#1963)"

- relationships/synthesis/APM-APPLICATION-to-INFRA-REDSHIFTCLUSTER.yml
Updating Redshift cluster APM-infra relationship file to update attribute as peer.hostname as discussed in the [thread](https://newrelic.slack.com/archives/C05UUMVP12T/p1744047457893939)
> feat:Updating Redshift cluster APM-infra relationship file to update peer.hostname

- entity-types/ext-aws_firehose_log_forwarder/definition.yml
- entity-types/ext-aws_firehose_log_forwarder/tests/Metric.json
This PR adds entity definition for a new entity called AWS_FIREHOSE_LOG_FORWARDER.
> NR-386014 added entity definition for aws firehose log forwarder

- entity-types/infra-mysqlnode/definition.yml
> add overrideGuidType legacy attribute to INFRA-MYSQLNODE

- entity-types/ext-service/definition.yml
- Added exclusion in otel rule for when `trace_role` field is present
- Add separate role for eBPF client and server as we don't want to add port tag for client
Removed
> fix: Remove local port from eBPF client role entity

- relationships/candidates/KUBERNETESCLUSTER.yml
fix k8s cluster candidate after tag renaming
https://github.com/newrelic/entity-definitions/pull/1988/files#diff-96cf068cf6341a9af9e6f95e394bd9be6a7dff844153839708721ab7db0993a9
https://new-relic.atlassian.net/browse/NR-416403
> fix k8s cluster candidate after tag renaming

- relationships/synthesis/EXT-AWS_FIREHOSE_LOG_FORWARDER-to-INFRA-KINESSISDELIVERYSTREAM.yml
- relationships/synthesis/EXT-AWS_LAMBDA_LOG_FORWARDER-to-INFRA-AWSLAMBDAFUNCTION.yml
This PR attempts to change the expiry on the relationships on AWS Log Forwarder entities from 75 minutes to 72 hours.
> Changed relationship TTL of AWS Lambda log forwarder entities

- entity-types/ext-aws_firehose_log_forwarder/golden_metrics.yml
This PR attempts to fix the issue of summary metrics not showing up for the AWS_FIREHOSE_LOG_FORWARDER entity.
> fix: change datasource in golden metrics definition for AWS firehose log forwarder entity

- relationships/candidates/CONTAINER.yml
Add a new lookup in for the CONTAINER candidate relationship definition to allow creating relationship between K8s container and Services without container id, using the clusterName, namespaceName, podName and containerName instead.
This rule should enabled cgroups v2 containers to be related to services without the need of container id. 
The previous attempt of including this rule was done here: https://github.com/newrelic/entity-definitions/pull/1763
> feat: Add new lookup defining container candidate relationship for cgroups v2

- entity-types/infra-ocihealthcheck/definition.yml
- entity-types/infra-ociobjectstorage/definition.yml
- entity-types/infra-ociobjectstorage/tests/Metric.json
This PR updates the OCI entities based on the data ingested from the OCI platform.
- Add synthesis rule for ping monitor
- Modify resourceId to resourceID for objectstorage
> fix(oci): Enhance OCI Entity Mapping with Ingested Data

- entity-types/infra-ocilbaas/definition.yml
Fixes typo in rule for INFRA|OCILBAAS
> chore: [NR-443333] Fixes typo in rule for INFRA|OCILBAAS

- entity-types/infra-elasticsearchnode/definition.stg.yml
Removed the "prefix: elasticsearch." condition in metric synthesis condition so that jvm metrics will also be synthesised for widget population
Right now due to `prefix: elasticsearch.` condition metrics with specified prefix are only synthesised and because of that jvm related widgets are not getting data
> fix(infra-elasticsearch): Remove metric synthesis condition to collect all metrics

- relationships/synthesis/BROWSER-VIDEO-to-MEDIA-STREAMING.yml
- relationships/synthesis/MOBILE-VIDEO-to-MEDIA-STREAMING.yml
Updated the relationship type from CONTAINS to CONNECTS_TO
The current implementation model uses the CONTAINS relationship to define the connection between a Standalone Mobile/Browser Agent and a Mobile/Browser Agent. This implies that one is a component or a subset of the other, which is not an accurate representation of the new architecture(Standalone).
Proposed Change:
We need to update this relationship type from CONTAINS to CONNECTS_TO.
CONTAINS (Set-Based Relationship): This relationship is best suited for scenarios where one entity is a composite of other entities. This no longer reflects the independent nature of the agents.
CONNECTS_TO (Network-Based Relationship): This relationship more accurately represents the new, decentralized architecture. It signifies that a Standalone …
> feat: update the relationship type

- entity-types/infra-nginxserver/definition.stg.yml
- entity-types/infra-nginxserver/tests/Metric.stg.json
Changes in this PR:
1. Remove `nginx.server.address` from composite Identifier of Nginx otel entity definition
2. Use `nginx.displayName` as name in the entity synthesis rule because the value of `nginx.server.address` might not be unique i.e localhost/127.0.0.1 can be used on multiple hosts.
Note: `nginx.displayName` will be created in the processor of otel collector and it will contain `host.id` to build a unique name per host. The above changes are for staging ENV.
> Update Nginx Otel Entity definition

- entity-types/infra-nginxserver/definition.stg.yml
- entity-types/infra-nginxserver/tests/Metric.stg.json
1. Use `nginx.deployment.name` and `nginx.server.endpoint` as a composite identifier.
2. Rename `nginx.displayName` to `nginx.display.name` to maintain consistency.
3. Make the synthesis rule work for older and new version of otel collector by defining the possible `otel.library.name` values.
`nginx.deployment.name` will be a unique input value from customer across the Infra space for an account.
> feat: update nginx otel synthesis rule

- relationships/candidates/HOST.yml
- Expanding host.id to cover Cloudwatch Metrics Stream Tags aws.ec2.host.id
> [NR-462796] Expanding hostId to cover aws.ec2.hostId

- entity-types/infra-ocifunction/definition.yml
- entity-types/infra-ocilbaas/definition.yml
- entity-types/infra-ociobjectstorage/definition.yml
- entity-types/infra-ociserviceconnectorhub/definition.yml
The feature-flagged attribute `logging.testing.synthesize.oci.entities` is no longer required for the OCI entity synthesis rules included in this PR, as they have been successfully tested.
> Removes feature-flagged logging.testing.synthesize.oci.entities attribute from OCI entity synthesis rules

- entity-types/ext-coredns/dashboard.json
- entity-types/ext-coredns/golden_metrics.yml
- entity-types/ext-coredns/opentelemetry_dashboard.json
Replace deprecated metrics from coredns queries
> fix: Replace deprecated metrics from coredns queries

- entity-types/infra-ociapigateway/definition.yml
- entity-types/infra-ociblockstore/definition.yml
- entity-types/infra-ociconnector/definition.yml
- entity-types/infra-ocicontainerinstance/definition.yml
- entity-types/infra-ocifunction/definition.yml
- entity-types/infra-ocihealthcheck/definition.yml
- entity-types/infra-ociinstancepool/definition.yml
- entity-types/infra-ocikubernetes/definition.yml
- entity-types/infra-ociloadbalancer/definition.yml
- entity-types/infra-ocinlb/definition.yml
- entity-types/infra-ociobjectstoragebucket/definition.yml
- entity-types/infra-ocipostgresqldatabase/definition.yml
- entity-types/infra-ociqueue/definition.yml
- entity-types/infra-ocistreaming/definition.yml
Set multiValue to false for providerAccountName in OCI entity definitions to avoid duplicate tag creation
> fix: Set multiValue to false for providerAccountName in OCI entity definitions to avoid duplicate tag creation
